DROP TABLE IF EXISTS PAFF_CUSTOMER;
DROP TABLE IF EXISTS PAFF_ORDER;

CREATE TABLE PAFF_CUSTOMER(ID INT IDENTITY  PRIMARY KEY, NAME VARCHAR(255),ADDRESS VARCHAR(255),MOBILE VARCHAR(32),MEMO VARCHAR(1024));
CREATE TABLE PAFF_ORDER (ID INT IDENTITY  PRIMARY KEY,CUSTOMER_ID INT, ORDER_NAME VARCHAR(12) ,ORDER_TIME VARCHAR(14),ORDER_DETAIL VARCHAR(1024));

INSERT INTO PAFF_CUSTOMER (ID , NAME,ADDRESS ,MOBILE ,MEMO) VALUES (1,'NAME1','SOMEWHERE1','1111111111','MEMO1');
INSERT INTO PAFF_CUSTOMER (ID , NAME,ADDRESS ,MOBILE ,MEMO) VALUES (2,'NAME2','SOMEWHERE2','2222222222','MEMO2');
INSERT INTO PAFF_CUSTOMER (ID , NAME,ADDRESS ,MOBILE ,MEMO) VALUES (3,'NAME3','SOMEWHERE3','3333333333','MEMO3');
INSERT INTO PAFF_CUSTOMER (ID , NAME,ADDRESS ,MOBILE ,MEMO) VALUES (4,'NAME4','SOMEWHERE4','4444444444','MEMO4');
INSERT INTO PAFF_CUSTOMER (ID , NAME,ADDRESS ,MOBILE ,MEMO) VALUES (5,'NAME5','SOMEWHERE5','5555555555','MEMO5');

INSERT INTO PAFF_ORDER (ID,CUSTOMER_ID,ORDER_NAME,ORDER_TIME ,ORDER_DETAIL) VALUES(1,'1','ONAME1','OTIME1','ODETAIL1');
INSERT INTO PAFF_ORDER (ID,CUSTOMER_ID,ORDER_NAME,ORDER_TIME ,ORDER_DETAIL) VALUES(2,'1','ONAME1','OTIME1','ODETAIL1');
INSERT INTO PAFF_ORDER (ID,CUSTOMER_ID,ORDER_NAME,ORDER_TIME ,ORDER_DETAIL) VALUES(3,'1','ONAME1','OTIME1','ODETAIL1');
INSERT INTO PAFF_ORDER (ID,CUSTOMER_ID,ORDER_NAME,ORDER_TIME ,ORDER_DETAIL) VALUES(4,'2','ONAME2','OTIME2','ODETAIL2');
INSERT INTO PAFF_ORDER (ID,CUSTOMER_ID,ORDER_NAME,ORDER_TIME ,ORDER_DETAIL) VALUES(5,'2','ONAME2','OTIME2','ODETAIL2');
INSERT INTO PAFF_ORDER (ID,CUSTOMER_ID,ORDER_NAME,ORDER_TIME ,ORDER_DETAIL) VALUES(6,'2','ONAME2','OTIME2','ODETAIL2');
INSERT INTO PAFF_ORDER (ID,CUSTOMER_ID,ORDER_NAME,ORDER_TIME ,ORDER_DETAIL) VALUES(7,'3','ONAME3','OTIME3','ODETAIL3');
INSERT INTO PAFF_ORDER (ID,CUSTOMER_ID,ORDER_NAME,ORDER_TIME ,ORDER_DETAIL) VALUES(8,'3','ONAME3','OTIME3','ODETAIL3');
INSERT INTO PAFF_ORDER (ID,CUSTOMER_ID,ORDER_NAME,ORDER_TIME ,ORDER_DETAIL) VALUES(9,'3','ONAME3','OTIME3','ODETAIL3');
INSERT INTO PAFF_ORDER (ID,CUSTOMER_ID,ORDER_NAME,ORDER_TIME ,ORDER_DETAIL) VALUES(10,'4','ONAME4','OTIME4','ODETAIL4');
INSERT INTO PAFF_ORDER (ID,CUSTOMER_ID,ORDER_NAME,ORDER_TIME ,ORDER_DETAIL) VALUES(11,'4','ONAME4','OTIME4','ODETAIL4');
INSERT INTO PAFF_ORDER (ID,CUSTOMER_ID,ORDER_NAME,ORDER_TIME ,ORDER_DETAIL) VALUES(12,'4','ONAME4','OTIME4','ODETAIL4');
INSERT INTO PAFF_ORDER (ID,CUSTOMER_ID,ORDER_NAME,ORDER_TIME ,ORDER_DETAIL) VALUES(13,'5','ONAME5','OTIME5','ODETAIL5');
INSERT INTO PAFF_ORDER (ID,CUSTOMER_ID,ORDER_NAME,ORDER_TIME ,ORDER_DETAIL) VALUES(14,'5','ONAME5','OTIME5','ODETAIL5');
INSERT INTO PAFF_ORDER (ID,CUSTOMER_ID,ORDER_NAME,ORDER_TIME ,ORDER_DETAIL) VALUES(15,'5','ONAME5','OTIME5','ODETAIL5');

COMMIT;