package com.chinadrtv.model.iagent;

public class AreaAll {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.AREA_ALL.AREAID
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    private Integer areaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.AREA_ALL.PROVID
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    private String provid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.AREA_ALL.CITYID
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    private Integer cityid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.AREA_ALL.COUNTYID
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    private Integer countyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.AREA_ALL.AREANAME
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    private String areaname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.AREA_ALL.AREAKEY
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    private String areakey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.AREA_ALL.FLAG
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    private String flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.AREA_ALL.ZIPCODE
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    private String zipcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.AREA_ALL.CODE
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.AREA_ALL.SPELLID
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    private Integer spellid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.AREA_ALL.AREAID
     *
     * @return the value of IAGENT.AREA_ALL.AREAID
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    public Integer getAreaid() {
        return areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.AREA_ALL.AREAID
     *
     * @param areaid the value for IAGENT.AREA_ALL.AREAID
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    public void setAreaid(Integer areaid) {
        this.areaid = areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.AREA_ALL.PROVID
     *
     * @return the value of IAGENT.AREA_ALL.PROVID
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    public String getProvid() {
        return provid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.AREA_ALL.PROVID
     *
     * @param provid the value for IAGENT.AREA_ALL.PROVID
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    public void setProvid(String provid) {
        this.provid = provid == null ? null : provid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.AREA_ALL.CITYID
     *
     * @return the value of IAGENT.AREA_ALL.CITYID
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    public Integer getCityid() {
        return cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.AREA_ALL.CITYID
     *
     * @param cityid the value for IAGENT.AREA_ALL.CITYID
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    public void setCityid(Integer cityid) {
        this.cityid = cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.AREA_ALL.COUNTYID
     *
     * @return the value of IAGENT.AREA_ALL.COUNTYID
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    public Integer getCountyid() {
        return countyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.AREA_ALL.COUNTYID
     *
     * @param countyid the value for IAGENT.AREA_ALL.COUNTYID
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    public void setCountyid(Integer countyid) {
        this.countyid = countyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.AREA_ALL.AREANAME
     *
     * @return the value of IAGENT.AREA_ALL.AREANAME
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    public String getAreaname() {
        return areaname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.AREA_ALL.AREANAME
     *
     * @param areaname the value for IAGENT.AREA_ALL.AREANAME
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    public void setAreaname(String areaname) {
        this.areaname = areaname == null ? null : areaname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.AREA_ALL.AREAKEY
     *
     * @return the value of IAGENT.AREA_ALL.AREAKEY
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    public String getAreakey() {
        return areakey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.AREA_ALL.AREAKEY
     *
     * @param areakey the value for IAGENT.AREA_ALL.AREAKEY
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    public void setAreakey(String areakey) {
        this.areakey = areakey == null ? null : areakey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.AREA_ALL.FLAG
     *
     * @return the value of IAGENT.AREA_ALL.FLAG
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.AREA_ALL.FLAG
     *
     * @param flag the value for IAGENT.AREA_ALL.FLAG
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    public void setFlag(String flag) {
        this.flag = flag == null ? null : flag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.AREA_ALL.ZIPCODE
     *
     * @return the value of IAGENT.AREA_ALL.ZIPCODE
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    public String getZipcode() {
        return zipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.AREA_ALL.ZIPCODE
     *
     * @param zipcode the value for IAGENT.AREA_ALL.ZIPCODE
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    public void setZipcode(String zipcode) {
        this.zipcode = zipcode == null ? null : zipcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.AREA_ALL.CODE
     *
     * @return the value of IAGENT.AREA_ALL.CODE
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.AREA_ALL.CODE
     *
     * @param code the value for IAGENT.AREA_ALL.CODE
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.AREA_ALL.SPELLID
     *
     * @return the value of IAGENT.AREA_ALL.SPELLID
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    public Integer getSpellid() {
        return spellid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.AREA_ALL.SPELLID
     *
     * @param spellid the value for IAGENT.AREA_ALL.SPELLID
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    public void setSpellid(Integer spellid) {
        this.spellid = spellid;
    }
}