package com.chinadrtv.model.iagent;

public class CityAll {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.CITY_ALL.CITYID
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    private Integer cityid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.CITY_ALL.PROVID
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    private String provid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.CITY_ALL.CITYNAME
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    private String cityname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.CITY_ALL.CITYKEY
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    private String citykey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.CITY_ALL.CITY_FLAG
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    private String cityFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.CITY_ALL.ZIPCODE
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    private String zipcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.CITY_ALL.CODE
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.CITY_ALL.AREACODE
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    private String areacode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.CITY_ALL.SPELLID
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    private Integer spellid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.CITY_ALL.CITYID
     *
     * @return the value of IAGENT.CITY_ALL.CITYID
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    public Integer getCityid() {
        return cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.CITY_ALL.CITYID
     *
     * @param cityid the value for IAGENT.CITY_ALL.CITYID
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    public void setCityid(Integer cityid) {
        this.cityid = cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.CITY_ALL.PROVID
     *
     * @return the value of IAGENT.CITY_ALL.PROVID
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    public String getProvid() {
        return provid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.CITY_ALL.PROVID
     *
     * @param provid the value for IAGENT.CITY_ALL.PROVID
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    public void setProvid(String provid) {
        this.provid = provid == null ? null : provid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.CITY_ALL.CITYNAME
     *
     * @return the value of IAGENT.CITY_ALL.CITYNAME
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    public String getCityname() {
        return cityname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.CITY_ALL.CITYNAME
     *
     * @param cityname the value for IAGENT.CITY_ALL.CITYNAME
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    public void setCityname(String cityname) {
        this.cityname = cityname == null ? null : cityname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.CITY_ALL.CITYKEY
     *
     * @return the value of IAGENT.CITY_ALL.CITYKEY
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    public String getCitykey() {
        return citykey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.CITY_ALL.CITYKEY
     *
     * @param citykey the value for IAGENT.CITY_ALL.CITYKEY
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    public void setCitykey(String citykey) {
        this.citykey = citykey == null ? null : citykey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.CITY_ALL.CITY_FLAG
     *
     * @return the value of IAGENT.CITY_ALL.CITY_FLAG
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    public String getCityFlag() {
        return cityFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.CITY_ALL.CITY_FLAG
     *
     * @param cityFlag the value for IAGENT.CITY_ALL.CITY_FLAG
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    public void setCityFlag(String cityFlag) {
        this.cityFlag = cityFlag == null ? null : cityFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.CITY_ALL.ZIPCODE
     *
     * @return the value of IAGENT.CITY_ALL.ZIPCODE
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    public String getZipcode() {
        return zipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.CITY_ALL.ZIPCODE
     *
     * @param zipcode the value for IAGENT.CITY_ALL.ZIPCODE
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    public void setZipcode(String zipcode) {
        this.zipcode = zipcode == null ? null : zipcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.CITY_ALL.CODE
     *
     * @return the value of IAGENT.CITY_ALL.CODE
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.CITY_ALL.CODE
     *
     * @param code the value for IAGENT.CITY_ALL.CODE
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.CITY_ALL.AREACODE
     *
     * @return the value of IAGENT.CITY_ALL.AREACODE
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    public String getAreacode() {
        return areacode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.CITY_ALL.AREACODE
     *
     * @param areacode the value for IAGENT.CITY_ALL.AREACODE
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    public void setAreacode(String areacode) {
        this.areacode = areacode == null ? null : areacode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.CITY_ALL.SPELLID
     *
     * @return the value of IAGENT.CITY_ALL.SPELLID
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    public Integer getSpellid() {
        return spellid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.CITY_ALL.SPELLID
     *
     * @param spellid the value for IAGENT.CITY_ALL.SPELLID
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    public void setSpellid(Integer spellid) {
        this.spellid = spellid;
    }
}