package com.chinadrtv.model.iagent;

import java.math.BigDecimal;

public class Company {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.COMPANY.COMPANYID
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    private String companyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.COMPANY.TYPEID
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    private String typeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.COMPANY.NAME
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.COMPANY.ADDRESS
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.COMPANY.ZIP
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    private String zip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.COMPANY.FAX
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    private String fax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.COMPANY.DESCRIPTION
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.COMPANY.REMARK
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.COMPANY.AREA_CODE
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    private String areaCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.COMPANY.PHONE
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.COMPANY.SUBPHONE
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    private String subphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.COMPANY.SHORT_CODE
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    private String shortCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.COMPANY.SPELLID
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    private String spellid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.COMPANY.CITY_NAME
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    private String cityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.COMPANY.MAIL_CODE
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    private String mailCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.COMPANY.EMAIL
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.COMPANY.MAILTYPE
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    private String mailtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.COMPANY.POSTFEE
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    private BigDecimal postfee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.COMPANY.ISRESELLER
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    private String isreseller;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.COMPANY.PROVINCEID
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    private String provinceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.COMPANY.REFPOSTFEE
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    private BigDecimal refpostfee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.COMPANY.BILL
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    private String bill;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.COMPANY.NCCOMPANYID
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    private String nccompanyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.COMPANY.BILLPOSTFEE
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    private String billpostfee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.COMPANY.NOUSEBILL
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    private String nousebill;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.COMPANY.TO_WAREHOUSE
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    private String toWarehouse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.COMPANY.AREACODE
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    private String areacode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.COMPANY.CITYNAME
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    private String cityname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.COMPANY.MAILCODE
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    private String mailcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.COMPANY.SHORTCODE
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    private String shortcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.COMPANY.WAREHOUSEID
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    private BigDecimal warehouseid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.COMPANY.COMPANYID
     *
     * @return the value of IAGENT.COMPANY.COMPANYID
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    public String getCompanyid() {
        return companyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.COMPANY.COMPANYID
     *
     * @param companyid the value for IAGENT.COMPANY.COMPANYID
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    public void setCompanyid(String companyid) {
        this.companyid = companyid == null ? null : companyid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.COMPANY.TYPEID
     *
     * @return the value of IAGENT.COMPANY.TYPEID
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    public String getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.COMPANY.TYPEID
     *
     * @param typeid the value for IAGENT.COMPANY.TYPEID
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    public void setTypeid(String typeid) {
        this.typeid = typeid == null ? null : typeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.COMPANY.NAME
     *
     * @return the value of IAGENT.COMPANY.NAME
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.COMPANY.NAME
     *
     * @param name the value for IAGENT.COMPANY.NAME
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.COMPANY.ADDRESS
     *
     * @return the value of IAGENT.COMPANY.ADDRESS
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.COMPANY.ADDRESS
     *
     * @param address the value for IAGENT.COMPANY.ADDRESS
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.COMPANY.ZIP
     *
     * @return the value of IAGENT.COMPANY.ZIP
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    public String getZip() {
        return zip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.COMPANY.ZIP
     *
     * @param zip the value for IAGENT.COMPANY.ZIP
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    public void setZip(String zip) {
        this.zip = zip == null ? null : zip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.COMPANY.FAX
     *
     * @return the value of IAGENT.COMPANY.FAX
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.COMPANY.FAX
     *
     * @param fax the value for IAGENT.COMPANY.FAX
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.COMPANY.DESCRIPTION
     *
     * @return the value of IAGENT.COMPANY.DESCRIPTION
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.COMPANY.DESCRIPTION
     *
     * @param description the value for IAGENT.COMPANY.DESCRIPTION
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.COMPANY.REMARK
     *
     * @return the value of IAGENT.COMPANY.REMARK
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.COMPANY.REMARK
     *
     * @param remark the value for IAGENT.COMPANY.REMARK
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.COMPANY.AREA_CODE
     *
     * @return the value of IAGENT.COMPANY.AREA_CODE
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.COMPANY.AREA_CODE
     *
     * @param areaCode the value for IAGENT.COMPANY.AREA_CODE
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode == null ? null : areaCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.COMPANY.PHONE
     *
     * @return the value of IAGENT.COMPANY.PHONE
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.COMPANY.PHONE
     *
     * @param phone the value for IAGENT.COMPANY.PHONE
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.COMPANY.SUBPHONE
     *
     * @return the value of IAGENT.COMPANY.SUBPHONE
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    public String getSubphone() {
        return subphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.COMPANY.SUBPHONE
     *
     * @param subphone the value for IAGENT.COMPANY.SUBPHONE
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    public void setSubphone(String subphone) {
        this.subphone = subphone == null ? null : subphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.COMPANY.SHORT_CODE
     *
     * @return the value of IAGENT.COMPANY.SHORT_CODE
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    public String getShortCode() {
        return shortCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.COMPANY.SHORT_CODE
     *
     * @param shortCode the value for IAGENT.COMPANY.SHORT_CODE
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    public void setShortCode(String shortCode) {
        this.shortCode = shortCode == null ? null : shortCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.COMPANY.SPELLID
     *
     * @return the value of IAGENT.COMPANY.SPELLID
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    public String getSpellid() {
        return spellid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.COMPANY.SPELLID
     *
     * @param spellid the value for IAGENT.COMPANY.SPELLID
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    public void setSpellid(String spellid) {
        this.spellid = spellid == null ? null : spellid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.COMPANY.CITY_NAME
     *
     * @return the value of IAGENT.COMPANY.CITY_NAME
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.COMPANY.CITY_NAME
     *
     * @param cityName the value for IAGENT.COMPANY.CITY_NAME
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    public void setCityName(String cityName) {
        this.cityName = cityName == null ? null : cityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.COMPANY.MAIL_CODE
     *
     * @return the value of IAGENT.COMPANY.MAIL_CODE
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    public String getMailCode() {
        return mailCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.COMPANY.MAIL_CODE
     *
     * @param mailCode the value for IAGENT.COMPANY.MAIL_CODE
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    public void setMailCode(String mailCode) {
        this.mailCode = mailCode == null ? null : mailCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.COMPANY.EMAIL
     *
     * @return the value of IAGENT.COMPANY.EMAIL
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.COMPANY.EMAIL
     *
     * @param email the value for IAGENT.COMPANY.EMAIL
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.COMPANY.MAILTYPE
     *
     * @return the value of IAGENT.COMPANY.MAILTYPE
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    public String getMailtype() {
        return mailtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.COMPANY.MAILTYPE
     *
     * @param mailtype the value for IAGENT.COMPANY.MAILTYPE
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    public void setMailtype(String mailtype) {
        this.mailtype = mailtype == null ? null : mailtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.COMPANY.POSTFEE
     *
     * @return the value of IAGENT.COMPANY.POSTFEE
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    public BigDecimal getPostfee() {
        return postfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.COMPANY.POSTFEE
     *
     * @param postfee the value for IAGENT.COMPANY.POSTFEE
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    public void setPostfee(BigDecimal postfee) {
        this.postfee = postfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.COMPANY.ISRESELLER
     *
     * @return the value of IAGENT.COMPANY.ISRESELLER
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    public String getIsreseller() {
        return isreseller;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.COMPANY.ISRESELLER
     *
     * @param isreseller the value for IAGENT.COMPANY.ISRESELLER
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    public void setIsreseller(String isreseller) {
        this.isreseller = isreseller == null ? null : isreseller.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.COMPANY.PROVINCEID
     *
     * @return the value of IAGENT.COMPANY.PROVINCEID
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    public String getProvinceid() {
        return provinceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.COMPANY.PROVINCEID
     *
     * @param provinceid the value for IAGENT.COMPANY.PROVINCEID
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    public void setProvinceid(String provinceid) {
        this.provinceid = provinceid == null ? null : provinceid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.COMPANY.REFPOSTFEE
     *
     * @return the value of IAGENT.COMPANY.REFPOSTFEE
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    public BigDecimal getRefpostfee() {
        return refpostfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.COMPANY.REFPOSTFEE
     *
     * @param refpostfee the value for IAGENT.COMPANY.REFPOSTFEE
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    public void setRefpostfee(BigDecimal refpostfee) {
        this.refpostfee = refpostfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.COMPANY.BILL
     *
     * @return the value of IAGENT.COMPANY.BILL
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    public String getBill() {
        return bill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.COMPANY.BILL
     *
     * @param bill the value for IAGENT.COMPANY.BILL
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    public void setBill(String bill) {
        this.bill = bill == null ? null : bill.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.COMPANY.NCCOMPANYID
     *
     * @return the value of IAGENT.COMPANY.NCCOMPANYID
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    public String getNccompanyid() {
        return nccompanyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.COMPANY.NCCOMPANYID
     *
     * @param nccompanyid the value for IAGENT.COMPANY.NCCOMPANYID
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    public void setNccompanyid(String nccompanyid) {
        this.nccompanyid = nccompanyid == null ? null : nccompanyid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.COMPANY.BILLPOSTFEE
     *
     * @return the value of IAGENT.COMPANY.BILLPOSTFEE
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    public String getBillpostfee() {
        return billpostfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.COMPANY.BILLPOSTFEE
     *
     * @param billpostfee the value for IAGENT.COMPANY.BILLPOSTFEE
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    public void setBillpostfee(String billpostfee) {
        this.billpostfee = billpostfee == null ? null : billpostfee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.COMPANY.NOUSEBILL
     *
     * @return the value of IAGENT.COMPANY.NOUSEBILL
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    public String getNousebill() {
        return nousebill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.COMPANY.NOUSEBILL
     *
     * @param nousebill the value for IAGENT.COMPANY.NOUSEBILL
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    public void setNousebill(String nousebill) {
        this.nousebill = nousebill == null ? null : nousebill.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.COMPANY.TO_WAREHOUSE
     *
     * @return the value of IAGENT.COMPANY.TO_WAREHOUSE
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    public String getToWarehouse() {
        return toWarehouse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.COMPANY.TO_WAREHOUSE
     *
     * @param toWarehouse the value for IAGENT.COMPANY.TO_WAREHOUSE
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    public void setToWarehouse(String toWarehouse) {
        this.toWarehouse = toWarehouse == null ? null : toWarehouse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.COMPANY.AREACODE
     *
     * @return the value of IAGENT.COMPANY.AREACODE
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    public String getAreacode() {
        return areacode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.COMPANY.AREACODE
     *
     * @param areacode the value for IAGENT.COMPANY.AREACODE
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    public void setAreacode(String areacode) {
        this.areacode = areacode == null ? null : areacode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.COMPANY.CITYNAME
     *
     * @return the value of IAGENT.COMPANY.CITYNAME
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    public String getCityname() {
        return cityname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.COMPANY.CITYNAME
     *
     * @param cityname the value for IAGENT.COMPANY.CITYNAME
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    public void setCityname(String cityname) {
        this.cityname = cityname == null ? null : cityname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.COMPANY.MAILCODE
     *
     * @return the value of IAGENT.COMPANY.MAILCODE
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    public String getMailcode() {
        return mailcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.COMPANY.MAILCODE
     *
     * @param mailcode the value for IAGENT.COMPANY.MAILCODE
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    public void setMailcode(String mailcode) {
        this.mailcode = mailcode == null ? null : mailcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.COMPANY.SHORTCODE
     *
     * @return the value of IAGENT.COMPANY.SHORTCODE
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    public String getShortcode() {
        return shortcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.COMPANY.SHORTCODE
     *
     * @param shortcode the value for IAGENT.COMPANY.SHORTCODE
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    public void setShortcode(String shortcode) {
        this.shortcode = shortcode == null ? null : shortcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.COMPANY.WAREHOUSEID
     *
     * @return the value of IAGENT.COMPANY.WAREHOUSEID
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    public BigDecimal getWarehouseid() {
        return warehouseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.COMPANY.WAREHOUSEID
     *
     * @param warehouseid the value for IAGENT.COMPANY.WAREHOUSEID
     *
     * @mbggenerated Tue Nov 05 10:25:43 CST 2013
     */
    public void setWarehouseid(BigDecimal warehouseid) {
        this.warehouseid = warehouseid;
    }
}