package com.chinadrtv.model.iagent;

public class CountyAll {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.COUNTY_ALL.COUNTYID
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    private Integer countyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.COUNTY_ALL.PROVID
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    private String provid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.COUNTY_ALL.CITYID
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    private Integer cityid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.COUNTY_ALL.COUNTYNAME
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    private String countyname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.COUNTY_ALL.COUNTYKEY
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    private String countykey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.COUNTY_ALL.COUNT_FLAG
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    private String countFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.COUNTY_ALL.ZIPCODE
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    private String zipcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.COUNTY_ALL.CODE
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.COUNTY_ALL.AREACODE
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    private String areacode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.COUNTY_ALL.SPELLID
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    private Integer spellid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.COUNTY_ALL.COUNTYID
     *
     * @return the value of IAGENT.COUNTY_ALL.COUNTYID
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    public Integer getCountyid() {
        return countyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.COUNTY_ALL.COUNTYID
     *
     * @param countyid the value for IAGENT.COUNTY_ALL.COUNTYID
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    public void setCountyid(Integer countyid) {
        this.countyid = countyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.COUNTY_ALL.PROVID
     *
     * @return the value of IAGENT.COUNTY_ALL.PROVID
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    public String getProvid() {
        return provid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.COUNTY_ALL.PROVID
     *
     * @param provid the value for IAGENT.COUNTY_ALL.PROVID
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    public void setProvid(String provid) {
        this.provid = provid == null ? null : provid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.COUNTY_ALL.CITYID
     *
     * @return the value of IAGENT.COUNTY_ALL.CITYID
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    public Integer getCityid() {
        return cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.COUNTY_ALL.CITYID
     *
     * @param cityid the value for IAGENT.COUNTY_ALL.CITYID
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    public void setCityid(Integer cityid) {
        this.cityid = cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.COUNTY_ALL.COUNTYNAME
     *
     * @return the value of IAGENT.COUNTY_ALL.COUNTYNAME
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    public String getCountyname() {
        return countyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.COUNTY_ALL.COUNTYNAME
     *
     * @param countyname the value for IAGENT.COUNTY_ALL.COUNTYNAME
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    public void setCountyname(String countyname) {
        this.countyname = countyname == null ? null : countyname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.COUNTY_ALL.COUNTYKEY
     *
     * @return the value of IAGENT.COUNTY_ALL.COUNTYKEY
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    public String getCountykey() {
        return countykey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.COUNTY_ALL.COUNTYKEY
     *
     * @param countykey the value for IAGENT.COUNTY_ALL.COUNTYKEY
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    public void setCountykey(String countykey) {
        this.countykey = countykey == null ? null : countykey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.COUNTY_ALL.COUNT_FLAG
     *
     * @return the value of IAGENT.COUNTY_ALL.COUNT_FLAG
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    public String getCountFlag() {
        return countFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.COUNTY_ALL.COUNT_FLAG
     *
     * @param countFlag the value for IAGENT.COUNTY_ALL.COUNT_FLAG
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    public void setCountFlag(String countFlag) {
        this.countFlag = countFlag == null ? null : countFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.COUNTY_ALL.ZIPCODE
     *
     * @return the value of IAGENT.COUNTY_ALL.ZIPCODE
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    public String getZipcode() {
        return zipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.COUNTY_ALL.ZIPCODE
     *
     * @param zipcode the value for IAGENT.COUNTY_ALL.ZIPCODE
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    public void setZipcode(String zipcode) {
        this.zipcode = zipcode == null ? null : zipcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.COUNTY_ALL.CODE
     *
     * @return the value of IAGENT.COUNTY_ALL.CODE
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.COUNTY_ALL.CODE
     *
     * @param code the value for IAGENT.COUNTY_ALL.CODE
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.COUNTY_ALL.AREACODE
     *
     * @return the value of IAGENT.COUNTY_ALL.AREACODE
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    public String getAreacode() {
        return areacode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.COUNTY_ALL.AREACODE
     *
     * @param areacode the value for IAGENT.COUNTY_ALL.AREACODE
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    public void setAreacode(String areacode) {
        this.areacode = areacode == null ? null : areacode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.COUNTY_ALL.SPELLID
     *
     * @return the value of IAGENT.COUNTY_ALL.SPELLID
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    public Integer getSpellid() {
        return spellid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.COUNTY_ALL.SPELLID
     *
     * @param spellid the value for IAGENT.COUNTY_ALL.SPELLID
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    public void setSpellid(Integer spellid) {
        this.spellid = spellid;
    }
}