package com.chinadrtv.model.iagent;

public class MailOperCustomize {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.MAIL_OPER_CUSTOMIZE.OPERATYPE
     *
     * @mbggenerated Wed Oct 23 15:46:30 CST 2013
     */
    private String operatype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.MAIL_OPER_CUSTOMIZE.CUSTOMIZESTATUS
     *
     * @mbggenerated Wed Oct 23 15:46:30 CST 2013
     */
    private String customizestatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.MAIL_OPER_CUSTOMIZE.ISVALID
     *
     * @mbggenerated Wed Oct 23 15:46:30 CST 2013
     */
    private String isvalid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.MAIL_OPER_CUSTOMIZE.OPERATYPE
     *
     * @return the value of IAGENT.MAIL_OPER_CUSTOMIZE.OPERATYPE
     *
     * @mbggenerated Wed Oct 23 15:46:30 CST 2013
     */
    public String getOperatype() {
        return operatype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.MAIL_OPER_CUSTOMIZE.OPERATYPE
     *
     * @param operatype the value for IAGENT.MAIL_OPER_CUSTOMIZE.OPERATYPE
     *
     * @mbggenerated Wed Oct 23 15:46:30 CST 2013
     */
    public void setOperatype(String operatype) {
        this.operatype = operatype == null ? null : operatype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.MAIL_OPER_CUSTOMIZE.CUSTOMIZESTATUS
     *
     * @return the value of IAGENT.MAIL_OPER_CUSTOMIZE.CUSTOMIZESTATUS
     *
     * @mbggenerated Wed Oct 23 15:46:30 CST 2013
     */
    public String getCustomizestatus() {
        return customizestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.MAIL_OPER_CUSTOMIZE.CUSTOMIZESTATUS
     *
     * @param customizestatus the value for IAGENT.MAIL_OPER_CUSTOMIZE.CUSTOMIZESTATUS
     *
     * @mbggenerated Wed Oct 23 15:46:30 CST 2013
     */
    public void setCustomizestatus(String customizestatus) {
        this.customizestatus = customizestatus == null ? null : customizestatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.MAIL_OPER_CUSTOMIZE.ISVALID
     *
     * @return the value of IAGENT.MAIL_OPER_CUSTOMIZE.ISVALID
     *
     * @mbggenerated Wed Oct 23 15:46:30 CST 2013
     */
    public String getIsvalid() {
        return isvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.MAIL_OPER_CUSTOMIZE.ISVALID
     *
     * @param isvalid the value for IAGENT.MAIL_OPER_CUSTOMIZE.ISVALID
     *
     * @mbggenerated Wed Oct 23 15:46:30 CST 2013
     */
    public void setIsvalid(String isvalid) {
        this.isvalid = isvalid == null ? null : isvalid.trim();
    }
}