package com.chinadrtv.model.iagent;

import java.math.BigDecimal;
import java.util.Date;

public class MailStatusHis {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.MAIL_STATUS_HIS.RECORD_ID
     *
     * @mbggenerated Wed Oct 23 16:06:25 CST 2013
     */
    private BigDecimal recordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.MAIL_STATUS_HIS.SHIPMENT_ID
     *
     * @mbggenerated Wed Oct 23 16:06:25 CST 2013
     */
    private String shipmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.MAIL_STATUS_HIS.MAILID
     *
     * @mbggenerated Wed Oct 23 16:06:25 CST 2013
     */
    private String mailid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.MAIL_STATUS_HIS.STATUS_CODE
     *
     * @mbggenerated Wed Oct 23 16:06:25 CST 2013
     */
    private String statusCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.MAIL_STATUS_HIS.REASON_CODE
     *
     * @mbggenerated Wed Oct 23 16:06:25 CST 2013
     */
    private String reasonCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.MAIL_STATUS_HIS.SIGN_RESULT
     *
     * @mbggenerated Wed Oct 23 16:06:25 CST 2013
     */
    private String signResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.MAIL_STATUS_HIS.EMS_DATE_TIME_STAMP
     *
     * @mbggenerated Wed Oct 23 16:06:25 CST 2013
     */
    private Date emsDateTimeStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.MAIL_STATUS_HIS.IS_PROCESSED
     *
     * @mbggenerated Wed Oct 23 16:06:25 CST 2013
     */
    private String isProcessed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.MAIL_STATUS_HIS.DATE_TIME_STAMP
     *
     * @mbggenerated Wed Oct 23 16:06:25 CST 2013
     */
    private Date dateTimeStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.MAIL_STATUS_HIS.COMPANYID
     *
     * @mbggenerated Wed Oct 23 16:06:25 CST 2013
     */
    private String companyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.MAIL_STATUS_HIS.OPERATYPE
     *
     * @mbggenerated Wed Oct 23 16:06:25 CST 2013
     */
    private String operatype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.MAIL_STATUS_HIS.OPERADATE
     *
     * @mbggenerated Wed Oct 23 16:06:25 CST 2013
     */
    private Date operadate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.MAIL_STATUS_HIS.STATION
     *
     * @mbggenerated Wed Oct 23 16:06:25 CST 2013
     */
    private String station;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.MAIL_STATUS_HIS.OPTOR
     *
     * @mbggenerated Wed Oct 23 16:06:25 CST 2013
     */
    private String optor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.MAIL_STATUS_HIS.REFUSEREASON
     *
     * @mbggenerated Wed Oct 23 16:06:25 CST 2013
     */
    private String refusereason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.MAIL_STATUS_HIS.PROBLEMREASON
     *
     * @mbggenerated Wed Oct 23 16:06:25 CST 2013
     */
    private String problemreason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.MAIL_STATUS_HIS.REMARKS
     *
     * @mbggenerated Wed Oct 23 16:06:25 CST 2013
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.MAIL_STATUS_HIS.RECORD_ID
     *
     * @return the value of IAGENT.MAIL_STATUS_HIS.RECORD_ID
     *
     * @mbggenerated Wed Oct 23 16:06:25 CST 2013
     */
    public BigDecimal getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.MAIL_STATUS_HIS.RECORD_ID
     *
     * @param recordId the value for IAGENT.MAIL_STATUS_HIS.RECORD_ID
     *
     * @mbggenerated Wed Oct 23 16:06:25 CST 2013
     */
    public void setRecordId(BigDecimal recordId) {
        this.recordId = recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.MAIL_STATUS_HIS.SHIPMENT_ID
     *
     * @return the value of IAGENT.MAIL_STATUS_HIS.SHIPMENT_ID
     *
     * @mbggenerated Wed Oct 23 16:06:25 CST 2013
     */
    public String getShipmentId() {
        return shipmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.MAIL_STATUS_HIS.SHIPMENT_ID
     *
     * @param shipmentId the value for IAGENT.MAIL_STATUS_HIS.SHIPMENT_ID
     *
     * @mbggenerated Wed Oct 23 16:06:25 CST 2013
     */
    public void setShipmentId(String shipmentId) {
        this.shipmentId = shipmentId == null ? null : shipmentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.MAIL_STATUS_HIS.MAILID
     *
     * @return the value of IAGENT.MAIL_STATUS_HIS.MAILID
     *
     * @mbggenerated Wed Oct 23 16:06:25 CST 2013
     */
    public String getMailid() {
        return mailid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.MAIL_STATUS_HIS.MAILID
     *
     * @param mailid the value for IAGENT.MAIL_STATUS_HIS.MAILID
     *
     * @mbggenerated Wed Oct 23 16:06:25 CST 2013
     */
    public void setMailid(String mailid) {
        this.mailid = mailid == null ? null : mailid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.MAIL_STATUS_HIS.STATUS_CODE
     *
     * @return the value of IAGENT.MAIL_STATUS_HIS.STATUS_CODE
     *
     * @mbggenerated Wed Oct 23 16:06:25 CST 2013
     */
    public String getStatusCode() {
        return statusCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.MAIL_STATUS_HIS.STATUS_CODE
     *
     * @param statusCode the value for IAGENT.MAIL_STATUS_HIS.STATUS_CODE
     *
     * @mbggenerated Wed Oct 23 16:06:25 CST 2013
     */
    public void setStatusCode(String statusCode) {
        this.statusCode = statusCode == null ? null : statusCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.MAIL_STATUS_HIS.REASON_CODE
     *
     * @return the value of IAGENT.MAIL_STATUS_HIS.REASON_CODE
     *
     * @mbggenerated Wed Oct 23 16:06:25 CST 2013
     */
    public String getReasonCode() {
        return reasonCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.MAIL_STATUS_HIS.REASON_CODE
     *
     * @param reasonCode the value for IAGENT.MAIL_STATUS_HIS.REASON_CODE
     *
     * @mbggenerated Wed Oct 23 16:06:25 CST 2013
     */
    public void setReasonCode(String reasonCode) {
        this.reasonCode = reasonCode == null ? null : reasonCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.MAIL_STATUS_HIS.SIGN_RESULT
     *
     * @return the value of IAGENT.MAIL_STATUS_HIS.SIGN_RESULT
     *
     * @mbggenerated Wed Oct 23 16:06:25 CST 2013
     */
    public String getSignResult() {
        return signResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.MAIL_STATUS_HIS.SIGN_RESULT
     *
     * @param signResult the value for IAGENT.MAIL_STATUS_HIS.SIGN_RESULT
     *
     * @mbggenerated Wed Oct 23 16:06:25 CST 2013
     */
    public void setSignResult(String signResult) {
        this.signResult = signResult == null ? null : signResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.MAIL_STATUS_HIS.EMS_DATE_TIME_STAMP
     *
     * @return the value of IAGENT.MAIL_STATUS_HIS.EMS_DATE_TIME_STAMP
     *
     * @mbggenerated Wed Oct 23 16:06:25 CST 2013
     */
    public Date getEmsDateTimeStamp() {
        return emsDateTimeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.MAIL_STATUS_HIS.EMS_DATE_TIME_STAMP
     *
     * @param emsDateTimeStamp the value for IAGENT.MAIL_STATUS_HIS.EMS_DATE_TIME_STAMP
     *
     * @mbggenerated Wed Oct 23 16:06:25 CST 2013
     */
    public void setEmsDateTimeStamp(Date emsDateTimeStamp) {
        this.emsDateTimeStamp = emsDateTimeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.MAIL_STATUS_HIS.IS_PROCESSED
     *
     * @return the value of IAGENT.MAIL_STATUS_HIS.IS_PROCESSED
     *
     * @mbggenerated Wed Oct 23 16:06:25 CST 2013
     */
    public String getIsProcessed() {
        return isProcessed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.MAIL_STATUS_HIS.IS_PROCESSED
     *
     * @param isProcessed the value for IAGENT.MAIL_STATUS_HIS.IS_PROCESSED
     *
     * @mbggenerated Wed Oct 23 16:06:25 CST 2013
     */
    public void setIsProcessed(String isProcessed) {
        this.isProcessed = isProcessed == null ? null : isProcessed.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.MAIL_STATUS_HIS.DATE_TIME_STAMP
     *
     * @return the value of IAGENT.MAIL_STATUS_HIS.DATE_TIME_STAMP
     *
     * @mbggenerated Wed Oct 23 16:06:25 CST 2013
     */
    public Date getDateTimeStamp() {
        return dateTimeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.MAIL_STATUS_HIS.DATE_TIME_STAMP
     *
     * @param dateTimeStamp the value for IAGENT.MAIL_STATUS_HIS.DATE_TIME_STAMP
     *
     * @mbggenerated Wed Oct 23 16:06:25 CST 2013
     */
    public void setDateTimeStamp(Date dateTimeStamp) {
        this.dateTimeStamp = dateTimeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.MAIL_STATUS_HIS.COMPANYID
     *
     * @return the value of IAGENT.MAIL_STATUS_HIS.COMPANYID
     *
     * @mbggenerated Wed Oct 23 16:06:25 CST 2013
     */
    public String getCompanyid() {
        return companyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.MAIL_STATUS_HIS.COMPANYID
     *
     * @param companyid the value for IAGENT.MAIL_STATUS_HIS.COMPANYID
     *
     * @mbggenerated Wed Oct 23 16:06:25 CST 2013
     */
    public void setCompanyid(String companyid) {
        this.companyid = companyid == null ? null : companyid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.MAIL_STATUS_HIS.OPERATYPE
     *
     * @return the value of IAGENT.MAIL_STATUS_HIS.OPERATYPE
     *
     * @mbggenerated Wed Oct 23 16:06:25 CST 2013
     */
    public String getOperatype() {
        return operatype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.MAIL_STATUS_HIS.OPERATYPE
     *
     * @param operatype the value for IAGENT.MAIL_STATUS_HIS.OPERATYPE
     *
     * @mbggenerated Wed Oct 23 16:06:25 CST 2013
     */
    public void setOperatype(String operatype) {
        this.operatype = operatype == null ? null : operatype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.MAIL_STATUS_HIS.OPERADATE
     *
     * @return the value of IAGENT.MAIL_STATUS_HIS.OPERADATE
     *
     * @mbggenerated Wed Oct 23 16:06:25 CST 2013
     */
    public Date getOperadate() {
        return operadate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.MAIL_STATUS_HIS.OPERADATE
     *
     * @param operadate the value for IAGENT.MAIL_STATUS_HIS.OPERADATE
     *
     * @mbggenerated Wed Oct 23 16:06:25 CST 2013
     */
    public void setOperadate(Date operadate) {
        this.operadate = operadate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.MAIL_STATUS_HIS.STATION
     *
     * @return the value of IAGENT.MAIL_STATUS_HIS.STATION
     *
     * @mbggenerated Wed Oct 23 16:06:25 CST 2013
     */
    public String getStation() {
        return station;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.MAIL_STATUS_HIS.STATION
     *
     * @param station the value for IAGENT.MAIL_STATUS_HIS.STATION
     *
     * @mbggenerated Wed Oct 23 16:06:25 CST 2013
     */
    public void setStation(String station) {
        this.station = station == null ? null : station.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.MAIL_STATUS_HIS.OPTOR
     *
     * @return the value of IAGENT.MAIL_STATUS_HIS.OPTOR
     *
     * @mbggenerated Wed Oct 23 16:06:25 CST 2013
     */
    public String getOptor() {
        return optor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.MAIL_STATUS_HIS.OPTOR
     *
     * @param optor the value for IAGENT.MAIL_STATUS_HIS.OPTOR
     *
     * @mbggenerated Wed Oct 23 16:06:25 CST 2013
     */
    public void setOptor(String optor) {
        this.optor = optor == null ? null : optor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.MAIL_STATUS_HIS.REFUSEREASON
     *
     * @return the value of IAGENT.MAIL_STATUS_HIS.REFUSEREASON
     *
     * @mbggenerated Wed Oct 23 16:06:25 CST 2013
     */
    public String getRefusereason() {
        return refusereason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.MAIL_STATUS_HIS.REFUSEREASON
     *
     * @param refusereason the value for IAGENT.MAIL_STATUS_HIS.REFUSEREASON
     *
     * @mbggenerated Wed Oct 23 16:06:25 CST 2013
     */
    public void setRefusereason(String refusereason) {
        this.refusereason = refusereason == null ? null : refusereason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.MAIL_STATUS_HIS.PROBLEMREASON
     *
     * @return the value of IAGENT.MAIL_STATUS_HIS.PROBLEMREASON
     *
     * @mbggenerated Wed Oct 23 16:06:25 CST 2013
     */
    public String getProblemreason() {
        return problemreason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.MAIL_STATUS_HIS.PROBLEMREASON
     *
     * @param problemreason the value for IAGENT.MAIL_STATUS_HIS.PROBLEMREASON
     *
     * @mbggenerated Wed Oct 23 16:06:25 CST 2013
     */
    public void setProblemreason(String problemreason) {
        this.problemreason = problemreason == null ? null : problemreason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.MAIL_STATUS_HIS.REMARKS
     *
     * @return the value of IAGENT.MAIL_STATUS_HIS.REMARKS
     *
     * @mbggenerated Wed Oct 23 16:06:25 CST 2013
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.MAIL_STATUS_HIS.REMARKS
     *
     * @param remarks the value for IAGENT.MAIL_STATUS_HIS.REMARKS
     *
     * @mbggenerated Wed Oct 23 16:06:25 CST 2013
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

	
	public int bizHashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((companyid == null) ? 0 : companyid.hashCode());
		result = prime * result + ((mailid == null) ? 0 : mailid.hashCode());
		result = prime * result + ((operatype == null) ? 0 : operatype.hashCode());
		result = prime * result + ((optor == null) ? 0 : optor.hashCode());
		result = prime * result + ((problemreason == null) ? 0 : problemreason.hashCode());
		result = prime * result + ((reasonCode == null) ? 0 : reasonCode.hashCode());
		result = prime * result + ((refusereason == null) ? 0 : refusereason.hashCode());
		result = prime * result + ((remarks == null) ? 0 : remarks.hashCode());
		result = prime * result + ((shipmentId == null) ? 0 : shipmentId.hashCode());
		result = prime * result + ((signResult == null) ? 0 : signResult.hashCode());
		result = prime * result + ((station == null) ? 0 : station.hashCode());
		result = prime * result + ((statusCode == null) ? 0 : statusCode.hashCode());
		return result;
	}

	/** 
	 * <p>Title: equals</p>
	 * <p>Description: </p>
	 * @param obj
	 * @return
	 * @see java.lang.Object#equals(java.lang.Object)
	 */ 
	
	public boolean bizEquals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		MailStatusHis other = (MailStatusHis) obj;
		if (companyid == null) {
			if (other.companyid != null)
				return false;
		} else if (!companyid.equals(other.companyid))
			return false;
		if (mailid == null) {
			if (other.mailid != null)
				return false;
		} else if (!mailid.equals(other.mailid))
			return false;
		if (operatype == null) {
			if (other.operatype != null)
				return false;
		} else if (!operatype.equals(other.operatype))
			return false;
		if (optor == null) {
			if (other.optor != null)
				return false;
		} else if (!optor.equals(other.optor))
			return false;
		if (problemreason == null) {
			if (other.problemreason != null)
				return false;
		} else if (!problemreason.equals(other.problemreason))
			return false;
		if (reasonCode == null) {
			if (other.reasonCode != null)
				return false;
		} else if (!reasonCode.equals(other.reasonCode))
			return false;
		if (refusereason == null) {
			if (other.refusereason != null)
				return false;
		} else if (!refusereason.equals(other.refusereason))
			return false;
		if (remarks == null) {
			if (other.remarks != null)
				return false;
		} else if (!remarks.equals(other.remarks))
			return false;
		if (shipmentId == null) {
			if (other.shipmentId != null)
				return false;
		} else if (!shipmentId.equals(other.shipmentId))
			return false;
		if (signResult == null) {
			if (other.signResult != null)
				return false;
		} else if (!signResult.equals(other.signResult))
			return false;
		if (station == null) {
			if (other.station != null)
				return false;
		} else if (!station.equals(other.station))
			return false;
		if (statusCode == null) {
			if (other.statusCode != null)
				return false;
		} else if (!statusCode.equals(other.statusCode))
			return false;
		return true;
	}

	/** 
	 * <p>Title: toString</p>
	 * <p>Description: </p>
	 * @return
	 * @see java.lang.Object#toString()
	 */ 
	@Override
	public String toString() {
		return "MailStatusHis [recordId=" + recordId + ", shipmentId="
				+ shipmentId + ", mailid=" + mailid + ", statusCode="
				+ statusCode + ", reasonCode=" + reasonCode + ", signResult="
				+ signResult + ", emsDateTimeStamp=" + emsDateTimeStamp
				+ ", isProcessed=" + isProcessed + ", dateTimeStamp="
				+ dateTimeStamp + ", companyid=" + companyid + ", operatype="
				+ operatype + ", operadate=" + operadate + ", station="
				+ station + ", optor=" + optor + ", refusereason="
				+ refusereason + ", problemreason=" + problemreason
				+ ", remarks=" + remarks + "]";
	}
}