package com.chinadrtv.model.iagent;

import java.math.BigDecimal;
import java.util.Date;

public class PlubasInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.PLUBASINFO.RUID
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    private BigDecimal ruid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.PLUBASINFO.PLUCODE
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    private String plucode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.PLUBASINFO.PLUNAME
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    private String pluname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.PLUBASINFO.CATCODE
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    private String catcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.PLUBASINFO.BRANDCODE
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    private String brandcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.PLUBASINFO.SPEC
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    private String spec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.PLUBASINFO.PKUNIT
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    private String pkunit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.PLUBASINFO.PKQTY
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    private BigDecimal pkqty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.PLUBASINFO.PLUNATURE
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    private BigDecimal plunature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.PLUBASINFO.DEPGRPID
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    private BigDecimal depgrpid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.PLUBASINFO.MEMO
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.PLUBASINFO.SLPRC
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    private BigDecimal slprc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.PLUBASINFO.OUTTX
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    private BigDecimal outtx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.PLUBASINFO.HSLPRC
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    private BigDecimal hslprc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.PLUBASINFO.LSLPRC
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    private BigDecimal lslprc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.PLUBASINFO.VALID
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    private BigDecimal valid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.PLUBASINFO.VALIDPSN
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    private String validpsn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.PLUBASINFO.VALIDDAT
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    private Date validdat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.PLUBASINFO.COMCODE
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    private String comcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.PLUBASINFO.COMCONTCODE
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    private String comcontcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.PLUBASINFO.WHSLPRC
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    private BigDecimal whslprc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.PLUBASINFO.STATUS
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.PLUBASINFO.AVGCSPRC
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    private BigDecimal avgcsprc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.PLUBASINFO.STAMDAT
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    private Date stamdat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.PLUBASINFO.OBCD
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    private String obcd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.PLUBASINFO.ADDTX
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    private BigDecimal addtx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.PLUBASINFO.PRESENT
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    private BigDecimal present;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.PLUBASINFO.ISSUITEPLU
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    private String issuiteplu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.PLUBASINFO.SPELLCODE
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    private String spellcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.PLUBASINFO.CSRAT
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    private BigDecimal csrat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.PLUBASINFO.VIPRAT
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    private BigDecimal viprat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.PLUBASINFO.QDQTY
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    private BigDecimal qdqty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.PLUBASINFO.SMPREP
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    private String smprep;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.PLUBASINFO.VIPTYP
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    private BigDecimal viptyp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.PLUBASINFO.FARE
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    private BigDecimal fare;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.PLUBASINFO.NCCODE
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    private String nccode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.PLUBASINFO.CREDAT
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    private Date credat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.PLUBASINFO.CREPSN
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    private String crepsn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.PLUBASINFO.NCFREE
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    private String ncfree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.PLUBASINFO.MODIDAT
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    private Date modidat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.PLUBASINFO.PRLIID
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    private BigDecimal prliid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.PLUBASINFO.TICKET
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    private BigDecimal ticket;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.PLUBASINFO.SPELLNAME
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    private String spellname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.PLUBASINFO.DPTID
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    private BigDecimal dptid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.PLUBASINFO.ISSEND
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    private Short issend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.PLUBASINFO.NCFREENAME
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    private String ncfreename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.PLUBASINFO.ISSNDNC
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    private Short issndnc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.PLUBASINFO.ISTV
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    private Short istv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.PLUBASINFO.MODIPSN
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    private String modipsn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.PLUBASINFO.STDBOX
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    private Short stdbox;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.PLUBASINFO.CURCSPRC
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    private BigDecimal curcsprc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.PLUBASINFO.FAREXT
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    private BigDecimal farext;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.PLUBASINFO.NCFREESTATUS
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    private BigDecimal ncfreestatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.PLUBASINFO.HOSTEDPLU
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    private Short hostedplu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.PLUBASINFO.PRODSER
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    private String prodser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.PLUBASINFO.LAST_LOCK_SEQID
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    private BigDecimal lastLockSeqid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.PLUBASINFO.LAST_UPDATE_SEQID
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    private BigDecimal lastUpdateSeqid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.PLUBASINFO.LAST_UPDATE_TIME
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.PLUBASINFO.MAILPRICE
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    private BigDecimal mailprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.PLUBASINFO.SENDRAT
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    private BigDecimal sendrat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.PLUBASINFO.RUID
     *
     * @return the value of IAGENT.PLUBASINFO.RUID
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public BigDecimal getRuid() {
        return ruid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.PLUBASINFO.RUID
     *
     * @param ruid the value for IAGENT.PLUBASINFO.RUID
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public void setRuid(BigDecimal ruid) {
        this.ruid = ruid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.PLUBASINFO.PLUCODE
     *
     * @return the value of IAGENT.PLUBASINFO.PLUCODE
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public String getPlucode() {
        return plucode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.PLUBASINFO.PLUCODE
     *
     * @param plucode the value for IAGENT.PLUBASINFO.PLUCODE
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public void setPlucode(String plucode) {
        this.plucode = plucode == null ? null : plucode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.PLUBASINFO.PLUNAME
     *
     * @return the value of IAGENT.PLUBASINFO.PLUNAME
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public String getPluname() {
        return pluname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.PLUBASINFO.PLUNAME
     *
     * @param pluname the value for IAGENT.PLUBASINFO.PLUNAME
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public void setPluname(String pluname) {
        this.pluname = pluname == null ? null : pluname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.PLUBASINFO.CATCODE
     *
     * @return the value of IAGENT.PLUBASINFO.CATCODE
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public String getCatcode() {
        return catcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.PLUBASINFO.CATCODE
     *
     * @param catcode the value for IAGENT.PLUBASINFO.CATCODE
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public void setCatcode(String catcode) {
        this.catcode = catcode == null ? null : catcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.PLUBASINFO.BRANDCODE
     *
     * @return the value of IAGENT.PLUBASINFO.BRANDCODE
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public String getBrandcode() {
        return brandcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.PLUBASINFO.BRANDCODE
     *
     * @param brandcode the value for IAGENT.PLUBASINFO.BRANDCODE
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public void setBrandcode(String brandcode) {
        this.brandcode = brandcode == null ? null : brandcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.PLUBASINFO.SPEC
     *
     * @return the value of IAGENT.PLUBASINFO.SPEC
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public String getSpec() {
        return spec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.PLUBASINFO.SPEC
     *
     * @param spec the value for IAGENT.PLUBASINFO.SPEC
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public void setSpec(String spec) {
        this.spec = spec == null ? null : spec.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.PLUBASINFO.PKUNIT
     *
     * @return the value of IAGENT.PLUBASINFO.PKUNIT
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public String getPkunit() {
        return pkunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.PLUBASINFO.PKUNIT
     *
     * @param pkunit the value for IAGENT.PLUBASINFO.PKUNIT
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public void setPkunit(String pkunit) {
        this.pkunit = pkunit == null ? null : pkunit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.PLUBASINFO.PKQTY
     *
     * @return the value of IAGENT.PLUBASINFO.PKQTY
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public BigDecimal getPkqty() {
        return pkqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.PLUBASINFO.PKQTY
     *
     * @param pkqty the value for IAGENT.PLUBASINFO.PKQTY
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public void setPkqty(BigDecimal pkqty) {
        this.pkqty = pkqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.PLUBASINFO.PLUNATURE
     *
     * @return the value of IAGENT.PLUBASINFO.PLUNATURE
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public BigDecimal getPlunature() {
        return plunature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.PLUBASINFO.PLUNATURE
     *
     * @param plunature the value for IAGENT.PLUBASINFO.PLUNATURE
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public void setPlunature(BigDecimal plunature) {
        this.plunature = plunature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.PLUBASINFO.DEPGRPID
     *
     * @return the value of IAGENT.PLUBASINFO.DEPGRPID
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public BigDecimal getDepgrpid() {
        return depgrpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.PLUBASINFO.DEPGRPID
     *
     * @param depgrpid the value for IAGENT.PLUBASINFO.DEPGRPID
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public void setDepgrpid(BigDecimal depgrpid) {
        this.depgrpid = depgrpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.PLUBASINFO.MEMO
     *
     * @return the value of IAGENT.PLUBASINFO.MEMO
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.PLUBASINFO.MEMO
     *
     * @param memo the value for IAGENT.PLUBASINFO.MEMO
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.PLUBASINFO.SLPRC
     *
     * @return the value of IAGENT.PLUBASINFO.SLPRC
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public BigDecimal getSlprc() {
        return slprc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.PLUBASINFO.SLPRC
     *
     * @param slprc the value for IAGENT.PLUBASINFO.SLPRC
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public void setSlprc(BigDecimal slprc) {
        this.slprc = slprc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.PLUBASINFO.OUTTX
     *
     * @return the value of IAGENT.PLUBASINFO.OUTTX
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public BigDecimal getOuttx() {
        return outtx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.PLUBASINFO.OUTTX
     *
     * @param outtx the value for IAGENT.PLUBASINFO.OUTTX
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public void setOuttx(BigDecimal outtx) {
        this.outtx = outtx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.PLUBASINFO.HSLPRC
     *
     * @return the value of IAGENT.PLUBASINFO.HSLPRC
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public BigDecimal getHslprc() {
        return hslprc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.PLUBASINFO.HSLPRC
     *
     * @param hslprc the value for IAGENT.PLUBASINFO.HSLPRC
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public void setHslprc(BigDecimal hslprc) {
        this.hslprc = hslprc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.PLUBASINFO.LSLPRC
     *
     * @return the value of IAGENT.PLUBASINFO.LSLPRC
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public BigDecimal getLslprc() {
        return lslprc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.PLUBASINFO.LSLPRC
     *
     * @param lslprc the value for IAGENT.PLUBASINFO.LSLPRC
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public void setLslprc(BigDecimal lslprc) {
        this.lslprc = lslprc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.PLUBASINFO.VALID
     *
     * @return the value of IAGENT.PLUBASINFO.VALID
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public BigDecimal getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.PLUBASINFO.VALID
     *
     * @param valid the value for IAGENT.PLUBASINFO.VALID
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public void setValid(BigDecimal valid) {
        this.valid = valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.PLUBASINFO.VALIDPSN
     *
     * @return the value of IAGENT.PLUBASINFO.VALIDPSN
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public String getValidpsn() {
        return validpsn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.PLUBASINFO.VALIDPSN
     *
     * @param validpsn the value for IAGENT.PLUBASINFO.VALIDPSN
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public void setValidpsn(String validpsn) {
        this.validpsn = validpsn == null ? null : validpsn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.PLUBASINFO.VALIDDAT
     *
     * @return the value of IAGENT.PLUBASINFO.VALIDDAT
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public Date getValiddat() {
        return validdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.PLUBASINFO.VALIDDAT
     *
     * @param validdat the value for IAGENT.PLUBASINFO.VALIDDAT
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public void setValiddat(Date validdat) {
        this.validdat = validdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.PLUBASINFO.COMCODE
     *
     * @return the value of IAGENT.PLUBASINFO.COMCODE
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public String getComcode() {
        return comcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.PLUBASINFO.COMCODE
     *
     * @param comcode the value for IAGENT.PLUBASINFO.COMCODE
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public void setComcode(String comcode) {
        this.comcode = comcode == null ? null : comcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.PLUBASINFO.COMCONTCODE
     *
     * @return the value of IAGENT.PLUBASINFO.COMCONTCODE
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public String getComcontcode() {
        return comcontcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.PLUBASINFO.COMCONTCODE
     *
     * @param comcontcode the value for IAGENT.PLUBASINFO.COMCONTCODE
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public void setComcontcode(String comcontcode) {
        this.comcontcode = comcontcode == null ? null : comcontcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.PLUBASINFO.WHSLPRC
     *
     * @return the value of IAGENT.PLUBASINFO.WHSLPRC
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public BigDecimal getWhslprc() {
        return whslprc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.PLUBASINFO.WHSLPRC
     *
     * @param whslprc the value for IAGENT.PLUBASINFO.WHSLPRC
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public void setWhslprc(BigDecimal whslprc) {
        this.whslprc = whslprc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.PLUBASINFO.STATUS
     *
     * @return the value of IAGENT.PLUBASINFO.STATUS
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.PLUBASINFO.STATUS
     *
     * @param status the value for IAGENT.PLUBASINFO.STATUS
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.PLUBASINFO.AVGCSPRC
     *
     * @return the value of IAGENT.PLUBASINFO.AVGCSPRC
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public BigDecimal getAvgcsprc() {
        return avgcsprc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.PLUBASINFO.AVGCSPRC
     *
     * @param avgcsprc the value for IAGENT.PLUBASINFO.AVGCSPRC
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public void setAvgcsprc(BigDecimal avgcsprc) {
        this.avgcsprc = avgcsprc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.PLUBASINFO.STAMDAT
     *
     * @return the value of IAGENT.PLUBASINFO.STAMDAT
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public Date getStamdat() {
        return stamdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.PLUBASINFO.STAMDAT
     *
     * @param stamdat the value for IAGENT.PLUBASINFO.STAMDAT
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public void setStamdat(Date stamdat) {
        this.stamdat = stamdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.PLUBASINFO.OBCD
     *
     * @return the value of IAGENT.PLUBASINFO.OBCD
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public String getObcd() {
        return obcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.PLUBASINFO.OBCD
     *
     * @param obcd the value for IAGENT.PLUBASINFO.OBCD
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public void setObcd(String obcd) {
        this.obcd = obcd == null ? null : obcd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.PLUBASINFO.ADDTX
     *
     * @return the value of IAGENT.PLUBASINFO.ADDTX
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public BigDecimal getAddtx() {
        return addtx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.PLUBASINFO.ADDTX
     *
     * @param addtx the value for IAGENT.PLUBASINFO.ADDTX
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public void setAddtx(BigDecimal addtx) {
        this.addtx = addtx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.PLUBASINFO.PRESENT
     *
     * @return the value of IAGENT.PLUBASINFO.PRESENT
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public BigDecimal getPresent() {
        return present;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.PLUBASINFO.PRESENT
     *
     * @param present the value for IAGENT.PLUBASINFO.PRESENT
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public void setPresent(BigDecimal present) {
        this.present = present;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.PLUBASINFO.ISSUITEPLU
     *
     * @return the value of IAGENT.PLUBASINFO.ISSUITEPLU
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public String getIssuiteplu() {
        return issuiteplu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.PLUBASINFO.ISSUITEPLU
     *
     * @param issuiteplu the value for IAGENT.PLUBASINFO.ISSUITEPLU
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public void setIssuiteplu(String issuiteplu) {
        this.issuiteplu = issuiteplu == null ? null : issuiteplu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.PLUBASINFO.SPELLCODE
     *
     * @return the value of IAGENT.PLUBASINFO.SPELLCODE
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public String getSpellcode() {
        return spellcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.PLUBASINFO.SPELLCODE
     *
     * @param spellcode the value for IAGENT.PLUBASINFO.SPELLCODE
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public void setSpellcode(String spellcode) {
        this.spellcode = spellcode == null ? null : spellcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.PLUBASINFO.CSRAT
     *
     * @return the value of IAGENT.PLUBASINFO.CSRAT
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public BigDecimal getCsrat() {
        return csrat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.PLUBASINFO.CSRAT
     *
     * @param csrat the value for IAGENT.PLUBASINFO.CSRAT
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public void setCsrat(BigDecimal csrat) {
        this.csrat = csrat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.PLUBASINFO.VIPRAT
     *
     * @return the value of IAGENT.PLUBASINFO.VIPRAT
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public BigDecimal getViprat() {
        return viprat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.PLUBASINFO.VIPRAT
     *
     * @param viprat the value for IAGENT.PLUBASINFO.VIPRAT
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public void setViprat(BigDecimal viprat) {
        this.viprat = viprat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.PLUBASINFO.QDQTY
     *
     * @return the value of IAGENT.PLUBASINFO.QDQTY
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public BigDecimal getQdqty() {
        return qdqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.PLUBASINFO.QDQTY
     *
     * @param qdqty the value for IAGENT.PLUBASINFO.QDQTY
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public void setQdqty(BigDecimal qdqty) {
        this.qdqty = qdqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.PLUBASINFO.SMPREP
     *
     * @return the value of IAGENT.PLUBASINFO.SMPREP
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public String getSmprep() {
        return smprep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.PLUBASINFO.SMPREP
     *
     * @param smprep the value for IAGENT.PLUBASINFO.SMPREP
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public void setSmprep(String smprep) {
        this.smprep = smprep == null ? null : smprep.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.PLUBASINFO.VIPTYP
     *
     * @return the value of IAGENT.PLUBASINFO.VIPTYP
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public BigDecimal getViptyp() {
        return viptyp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.PLUBASINFO.VIPTYP
     *
     * @param viptyp the value for IAGENT.PLUBASINFO.VIPTYP
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public void setViptyp(BigDecimal viptyp) {
        this.viptyp = viptyp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.PLUBASINFO.FARE
     *
     * @return the value of IAGENT.PLUBASINFO.FARE
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public BigDecimal getFare() {
        return fare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.PLUBASINFO.FARE
     *
     * @param fare the value for IAGENT.PLUBASINFO.FARE
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public void setFare(BigDecimal fare) {
        this.fare = fare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.PLUBASINFO.NCCODE
     *
     * @return the value of IAGENT.PLUBASINFO.NCCODE
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public String getNccode() {
        return nccode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.PLUBASINFO.NCCODE
     *
     * @param nccode the value for IAGENT.PLUBASINFO.NCCODE
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public void setNccode(String nccode) {
        this.nccode = nccode == null ? null : nccode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.PLUBASINFO.CREDAT
     *
     * @return the value of IAGENT.PLUBASINFO.CREDAT
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public Date getCredat() {
        return credat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.PLUBASINFO.CREDAT
     *
     * @param credat the value for IAGENT.PLUBASINFO.CREDAT
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public void setCredat(Date credat) {
        this.credat = credat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.PLUBASINFO.CREPSN
     *
     * @return the value of IAGENT.PLUBASINFO.CREPSN
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public String getCrepsn() {
        return crepsn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.PLUBASINFO.CREPSN
     *
     * @param crepsn the value for IAGENT.PLUBASINFO.CREPSN
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public void setCrepsn(String crepsn) {
        this.crepsn = crepsn == null ? null : crepsn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.PLUBASINFO.NCFREE
     *
     * @return the value of IAGENT.PLUBASINFO.NCFREE
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public String getNcfree() {
        return ncfree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.PLUBASINFO.NCFREE
     *
     * @param ncfree the value for IAGENT.PLUBASINFO.NCFREE
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public void setNcfree(String ncfree) {
        this.ncfree = ncfree == null ? null : ncfree.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.PLUBASINFO.MODIDAT
     *
     * @return the value of IAGENT.PLUBASINFO.MODIDAT
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public Date getModidat() {
        return modidat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.PLUBASINFO.MODIDAT
     *
     * @param modidat the value for IAGENT.PLUBASINFO.MODIDAT
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public void setModidat(Date modidat) {
        this.modidat = modidat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.PLUBASINFO.PRLIID
     *
     * @return the value of IAGENT.PLUBASINFO.PRLIID
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public BigDecimal getPrliid() {
        return prliid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.PLUBASINFO.PRLIID
     *
     * @param prliid the value for IAGENT.PLUBASINFO.PRLIID
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public void setPrliid(BigDecimal prliid) {
        this.prliid = prliid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.PLUBASINFO.TICKET
     *
     * @return the value of IAGENT.PLUBASINFO.TICKET
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public BigDecimal getTicket() {
        return ticket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.PLUBASINFO.TICKET
     *
     * @param ticket the value for IAGENT.PLUBASINFO.TICKET
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public void setTicket(BigDecimal ticket) {
        this.ticket = ticket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.PLUBASINFO.SPELLNAME
     *
     * @return the value of IAGENT.PLUBASINFO.SPELLNAME
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public String getSpellname() {
        return spellname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.PLUBASINFO.SPELLNAME
     *
     * @param spellname the value for IAGENT.PLUBASINFO.SPELLNAME
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public void setSpellname(String spellname) {
        this.spellname = spellname == null ? null : spellname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.PLUBASINFO.DPTID
     *
     * @return the value of IAGENT.PLUBASINFO.DPTID
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public BigDecimal getDptid() {
        return dptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.PLUBASINFO.DPTID
     *
     * @param dptid the value for IAGENT.PLUBASINFO.DPTID
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public void setDptid(BigDecimal dptid) {
        this.dptid = dptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.PLUBASINFO.ISSEND
     *
     * @return the value of IAGENT.PLUBASINFO.ISSEND
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public Short getIssend() {
        return issend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.PLUBASINFO.ISSEND
     *
     * @param issend the value for IAGENT.PLUBASINFO.ISSEND
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public void setIssend(Short issend) {
        this.issend = issend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.PLUBASINFO.NCFREENAME
     *
     * @return the value of IAGENT.PLUBASINFO.NCFREENAME
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public String getNcfreename() {
        return ncfreename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.PLUBASINFO.NCFREENAME
     *
     * @param ncfreename the value for IAGENT.PLUBASINFO.NCFREENAME
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public void setNcfreename(String ncfreename) {
        this.ncfreename = ncfreename == null ? null : ncfreename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.PLUBASINFO.ISSNDNC
     *
     * @return the value of IAGENT.PLUBASINFO.ISSNDNC
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public Short getIssndnc() {
        return issndnc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.PLUBASINFO.ISSNDNC
     *
     * @param issndnc the value for IAGENT.PLUBASINFO.ISSNDNC
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public void setIssndnc(Short issndnc) {
        this.issndnc = issndnc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.PLUBASINFO.ISTV
     *
     * @return the value of IAGENT.PLUBASINFO.ISTV
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public Short getIstv() {
        return istv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.PLUBASINFO.ISTV
     *
     * @param istv the value for IAGENT.PLUBASINFO.ISTV
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public void setIstv(Short istv) {
        this.istv = istv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.PLUBASINFO.MODIPSN
     *
     * @return the value of IAGENT.PLUBASINFO.MODIPSN
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public String getModipsn() {
        return modipsn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.PLUBASINFO.MODIPSN
     *
     * @param modipsn the value for IAGENT.PLUBASINFO.MODIPSN
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public void setModipsn(String modipsn) {
        this.modipsn = modipsn == null ? null : modipsn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.PLUBASINFO.STDBOX
     *
     * @return the value of IAGENT.PLUBASINFO.STDBOX
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public Short getStdbox() {
        return stdbox;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.PLUBASINFO.STDBOX
     *
     * @param stdbox the value for IAGENT.PLUBASINFO.STDBOX
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public void setStdbox(Short stdbox) {
        this.stdbox = stdbox;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.PLUBASINFO.CURCSPRC
     *
     * @return the value of IAGENT.PLUBASINFO.CURCSPRC
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public BigDecimal getCurcsprc() {
        return curcsprc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.PLUBASINFO.CURCSPRC
     *
     * @param curcsprc the value for IAGENT.PLUBASINFO.CURCSPRC
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public void setCurcsprc(BigDecimal curcsprc) {
        this.curcsprc = curcsprc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.PLUBASINFO.FAREXT
     *
     * @return the value of IAGENT.PLUBASINFO.FAREXT
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public BigDecimal getFarext() {
        return farext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.PLUBASINFO.FAREXT
     *
     * @param farext the value for IAGENT.PLUBASINFO.FAREXT
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public void setFarext(BigDecimal farext) {
        this.farext = farext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.PLUBASINFO.NCFREESTATUS
     *
     * @return the value of IAGENT.PLUBASINFO.NCFREESTATUS
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public BigDecimal getNcfreestatus() {
        return ncfreestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.PLUBASINFO.NCFREESTATUS
     *
     * @param ncfreestatus the value for IAGENT.PLUBASINFO.NCFREESTATUS
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public void setNcfreestatus(BigDecimal ncfreestatus) {
        this.ncfreestatus = ncfreestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.PLUBASINFO.HOSTEDPLU
     *
     * @return the value of IAGENT.PLUBASINFO.HOSTEDPLU
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public Short getHostedplu() {
        return hostedplu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.PLUBASINFO.HOSTEDPLU
     *
     * @param hostedplu the value for IAGENT.PLUBASINFO.HOSTEDPLU
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public void setHostedplu(Short hostedplu) {
        this.hostedplu = hostedplu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.PLUBASINFO.PRODSER
     *
     * @return the value of IAGENT.PLUBASINFO.PRODSER
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public String getProdser() {
        return prodser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.PLUBASINFO.PRODSER
     *
     * @param prodser the value for IAGENT.PLUBASINFO.PRODSER
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public void setProdser(String prodser) {
        this.prodser = prodser == null ? null : prodser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.PLUBASINFO.LAST_LOCK_SEQID
     *
     * @return the value of IAGENT.PLUBASINFO.LAST_LOCK_SEQID
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public BigDecimal getLastLockSeqid() {
        return lastLockSeqid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.PLUBASINFO.LAST_LOCK_SEQID
     *
     * @param lastLockSeqid the value for IAGENT.PLUBASINFO.LAST_LOCK_SEQID
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public void setLastLockSeqid(BigDecimal lastLockSeqid) {
        this.lastLockSeqid = lastLockSeqid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.PLUBASINFO.LAST_UPDATE_SEQID
     *
     * @return the value of IAGENT.PLUBASINFO.LAST_UPDATE_SEQID
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public BigDecimal getLastUpdateSeqid() {
        return lastUpdateSeqid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.PLUBASINFO.LAST_UPDATE_SEQID
     *
     * @param lastUpdateSeqid the value for IAGENT.PLUBASINFO.LAST_UPDATE_SEQID
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public void setLastUpdateSeqid(BigDecimal lastUpdateSeqid) {
        this.lastUpdateSeqid = lastUpdateSeqid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.PLUBASINFO.LAST_UPDATE_TIME
     *
     * @return the value of IAGENT.PLUBASINFO.LAST_UPDATE_TIME
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.PLUBASINFO.LAST_UPDATE_TIME
     *
     * @param lastUpdateTime the value for IAGENT.PLUBASINFO.LAST_UPDATE_TIME
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.PLUBASINFO.MAILPRICE
     *
     * @return the value of IAGENT.PLUBASINFO.MAILPRICE
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public BigDecimal getMailprice() {
        return mailprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.PLUBASINFO.MAILPRICE
     *
     * @param mailprice the value for IAGENT.PLUBASINFO.MAILPRICE
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public void setMailprice(BigDecimal mailprice) {
        this.mailprice = mailprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.PLUBASINFO.SENDRAT
     *
     * @return the value of IAGENT.PLUBASINFO.SENDRAT
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public BigDecimal getSendrat() {
        return sendrat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.PLUBASINFO.SENDRAT
     *
     * @param sendrat the value for IAGENT.PLUBASINFO.SENDRAT
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public void setSendrat(BigDecimal sendrat) {
        this.sendrat = sendrat;
    }
}