package com.chinadrtv.model.iagent;

public class Province {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.PROVINCE.PROVINCEID
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    private String provinceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.PROVINCE.CODE
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.PROVINCE.CONTINENT
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    private String continent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.PROVINCE.ALLY1
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    private String ally1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.PROVINCE.ALLY2
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    private String ally2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.PROVINCE.ALLY3
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    private String ally3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.PROVINCE.CHINESE
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    private String chinese;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.PROVINCE.ENGLISH
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    private String english;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.PROVINCE.CAPITAL
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    private String capital;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IAGENT.PROVINCE.FEEZONE
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    private Integer feezone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.PROVINCE.PROVINCEID
     *
     * @return the value of IAGENT.PROVINCE.PROVINCEID
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    public String getProvinceid() {
        return provinceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.PROVINCE.PROVINCEID
     *
     * @param provinceid the value for IAGENT.PROVINCE.PROVINCEID
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    public void setProvinceid(String provinceid) {
        this.provinceid = provinceid == null ? null : provinceid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.PROVINCE.CODE
     *
     * @return the value of IAGENT.PROVINCE.CODE
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.PROVINCE.CODE
     *
     * @param code the value for IAGENT.PROVINCE.CODE
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.PROVINCE.CONTINENT
     *
     * @return the value of IAGENT.PROVINCE.CONTINENT
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    public String getContinent() {
        return continent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.PROVINCE.CONTINENT
     *
     * @param continent the value for IAGENT.PROVINCE.CONTINENT
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    public void setContinent(String continent) {
        this.continent = continent == null ? null : continent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.PROVINCE.ALLY1
     *
     * @return the value of IAGENT.PROVINCE.ALLY1
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    public String getAlly1() {
        return ally1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.PROVINCE.ALLY1
     *
     * @param ally1 the value for IAGENT.PROVINCE.ALLY1
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    public void setAlly1(String ally1) {
        this.ally1 = ally1 == null ? null : ally1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.PROVINCE.ALLY2
     *
     * @return the value of IAGENT.PROVINCE.ALLY2
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    public String getAlly2() {
        return ally2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.PROVINCE.ALLY2
     *
     * @param ally2 the value for IAGENT.PROVINCE.ALLY2
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    public void setAlly2(String ally2) {
        this.ally2 = ally2 == null ? null : ally2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.PROVINCE.ALLY3
     *
     * @return the value of IAGENT.PROVINCE.ALLY3
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    public String getAlly3() {
        return ally3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.PROVINCE.ALLY3
     *
     * @param ally3 the value for IAGENT.PROVINCE.ALLY3
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    public void setAlly3(String ally3) {
        this.ally3 = ally3 == null ? null : ally3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.PROVINCE.CHINESE
     *
     * @return the value of IAGENT.PROVINCE.CHINESE
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    public String getChinese() {
        return chinese;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.PROVINCE.CHINESE
     *
     * @param chinese the value for IAGENT.PROVINCE.CHINESE
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    public void setChinese(String chinese) {
        this.chinese = chinese == null ? null : chinese.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.PROVINCE.ENGLISH
     *
     * @return the value of IAGENT.PROVINCE.ENGLISH
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    public String getEnglish() {
        return english;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.PROVINCE.ENGLISH
     *
     * @param english the value for IAGENT.PROVINCE.ENGLISH
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    public void setEnglish(String english) {
        this.english = english == null ? null : english.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.PROVINCE.CAPITAL
     *
     * @return the value of IAGENT.PROVINCE.CAPITAL
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    public String getCapital() {
        return capital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.PROVINCE.CAPITAL
     *
     * @param capital the value for IAGENT.PROVINCE.CAPITAL
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    public void setCapital(String capital) {
        this.capital = capital == null ? null : capital.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IAGENT.PROVINCE.FEEZONE
     *
     * @return the value of IAGENT.PROVINCE.FEEZONE
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    public Integer getFeezone() {
        return feezone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IAGENT.PROVINCE.FEEZONE
     *
     * @param feezone the value for IAGENT.PROVINCE.FEEZONE
     *
     * @mbggenerated Wed Oct 30 14:51:04 CST 2013
     */
    public void setFeezone(Integer feezone) {
        this.feezone = feezone;
    }
}