package com.chinadrtv.postprice.dal.iagent.model;

import java.math.BigDecimal;

/**
 * Created with (TC).
 * User: 徐志凯
 * Date: 13-11-21
 * 橡果国际-系统集成部
 * Copyright (c) 2012-2013 ACORN, Inc. All rights reserved.
 */

public class LogisticsFeeRuleDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.ID
     *
     * @mbggenerated Fri Nov 22 10:02:17 CST 2013
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.LOGISTICS_FEE_RULE_ID
     *
     * @mbggenerated Fri Nov 22 10:02:17 CST 2013
     */
    private BigDecimal logisticsFeeRuleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.WAREHOUSE_ID
     *
     * @mbggenerated Fri Nov 22 10:02:17 CST 2013
     */
    private String warehouseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.RULE_TYPE
     *
     * @mbggenerated Fri Nov 22 10:02:17 CST 2013
     */
    private String ruleType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.AMOUNT_FLOOR
     *
     * @mbggenerated Fri Nov 22 10:02:17 CST 2013
     */
    private BigDecimal amountFloor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.AMOUNT_CEIL
     *
     * @mbggenerated Fri Nov 22 10:02:17 CST 2013
     */
    private BigDecimal amountCeil;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.SUCCEED_FEE_RATIO
     *
     * @mbggenerated Fri Nov 22 10:02:17 CST 2013
     */
    private BigDecimal succeedFeeRatio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.SUCCEED_FEE_AMOUNT
     *
     * @mbggenerated Fri Nov 22 10:02:17 CST 2013
     */
    private BigDecimal succeedFeeAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.REFUSED_FEE_RATIO
     *
     * @mbggenerated Fri Nov 22 10:02:17 CST 2013
     */
    private BigDecimal refusedFeeRatio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.REFUSED_FEE_AMOUNT
     *
     * @mbggenerated Fri Nov 22 10:02:17 CST 2013
     */
    private BigDecimal refusedFeeAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.VIRTUAL_FEE_AMOUNT
     *
     * @mbggenerated Fri Nov 22 10:02:17 CST 2013
     */
    private BigDecimal virtualFeeAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.DESTINATION_PROVINCE
     *
     * @mbggenerated Fri Nov 22 10:02:17 CST 2013
     */
    private String destinationProvince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.DESTINATION_CITY
     *
     * @mbggenerated Fri Nov 22 10:02:17 CST 2013
     */
    private String destinationCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.DESTINATION_COUNTY
     *
     * @mbggenerated Fri Nov 22 10:02:17 CST 2013
     */
    private String destinationCounty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.WEIGHT_FLOOR
     *
     * @mbggenerated Fri Nov 22 10:02:17 CST 2013
     */
    private BigDecimal weightFloor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.WEIGHT_CEIL
     *
     * @mbggenerated Fri Nov 22 10:02:17 CST 2013
     */
    private BigDecimal weightCeil;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.WEIGHT_INITIAL
     *
     * @mbggenerated Fri Nov 22 10:02:17 CST 2013
     */
    private BigDecimal weightInitial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.WEIGHT_INITIAL_FEE
     *
     * @mbggenerated Fri Nov 22 10:02:17 CST 2013
     */
    private BigDecimal weightInitialFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.WEIGHT_INCREASE
     *
     * @mbggenerated Fri Nov 22 10:02:17 CST 2013
     */
    private BigDecimal weightIncrease;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.WEIGHT_INCREASE_FEE
     *
     * @mbggenerated Fri Nov 22 10:02:17 CST 2013
     */
    private BigDecimal weightIncreaseFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.SPECIAL_FEE
     *
     * @mbggenerated Fri Nov 22 10:02:17 CST 2013
     */
    private BigDecimal specialFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.SIDE_LENGTH
     *
     * @mbggenerated Fri Nov 22 10:02:17 CST 2013
     */
    private BigDecimal sideLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.VOLUME_FEE_AMOUNT
     *
     * @mbggenerated Fri Nov 22 10:02:17 CST 2013
     */
    private BigDecimal volumeFeeAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.ROUND_TYPE
     *
     * @mbggenerated Fri Nov 22 10:02:17 CST 2013
     */
    private String roundType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.REFUSED_INCLUDE_POSTFEE
     *
     * @mbggenerated Fri Nov 22 10:02:17 CST 2013
     */
    private String refusedIncludePostfee;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.ID
     *
     * @return the value of ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.ID
     *
     * @mbggenerated Fri Nov 22 10:02:17 CST 2013
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.ID
     *
     * @param id the value for ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.ID
     *
     * @mbggenerated Fri Nov 22 10:02:17 CST 2013
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.LOGISTICS_FEE_RULE_ID
     *
     * @return the value of ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.LOGISTICS_FEE_RULE_ID
     *
     * @mbggenerated Fri Nov 22 10:02:17 CST 2013
     */
    public BigDecimal getLogisticsFeeRuleId() {
        return logisticsFeeRuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.LOGISTICS_FEE_RULE_ID
     *
     * @param logisticsFeeRuleId the value for ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.LOGISTICS_FEE_RULE_ID
     *
     * @mbggenerated Fri Nov 22 10:02:17 CST 2013
     */
    public void setLogisticsFeeRuleId(BigDecimal logisticsFeeRuleId) {
        this.logisticsFeeRuleId = logisticsFeeRuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.WAREHOUSE_ID
     *
     * @return the value of ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.WAREHOUSE_ID
     *
     * @mbggenerated Fri Nov 22 10:02:17 CST 2013
     */
    public String getWarehouseId() {
        return warehouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.WAREHOUSE_ID
     *
     * @param warehouseId the value for ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.WAREHOUSE_ID
     *
     * @mbggenerated Fri Nov 22 10:02:17 CST 2013
     */
    public void setWarehouseId(String warehouseId) {
        this.warehouseId = warehouseId == null ? null : warehouseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.RULE_TYPE
     *
     * @return the value of ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.RULE_TYPE
     *
     * @mbggenerated Fri Nov 22 10:02:17 CST 2013
     */
    public String getRuleType() {
        return ruleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.RULE_TYPE
     *
     * @param ruleType the value for ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.RULE_TYPE
     *
     * @mbggenerated Fri Nov 22 10:02:17 CST 2013
     */
    public void setRuleType(String ruleType) {
        this.ruleType = ruleType == null ? null : ruleType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.AMOUNT_FLOOR
     *
     * @return the value of ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.AMOUNT_FLOOR
     *
     * @mbggenerated Fri Nov 22 10:02:17 CST 2013
     */
    public BigDecimal getAmountFloor() {
        return amountFloor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.AMOUNT_FLOOR
     *
     * @param amountFloor the value for ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.AMOUNT_FLOOR
     *
     * @mbggenerated Fri Nov 22 10:02:17 CST 2013
     */
    public void setAmountFloor(BigDecimal amountFloor) {
        this.amountFloor = amountFloor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.AMOUNT_CEIL
     *
     * @return the value of ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.AMOUNT_CEIL
     *
     * @mbggenerated Fri Nov 22 10:02:17 CST 2013
     */
    public BigDecimal getAmountCeil() {
        return amountCeil;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.AMOUNT_CEIL
     *
     * @param amountCeil the value for ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.AMOUNT_CEIL
     *
     * @mbggenerated Fri Nov 22 10:02:17 CST 2013
     */
    public void setAmountCeil(BigDecimal amountCeil) {
        this.amountCeil = amountCeil;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.SUCCEED_FEE_RATIO
     *
     * @return the value of ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.SUCCEED_FEE_RATIO
     *
     * @mbggenerated Fri Nov 22 10:02:17 CST 2013
     */
    public BigDecimal getSucceedFeeRatio() {
        return succeedFeeRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.SUCCEED_FEE_RATIO
     *
     * @param succeedFeeRatio the value for ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.SUCCEED_FEE_RATIO
     *
     * @mbggenerated Fri Nov 22 10:02:17 CST 2013
     */
    public void setSucceedFeeRatio(BigDecimal succeedFeeRatio) {
        this.succeedFeeRatio = succeedFeeRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.SUCCEED_FEE_AMOUNT
     *
     * @return the value of ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.SUCCEED_FEE_AMOUNT
     *
     * @mbggenerated Fri Nov 22 10:02:17 CST 2013
     */
    public BigDecimal getSucceedFeeAmount() {
        return succeedFeeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.SUCCEED_FEE_AMOUNT
     *
     * @param succeedFeeAmount the value for ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.SUCCEED_FEE_AMOUNT
     *
     * @mbggenerated Fri Nov 22 10:02:17 CST 2013
     */
    public void setSucceedFeeAmount(BigDecimal succeedFeeAmount) {
        this.succeedFeeAmount = succeedFeeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.REFUSED_FEE_RATIO
     *
     * @return the value of ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.REFUSED_FEE_RATIO
     *
     * @mbggenerated Fri Nov 22 10:02:17 CST 2013
     */
    public BigDecimal getRefusedFeeRatio() {
        return refusedFeeRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.REFUSED_FEE_RATIO
     *
     * @param refusedFeeRatio the value for ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.REFUSED_FEE_RATIO
     *
     * @mbggenerated Fri Nov 22 10:02:17 CST 2013
     */
    public void setRefusedFeeRatio(BigDecimal refusedFeeRatio) {
        this.refusedFeeRatio = refusedFeeRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.REFUSED_FEE_AMOUNT
     *
     * @return the value of ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.REFUSED_FEE_AMOUNT
     *
     * @mbggenerated Fri Nov 22 10:02:17 CST 2013
     */
    public BigDecimal getRefusedFeeAmount() {
        return refusedFeeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.REFUSED_FEE_AMOUNT
     *
     * @param refusedFeeAmount the value for ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.REFUSED_FEE_AMOUNT
     *
     * @mbggenerated Fri Nov 22 10:02:17 CST 2013
     */
    public void setRefusedFeeAmount(BigDecimal refusedFeeAmount) {
        this.refusedFeeAmount = refusedFeeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.VIRTUAL_FEE_AMOUNT
     *
     * @return the value of ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.VIRTUAL_FEE_AMOUNT
     *
     * @mbggenerated Fri Nov 22 10:02:17 CST 2013
     */
    public BigDecimal getVirtualFeeAmount() {
        return virtualFeeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.VIRTUAL_FEE_AMOUNT
     *
     * @param virtualFeeAmount the value for ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.VIRTUAL_FEE_AMOUNT
     *
     * @mbggenerated Fri Nov 22 10:02:17 CST 2013
     */
    public void setVirtualFeeAmount(BigDecimal virtualFeeAmount) {
        this.virtualFeeAmount = virtualFeeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.DESTINATION_PROVINCE
     *
     * @return the value of ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.DESTINATION_PROVINCE
     *
     * @mbggenerated Fri Nov 22 10:02:17 CST 2013
     */
    public String getDestinationProvince() {
        return destinationProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.DESTINATION_PROVINCE
     *
     * @param destinationProvince the value for ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.DESTINATION_PROVINCE
     *
     * @mbggenerated Fri Nov 22 10:02:17 CST 2013
     */
    public void setDestinationProvince(String destinationProvince) {
        this.destinationProvince = destinationProvince == null ? null : destinationProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.DESTINATION_CITY
     *
     * @return the value of ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.DESTINATION_CITY
     *
     * @mbggenerated Fri Nov 22 10:02:17 CST 2013
     */
    public String getDestinationCity() {
        return destinationCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.DESTINATION_CITY
     *
     * @param destinationCity the value for ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.DESTINATION_CITY
     *
     * @mbggenerated Fri Nov 22 10:02:17 CST 2013
     */
    public void setDestinationCity(String destinationCity) {
        this.destinationCity = destinationCity == null ? null : destinationCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.DESTINATION_COUNTY
     *
     * @return the value of ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.DESTINATION_COUNTY
     *
     * @mbggenerated Fri Nov 22 10:02:17 CST 2013
     */
    public String getDestinationCounty() {
        return destinationCounty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.DESTINATION_COUNTY
     *
     * @param destinationCounty the value for ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.DESTINATION_COUNTY
     *
     * @mbggenerated Fri Nov 22 10:02:17 CST 2013
     */
    public void setDestinationCounty(String destinationCounty) {
        this.destinationCounty = destinationCounty == null ? null : destinationCounty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.WEIGHT_FLOOR
     *
     * @return the value of ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.WEIGHT_FLOOR
     *
     * @mbggenerated Fri Nov 22 10:02:17 CST 2013
     */
    public BigDecimal getWeightFloor() {
        return weightFloor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.WEIGHT_FLOOR
     *
     * @param weightFloor the value for ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.WEIGHT_FLOOR
     *
     * @mbggenerated Fri Nov 22 10:02:17 CST 2013
     */
    public void setWeightFloor(BigDecimal weightFloor) {
        this.weightFloor = weightFloor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.WEIGHT_CEIL
     *
     * @return the value of ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.WEIGHT_CEIL
     *
     * @mbggenerated Fri Nov 22 10:02:17 CST 2013
     */
    public BigDecimal getWeightCeil() {
        return weightCeil;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.WEIGHT_CEIL
     *
     * @param weightCeil the value for ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.WEIGHT_CEIL
     *
     * @mbggenerated Fri Nov 22 10:02:17 CST 2013
     */
    public void setWeightCeil(BigDecimal weightCeil) {
        this.weightCeil = weightCeil;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.WEIGHT_INITIAL
     *
     * @return the value of ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.WEIGHT_INITIAL
     *
     * @mbggenerated Fri Nov 22 10:02:17 CST 2013
     */
    public BigDecimal getWeightInitial() {
        return weightInitial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.WEIGHT_INITIAL
     *
     * @param weightInitial the value for ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.WEIGHT_INITIAL
     *
     * @mbggenerated Fri Nov 22 10:02:17 CST 2013
     */
    public void setWeightInitial(BigDecimal weightInitial) {
        this.weightInitial = weightInitial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.WEIGHT_INITIAL_FEE
     *
     * @return the value of ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.WEIGHT_INITIAL_FEE
     *
     * @mbggenerated Fri Nov 22 10:02:17 CST 2013
     */
    public BigDecimal getWeightInitialFee() {
        return weightInitialFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.WEIGHT_INITIAL_FEE
     *
     * @param weightInitialFee the value for ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.WEIGHT_INITIAL_FEE
     *
     * @mbggenerated Fri Nov 22 10:02:17 CST 2013
     */
    public void setWeightInitialFee(BigDecimal weightInitialFee) {
        this.weightInitialFee = weightInitialFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.WEIGHT_INCREASE
     *
     * @return the value of ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.WEIGHT_INCREASE
     *
     * @mbggenerated Fri Nov 22 10:02:17 CST 2013
     */
    public BigDecimal getWeightIncrease() {
        return weightIncrease;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.WEIGHT_INCREASE
     *
     * @param weightIncrease the value for ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.WEIGHT_INCREASE
     *
     * @mbggenerated Fri Nov 22 10:02:17 CST 2013
     */
    public void setWeightIncrease(BigDecimal weightIncrease) {
        this.weightIncrease = weightIncrease;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.WEIGHT_INCREASE_FEE
     *
     * @return the value of ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.WEIGHT_INCREASE_FEE
     *
     * @mbggenerated Fri Nov 22 10:02:17 CST 2013
     */
    public BigDecimal getWeightIncreaseFee() {
        return weightIncreaseFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.WEIGHT_INCREASE_FEE
     *
     * @param weightIncreaseFee the value for ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.WEIGHT_INCREASE_FEE
     *
     * @mbggenerated Fri Nov 22 10:02:17 CST 2013
     */
    public void setWeightIncreaseFee(BigDecimal weightIncreaseFee) {
        this.weightIncreaseFee = weightIncreaseFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.SPECIAL_FEE
     *
     * @return the value of ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.SPECIAL_FEE
     *
     * @mbggenerated Fri Nov 22 10:02:17 CST 2013
     */
    public BigDecimal getSpecialFee() {
        return specialFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.SPECIAL_FEE
     *
     * @param specialFee the value for ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.SPECIAL_FEE
     *
     * @mbggenerated Fri Nov 22 10:02:17 CST 2013
     */
    public void setSpecialFee(BigDecimal specialFee) {
        this.specialFee = specialFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.SIDE_LENGTH
     *
     * @return the value of ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.SIDE_LENGTH
     *
     * @mbggenerated Fri Nov 22 10:02:17 CST 2013
     */
    public BigDecimal getSideLength() {
        return sideLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.SIDE_LENGTH
     *
     * @param sideLength the value for ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.SIDE_LENGTH
     *
     * @mbggenerated Fri Nov 22 10:02:17 CST 2013
     */
    public void setSideLength(BigDecimal sideLength) {
        this.sideLength = sideLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.VOLUME_FEE_AMOUNT
     *
     * @return the value of ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.VOLUME_FEE_AMOUNT
     *
     * @mbggenerated Fri Nov 22 10:02:17 CST 2013
     */
    public BigDecimal getVolumeFeeAmount() {
        return volumeFeeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.VOLUME_FEE_AMOUNT
     *
     * @param volumeFeeAmount the value for ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.VOLUME_FEE_AMOUNT
     *
     * @mbggenerated Fri Nov 22 10:02:17 CST 2013
     */
    public void setVolumeFeeAmount(BigDecimal volumeFeeAmount) {
        this.volumeFeeAmount = volumeFeeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.ROUND_TYPE
     *
     * @return the value of ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.ROUND_TYPE
     *
     * @mbggenerated Fri Nov 22 10:02:17 CST 2013
     */
    public String getRoundType() {
        return roundType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.ROUND_TYPE
     *
     * @param roundType the value for ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.ROUND_TYPE
     *
     * @mbggenerated Fri Nov 22 10:02:17 CST 2013
     */
    public void setRoundType(String roundType) {
        this.roundType = roundType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.REFUSED_INCLUDE_POSTFEE
     *
     * @return the value of ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.REFUSED_INCLUDE_POSTFEE
     *
     * @mbggenerated Fri Nov 22 10:02:17 CST 2013
     */
    public String getRefusedIncludePostfee() {
        return refusedIncludePostfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.REFUSED_INCLUDE_POSTFEE
     *
     * @param refusedIncludePostfee the value for ACOAPP_OMS.LOGISTICS_FEE_RULE_DETAIL.REFUSED_INCLUDE_POSTFEE
     *
     * @mbggenerated Fri Nov 22 10:02:17 CST 2013
     */
    public void setRefusedIncludePostfee(String refusedIncludePostfee) {
        this.refusedIncludePostfee = refusedIncludePostfee;
    }
}
