
package com.chinadrtv.erp.pay.core.merchants.service;

import com.chinadrtv.erp.pay.core.merchants.model.Response;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "OnlineAuthorization", targetNamespace = "http://oaas.creditcard.cmbchina.com")
/*@XmlSeeAlso({
    com.cmbchina.creditcard.oaas.beans.ObjectFactory.class,
    com.cmbchina.creditcard.oaas.ObjectFactory.class
}) */
public interface OnlineAuthorization {


    /**
     * 
     * @param merchantNo
     * @param password
     * @return
     *     returns com.chinadrtv.erp.sales.core.Merchants.model.Response
     */
    @WebMethod
    @WebResult(name = "loginReturn", targetNamespace = "http://oaas.creditcard.cmbchina.com")
    //@RequestWrapper(localName = "login", targetNamespace = "http://oaas.creditcard.cmbchina.com", className = "com.cmbchina.creditcard.oaas.Login")
    //@ResponseWrapper(localName = "loginResponse", targetNamespace = "http://oaas.creditcard.cmbchina.com", className = "com.cmbchina.creditcard.oaas.LoginResponse")
    public Response login(
            @WebParam(name = "MerchantNo", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String merchantNo,
            @WebParam(name = "Password", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String password);

    /**
     * 
     * @param preTraceNum
     * @param expiryDate
     * @param batchNum
     * @param traceNum
     * @param orderNum
     * @param preTransTime
     * @param stageNum
     * @param cardNo
     * @param amount
     * @param token
     * @param preBatchNum
     * @param preRefNum
     * @param preAuthID
     * @return
     *     returns com.chinadrtv.erp.sales.core.Merchants.model.Response
     */
    @WebMethod
    @WebResult(name = "hirePurchaseReturnReturn", targetNamespace = "http://oaas.creditcard.cmbchina.com")
    //@RequestWrapper(localName = "hirePurchaseReturn", targetNamespace = "http://oaas.creditcard.cmbchina.com", className = "com.cmbchina.creditcard.oaas.HirePurchaseReturn")
    //@ResponseWrapper(localName = "hirePurchaseReturnResponse", targetNamespace = "http://oaas.creditcard.cmbchina.com", className = "com.cmbchina.creditcard.oaas.HirePurchaseReturnResponse")
    public Response hirePurchaseReturn(
            @WebParam(name = "Token", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String token,
            @WebParam(name = "BatchNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String batchNum,
            @WebParam(name = "CardNo", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String cardNo,
            @WebParam(name = "ExpiryDate", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String expiryDate,
            @WebParam(name = "TraceNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            int traceNum,
            @WebParam(name = "Amount", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String amount,
            @WebParam(name = "PreBatchNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String preBatchNum,
            @WebParam(name = "PreTransTime", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String preTransTime,
            @WebParam(name = "PreTraceNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            int preTraceNum,
            @WebParam(name = "PreRefNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String preRefNum,
            @WebParam(name = "PreAuthID", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String preAuthID,
            @WebParam(name = "StageNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            int stageNum,
            @WebParam(name = "OrderNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String orderNum);

    /**
     * 
     * @param cardNo
     * @param preTraceNum
     * @param preAmount
     * @param token
     * @param expiryDate
     * @param preBatchNum
     * @param preRefNum
     * @param traceNum
     * @param batchNum
     * @param preAuthID
     * @param preTransTime
     * @return
     *     returns com.chinadrtv.erp.sales.core.Merchants.model.Response
     */
    @WebMethod
    @WebResult(name = "purchaseReturnCancelReturn", targetNamespace = "http://oaas.creditcard.cmbchina.com")
    //@RequestWrapper(localName = "purchaseReturnCancel", targetNamespace = "http://oaas.creditcard.cmbchina.com", className = "com.cmbchina.creditcard.oaas.PurchaseReturnCancel")
    //@ResponseWrapper(localName = "purchaseReturnCancelResponse", targetNamespace = "http://oaas.creditcard.cmbchina.com", className = "com.cmbchina.creditcard.oaas.PurchaseReturnCancelResponse")
    public Response purchaseReturnCancel(
            @WebParam(name = "Token", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String token,
            @WebParam(name = "BatchNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String batchNum,
            @WebParam(name = "CardNo", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String cardNo,
            @WebParam(name = "ExpiryDate", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String expiryDate,
            @WebParam(name = "TraceNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            int traceNum,
            @WebParam(name = "PreAmount", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String preAmount,
            @WebParam(name = "PreBatchNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String preBatchNum,
            @WebParam(name = "PreTransTime", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String preTransTime,
            @WebParam(name = "PreTraceNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            int preTraceNum,
            @WebParam(name = "PreRefNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String preRefNum,
            @WebParam(name = "PreAuthID", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String preAuthID);

    /**
     * 
     * @param cardNo
     * @param preAmount
     * @param preTraceNum
     * @param token
     * @param expiryDate
     * @param preBatchNum
     * @param traceNum
     * @param batchNum
     * @param preAuthID
     * @param operType
     * @param preTransTime
     * @return
     *     returns com.chinadrtv.erp.sales.core.Merchants.model.Response
     */
    @WebMethod
    @WebResult(name = "preAuthOperRevReturn", targetNamespace = "http://oaas.creditcard.cmbchina.com")
    //@RequestWrapper(localName = "preAuthOperRev", targetNamespace = "http://oaas.creditcard.cmbchina.com", className = "com.cmbchina.creditcard.oaas.PreAuthOperRev")
    //@ResponseWrapper(localName = "preAuthOperRevResponse", targetNamespace = "http://oaas.creditcard.cmbchina.com", className = "com.cmbchina.creditcard.oaas.PreAuthOperRevResponse")
    public Response preAuthOperRev(
            @WebParam(name = "Token", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String token,
            @WebParam(name = "BatchNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String batchNum,
            @WebParam(name = "CardNo", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String cardNo,
            @WebParam(name = "ExpiryDate", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String expiryDate,
            @WebParam(name = "TraceNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            int traceNum,
            @WebParam(name = "PreBatchNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String preBatchNum,
            @WebParam(name = "PreTransTime", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String preTransTime,
            @WebParam(name = "PreTraceNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            int preTraceNum,
            @WebParam(name = "PreAmount", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String preAmount,
            @WebParam(name = "PreAuthID", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String preAuthID,
            @WebParam(name = "OperType", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String operType);

    /**
     * 
     * @param recordCount
     * @param fileDate
     * @param fileType
     * @param token
     * @param fileLength
     * @return
     *     returns com.chinadrtv.erp.sales.core.Merchants.model.Response
     */
    @WebMethod
    @WebResult(name = "uploadFileReturn", targetNamespace = "http://oaas.creditcard.cmbchina.com")
    //@RequestWrapper(localName = "uploadFile", targetNamespace = "http://oaas.creditcard.cmbchina.com", className = "com.cmbchina.creditcard.oaas.UploadFile")
    //@ResponseWrapper(localName = "uploadFileResponse", targetNamespace = "http://oaas.creditcard.cmbchina.com", className = "com.cmbchina.creditcard.oaas.UploadFileResponse")
    public Response uploadFile(
            @WebParam(name = "Token", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String token,
            @WebParam(name = "FileType", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String fileType,
            @WebParam(name = "FileDate", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String fileDate,
            @WebParam(name = "FileLength", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            int fileLength,
            @WebParam(name = "RecordCount", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            int recordCount);

    /**
     * 
     * @param amount
     * @param cardNo
     * @param token
     * @param expiryDate
     * @param traceNum
     * @param batchNum
     * @return
     *     returns com.chinadrtv.erp.sales.core.Merchants.model.Response
     */
    @WebMethod
    @WebResult(name = "preAuthReturn", targetNamespace = "http://oaas.creditcard.cmbchina.com")
    //@RequestWrapper(localName = "preAuth", targetNamespace = "http://oaas.creditcard.cmbchina.com", className = "com.cmbchina.creditcard.oaas.PreAuth")
    //@ResponseWrapper(localName = "preAuthResponse", targetNamespace = "http://oaas.creditcard.cmbchina.com", className = "com.cmbchina.creditcard.oaas.PreAuthResponse")
    public Response preAuth(
            @WebParam(name = "Token", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String token,
            @WebParam(name = "BatchNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String batchNum,
            @WebParam(name = "CardNo", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String cardNo,
            @WebParam(name = "ExpiryDate", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String expiryDate,
            @WebParam(name = "TraceNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            int traceNum,
            @WebParam(name = "Amount", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String amount);

    /**
     * 
     * @param preTraceNum
     * @param expiryDate
     * @param batchNum
     * @param traceNum
     * @param orderNum
     * @param bonusAmount
     * @param preTransTime
     * @param stageNum
     * @param cardNo
     * @param amount
     * @param token
     * @param inputType
     * @param preBatchNum
     * @param preRefNum
     * @param preAuthID
     * @return
     *     returns com.chinadrtv.erp.sales.core.Merchants.model.Response
     */
    @WebMethod
    @WebResult(name = "bonusTransReturnReturn", targetNamespace = "http://oaas.creditcard.cmbchina.com")
    //@RequestWrapper(localName = "bonusTransReturn", targetNamespace = "http://oaas.creditcard.cmbchina.com", className = "com.cmbchina.creditcard.oaas.BonusTransReturn")
    //@ResponseWrapper(localName = "bonusTransReturnResponse", targetNamespace = "http://oaas.creditcard.cmbchina.com", className = "com.cmbchina.creditcard.oaas.BonusTransReturnResponse")
    public Response bonusTransReturn(
            @WebParam(name = "Token", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String token,
            @WebParam(name = "BatchNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String batchNum,
            @WebParam(name = "CardNo", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String cardNo,
            @WebParam(name = "ExpiryDate", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String expiryDate,
            @WebParam(name = "TraceNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            int traceNum,
            @WebParam(name = "Amount", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String amount,
            @WebParam(name = "PreBatchNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String preBatchNum,
            @WebParam(name = "PreTransTime", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String preTransTime,
            @WebParam(name = "PreTraceNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            int preTraceNum,
            @WebParam(name = "PreRefNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String preRefNum,
            @WebParam(name = "PreAuthID", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String preAuthID,
            @WebParam(name = "StageNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            int stageNum,
            @WebParam(name = "OrderNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String orderNum,
            @WebParam(name = "InputType", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String inputType,
            @WebParam(name = "BonusAmount", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            int bonusAmount);

    /**
     * 
     * @param preTraceNum
     * @param preAmount
     * @param expiryDate
     * @param batchNum
     * @param traceNum
     * @param orderNum
     * @param bonusAmount
     * @param preTransTime
     * @param stageNum
     * @param cardNo
     * @param token
     * @param inputType
     * @param preBatchNum
     * @param preRefNum
     * @param preAuthID
     * @return
     *     returns com.chinadrtv.erp.sales.core.Merchants.model.Response
     */
    @WebMethod
    @WebResult(name = "bonusTransCancelReturn", targetNamespace = "http://oaas.creditcard.cmbchina.com")
    //@RequestWrapper(localName = "bonusTransCancel", targetNamespace = "http://oaas.creditcard.cmbchina.com", className = "com.cmbchina.creditcard.oaas.BonusTransCancel")
    //@ResponseWrapper(localName = "bonusTransCancelResponse", targetNamespace = "http://oaas.creditcard.cmbchina.com", className = "com.cmbchina.creditcard.oaas.BonusTransCancelResponse")
    public Response bonusTransCancel(
            @WebParam(name = "Token", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String token,
            @WebParam(name = "BatchNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String batchNum,
            @WebParam(name = "CardNo", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String cardNo,
            @WebParam(name = "ExpiryDate", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String expiryDate,
            @WebParam(name = "TraceNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            int traceNum,
            @WebParam(name = "PreBatchNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String preBatchNum,
            @WebParam(name = "PreTransTime", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String preTransTime,
            @WebParam(name = "PreTraceNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            int preTraceNum,
            @WebParam(name = "PreRefNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String preRefNum,
            @WebParam(name = "PreAmount", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String preAmount,
            @WebParam(name = "PreAuthID", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String preAuthID,
            @WebParam(name = "StageNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            int stageNum,
            @WebParam(name = "OrderNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String orderNum,
            @WebParam(name = "InputType", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String inputType,
            @WebParam(name = "BonusAmount", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            int bonusAmount);

    /**
     * 
     * @param token
     * @return
     *     returns com.chinadrtv.erp.sales.core.Merchants.model.Response
     */
    @WebMethod
    @WebResult(name = "logoutReturn", targetNamespace = "http://oaas.creditcard.cmbchina.com")
    //@RequestWrapper(localName = "logout", targetNamespace = "http://oaas.creditcard.cmbchina.com", className = "com.cmbchina.creditcard.oaas.Logout")
    //@ResponseWrapper(localName = "logoutResponse", targetNamespace = "http://oaas.creditcard.cmbchina.com", className = "com.cmbchina.creditcard.oaas.LogoutResponse")
    public Response logout(
            @WebParam(name = "Token", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String token);

    /**
     * 
     * @param amount
     * @param cardNo
     * @param preTraceNum
     * @param token
     * @param expiryDate
     * @param preBatchNum
     * @param preRefNum
     * @param traceNum
     * @param batchNum
     * @param preAuthID
     * @param operType
     * @param preTransTime
     * @return
     *     returns com.chinadrtv.erp.sales.core.Merchants.model.Response
     */
    @WebMethod
    @WebResult(name = "preAuthOperReturn", targetNamespace = "http://oaas.creditcard.cmbchina.com")
    //@RequestWrapper(localName = "preAuthOper", targetNamespace = "http://oaas.creditcard.cmbchina.com", className = "com.cmbchina.creditcard.oaas.PreAuthOper")
    //@ResponseWrapper(localName = "preAuthOperResponse", targetNamespace = "http://oaas.creditcard.cmbchina.com", className = "com.cmbchina.creditcard.oaas.PreAuthOperResponse")
    public Response preAuthOper(
            @WebParam(name = "Token", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String token,
            @WebParam(name = "BatchNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String batchNum,
            @WebParam(name = "CardNo", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String cardNo,
            @WebParam(name = "ExpiryDate", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String expiryDate,
            @WebParam(name = "TraceNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            int traceNum,
            @WebParam(name = "Amount", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String amount,
            @WebParam(name = "PreBatchNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String preBatchNum,
            @WebParam(name = "PreTransTime", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String preTransTime,
            @WebParam(name = "PreTraceNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            int preTraceNum,
            @WebParam(name = "PreRefNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String preRefNum,
            @WebParam(name = "PreAuthID", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String preAuthID,
            @WebParam(name = "OperType", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String operType);

    /**
     * 
     * @param fileDate
     * @param fileType
     * @param token
     * @return
     *     returns com.chinadrtv.erp.sales.core.Merchants.model.Response
     */
    @WebMethod
    @WebResult(name = "downloadFileReturn", targetNamespace = "http://oaas.creditcard.cmbchina.com")
    //@RequestWrapper(localName = "downloadFile", targetNamespace = "http://oaas.creditcard.cmbchina.com", className = "com.cmbchina.creditcard.oaas.DownloadFile")
    //@ResponseWrapper(localName = "downloadFileResponse", targetNamespace = "http://oaas.creditcard.cmbchina.com", className = "com.cmbchina.creditcard.oaas.DownloadFileResponse")
    public Response downloadFile(
            @WebParam(name = "Token", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String token,
            @WebParam(name = "FileType", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String fileType,
            @WebParam(name = "FileDate", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String fileDate);

    /**
     * 
     * @param cardNo
     * @param preAmount
     * @param preTraceNum
     * @param token
     * @param expiryDate
     * @param preBatchNum
     * @param traceNum
     * @param batchNum
     * @param preTransTime
     * @return
     *     returns com.chinadrtv.erp.sales.core.Merchants.model.Response
     */
    @WebMethod
    @WebResult(name = "preAuthRevReturn", targetNamespace = "http://oaas.creditcard.cmbchina.com")
    //@RequestWrapper(localName = "preAuthRev", targetNamespace = "http://oaas.creditcard.cmbchina.com", className = "com.cmbchina.creditcard.oaas.PreAuthRev")
    //@ResponseWrapper(localName = "preAuthRevResponse", targetNamespace = "http://oaas.creditcard.cmbchina.com", className = "com.cmbchina.creditcard.oaas.PreAuthRevResponse")
    public Response preAuthRev(
            @WebParam(name = "Token", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String token,
            @WebParam(name = "BatchNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String batchNum,
            @WebParam(name = "CardNo", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String cardNo,
            @WebParam(name = "ExpiryDate", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String expiryDate,
            @WebParam(name = "TraceNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            int traceNum,
            @WebParam(name = "PreBatchNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String preBatchNum,
            @WebParam(name = "PreTransTime", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String preTransTime,
            @WebParam(name = "PreTraceNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            int preTraceNum,
            @WebParam(name = "PreAmount", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String preAmount);

    /**
     * 
     * @param amount
     * @param cardNo
     * @param token
     * @param expiryDate
     * @param inputType
     * @param traceNum
     * @param batchNum
     * @param bonusAmount
     * @param stageNum
     * @return
     *     returns com.chinadrtv.erp.sales.core.Merchants.model.Response
     */
    @WebMethod
    @WebResult(name = "bonusTransReturn", targetNamespace = "http://oaas.creditcard.cmbchina.com")
    //@RequestWrapper(localName = "bonusTrans", targetNamespace = "http://oaas.creditcard.cmbchina.com", className = "com.cmbchina.creditcard.oaas.BonusTrans")
    //@ResponseWrapper(localName = "bonusTransResponse", targetNamespace = "http://oaas.creditcard.cmbchina.com", className = "com.cmbchina.creditcard.oaas.BonusTransResponse")
    public Response bonusTrans(
            @WebParam(name = "Token", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String token,
            @WebParam(name = "BatchNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String batchNum,
            @WebParam(name = "CardNo", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String cardNo,
            @WebParam(name = "ExpiryDate", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String expiryDate,
            @WebParam(name = "TraceNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            int traceNum,
            @WebParam(name = "Amount", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String amount,
            @WebParam(name = "StageNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            int stageNum,
            @WebParam(name = "InputType", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String inputType,
            @WebParam(name = "BonusAmount", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            int bonusAmount);

    /**
     * 
     * @param token
     * @param newPassword
     * @param oldPassword
     * @return
     *     returns com.chinadrtv.erp.sales.core.Merchants.model.Response
     */
    @WebMethod
    @WebResult(name = "changePasswordReturn", targetNamespace = "http://oaas.creditcard.cmbchina.com")
    //@RequestWrapper(localName = "changePassword", targetNamespace = "http://oaas.creditcard.cmbchina.com", className = "com.cmbchina.creditcard.oaas.ChangePassword")
    //@ResponseWrapper(localName = "changePasswordResponse", targetNamespace = "http://oaas.creditcard.cmbchina.com", className = "com.cmbchina.creditcard.oaas.ChangePasswordResponse")
    public Response changePassword(
            @WebParam(name = "Token", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String token,
            @WebParam(name = "OldPassword", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String oldPassword,
            @WebParam(name = "NewPassword", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String newPassword);

    /**
     * 
     * @param preAmount
     * @param preTraceNum
     * @param expiryDate
     * @param batchNum
     * @param traceNum
     * @param orderNum
     * @param bonusAmount
     * @param preTransTime
     * @param stageNum
     * @param cardNo
     * @param token
     * @param inputType
     * @param preBatchNum
     * @param preRefNum
     * @param preAuthID
     * @return
     *     returns com.chinadrtv.erp.sales.core.Merchants.model.Response
     */
    @WebMethod
    @WebResult(name = "bonusTransReturnCancelReturn", targetNamespace = "http://oaas.creditcard.cmbchina.com")
    //@RequestWrapper(localName = "bonusTransReturnCancel", targetNamespace = "http://oaas.creditcard.cmbchina.com", className = "com.cmbchina.creditcard.oaas.BonusTransReturnCancel")
    //@ResponseWrapper(localName = "bonusTransReturnCancelResponse", targetNamespace = "http://oaas.creditcard.cmbchina.com", className = "com.cmbchina.creditcard.oaas.BonusTransReturnCancelResponse")
    public Response bonusTransReturnCancel(
            @WebParam(name = "Token", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String token,
            @WebParam(name = "BatchNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String batchNum,
            @WebParam(name = "CardNo", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String cardNo,
            @WebParam(name = "ExpiryDate", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String expiryDate,
            @WebParam(name = "TraceNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            int traceNum,
            @WebParam(name = "PreAmount", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String preAmount,
            @WebParam(name = "PreBatchNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String preBatchNum,
            @WebParam(name = "PreTransTime", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String preTransTime,
            @WebParam(name = "PreTraceNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            int preTraceNum,
            @WebParam(name = "PreRefNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String preRefNum,
            @WebParam(name = "PreAuthID", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String preAuthID,
            @WebParam(name = "StageNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            int stageNum,
            @WebParam(name = "OrderNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String orderNum,
            @WebParam(name = "InputType", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String inputType,
            @WebParam(name = "BonusAmount", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            int bonusAmount);

    /**
     * 
     * @param amount
     * @param cardNo
     * @param token
     * @param expiryDate
     * @param traceNum
     * @param batchNum
     * @param stageNum
     * @return
     *     returns com.chinadrtv.erp.sales.core.Merchants.model.Response
     */
    @WebMethod
    @WebResult(name = "hirePurchaseReturn", targetNamespace = "http://oaas.creditcard.cmbchina.com")
    //@RequestWrapper(localName = "hirePurchase", targetNamespace = "http://oaas.creditcard.cmbchina.com", className = "com.cmbchina.creditcard.oaas.HirePurchase")
    //@ResponseWrapper(localName = "hirePurchaseResponse", targetNamespace = "http://oaas.creditcard.cmbchina.com", className = "com.cmbchina.creditcard.oaas.HirePurchaseResponse")
    public Response hirePurchase(
            @WebParam(name = "Token", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String token,
            @WebParam(name = "BatchNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String batchNum,
            @WebParam(name = "CardNo", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String cardNo,
            @WebParam(name = "ExpiryDate", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String expiryDate,
            @WebParam(name = "TraceNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            int traceNum,
            @WebParam(name = "Amount", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String amount,
            @WebParam(name = "StageNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            int stageNum);

    /**
     * 
     * @param amount
     * @param cardNo
     * @param phoneNum
     * @param certNum
     * @param phoneType
     * @param token
     * @param verfType
     * @param expiryDate
     * @param certType
     * @param traceNum
     * @param batchNum
     * @param stageNum
     * @return
     *     returns com.chinadrtv.erp.sales.core.Merchants.model.Response
     */
    @WebMethod
    @WebResult(name = "hirePurchaseWithVerfReturn", targetNamespace = "http://oaas.creditcard.cmbchina.com")
    //@RequestWrapper(localName = "hirePurchaseWithVerf", targetNamespace = "http://oaas.creditcard.cmbchina.com", className = "com.cmbchina.creditcard.oaas.HirePurchaseWithVerf")
    //@ResponseWrapper(localName = "hirePurchaseWithVerfResponse", targetNamespace = "http://oaas.creditcard.cmbchina.com", className = "com.cmbchina.creditcard.oaas.HirePurchaseWithVerfResponse")
    public Response hirePurchaseWithVerf(
            @WebParam(name = "Token", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String token,
            @WebParam(name = "BatchNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String batchNum,
            @WebParam(name = "CardNo", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String cardNo,
            @WebParam(name = "ExpiryDate", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String expiryDate,
            @WebParam(name = "TraceNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            int traceNum,
            @WebParam(name = "Amount", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String amount,
            @WebParam(name = "StageNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            int stageNum,
            @WebParam(name = "VerfType", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String verfType,
            @WebParam(name = "CertType", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String certType,
            @WebParam(name = "CertNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String certNum,
            @WebParam(name = "PhoneType", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String phoneType,
            @WebParam(name = "PhoneNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String phoneNum);

    /**
     * 
     * @param preTraceNum
     * @param preAmount
     * @param expiryDate
     * @param batchNum
     * @param traceNum
     * @param orderNum
     * @param preTransTime
     * @param stageNum
     * @param cardNo
     * @param token
     * @param preBatchNum
     * @param preRefNum
     * @param preAuthID
     * @return
     *     returns com.chinadrtv.erp.sales.core.Merchants.model.Response
     */
    @WebMethod
    @WebResult(name = "hirePurchaseCancelReturn", targetNamespace = "http://oaas.creditcard.cmbchina.com")
    //@RequestWrapper(localName = "hirePurchaseCancel", targetNamespace = "http://oaas.creditcard.cmbchina.com", className = "com.cmbchina.creditcard.oaas.HirePurchaseCancel")
    //@ResponseWrapper(localName = "hirePurchaseCancelResponse", targetNamespace = "http://oaas.creditcard.cmbchina.com", className = "com.cmbchina.creditcard.oaas.HirePurchaseCancelResponse")
    public Response hirePurchaseCancel(
            @WebParam(name = "Token", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String token,
            @WebParam(name = "BatchNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String batchNum,
            @WebParam(name = "CardNo", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String cardNo,
            @WebParam(name = "ExpiryDate", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String expiryDate,
            @WebParam(name = "TraceNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            int traceNum,
            @WebParam(name = "PreBatchNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String preBatchNum,
            @WebParam(name = "PreTransTime", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String preTransTime,
            @WebParam(name = "PreTraceNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            int preTraceNum,
            @WebParam(name = "PreRefNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String preRefNum,
            @WebParam(name = "PreAmount", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String preAmount,
            @WebParam(name = "PreAuthID", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String preAuthID,
            @WebParam(name = "StageNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            int stageNum,
            @WebParam(name = "OrderNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String orderNum);

    /**
     * 
     * @param preAmount
     * @param preTraceNum
     * @param expiryDate
     * @param batchNum
     * @param traceNum
     * @param orderNum
     * @param preTransTime
     * @param stageNum
     * @param cardNo
     * @param token
     * @param preBatchNum
     * @param preRefNum
     * @param preAuthID
     * @return
     *     returns com.chinadrtv.erp.sales.core.Merchants.model.Response
     */
    @WebMethod
    @WebResult(name = "hirePurchaseReturnCancelReturn", targetNamespace = "http://oaas.creditcard.cmbchina.com")
    //@RequestWrapper(localName = "hirePurchaseReturnCancel", targetNamespace = "http://oaas.creditcard.cmbchina.com", className = "com.cmbchina.creditcard.oaas.HirePurchaseReturnCancel")
    //@ResponseWrapper(localName = "hirePurchaseReturnCancelResponse", targetNamespace = "http://oaas.creditcard.cmbchina.com", className = "com.cmbchina.creditcard.oaas.HirePurchaseReturnCancelResponse")
    public Response hirePurchaseReturnCancel(
            @WebParam(name = "Token", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String token,
            @WebParam(name = "BatchNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String batchNum,
            @WebParam(name = "CardNo", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String cardNo,
            @WebParam(name = "ExpiryDate", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String expiryDate,
            @WebParam(name = "TraceNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            int traceNum,
            @WebParam(name = "PreAmount", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String preAmount,
            @WebParam(name = "PreBatchNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String preBatchNum,
            @WebParam(name = "PreTransTime", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String preTransTime,
            @WebParam(name = "PreTraceNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            int preTraceNum,
            @WebParam(name = "PreRefNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String preRefNum,
            @WebParam(name = "PreAuthID", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String preAuthID,
            @WebParam(name = "StageNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            int stageNum,
            @WebParam(name = "OrderNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String orderNum);

    /**
     * 
     * @param amount
     * @param cardNo
     * @param preTraceNum
     * @param token
     * @param expiryDate
     * @param preBatchNum
     * @param preRefNum
     * @param traceNum
     * @param batchNum
     * @param preAuthID
     * @param preTransTime
     * @return
     *     returns com.chinadrtv.erp.sales.core.Merchants.model.Response
     */
    @WebMethod
    @WebResult(name = "purchaseReturnReturn", targetNamespace = "http://oaas.creditcard.cmbchina.com")
    //@RequestWrapper(localName = "purchaseReturn", targetNamespace = "http://oaas.creditcard.cmbchina.com", className = "com.cmbchina.creditcard.oaas.PurchaseReturn")
    //@ResponseWrapper(localName = "purchaseReturnResponse", targetNamespace = "http://oaas.creditcard.cmbchina.com", className = "com.cmbchina.creditcard.oaas.PurchaseReturnResponse")
    public Response purchaseReturn(
            @WebParam(name = "Token", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String token,
            @WebParam(name = "BatchNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String batchNum,
            @WebParam(name = "CardNo", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String cardNo,
            @WebParam(name = "ExpiryDate", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String expiryDate,
            @WebParam(name = "TraceNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            int traceNum,
            @WebParam(name = "Amount", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String amount,
            @WebParam(name = "PreBatchNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String preBatchNum,
            @WebParam(name = "PreTransTime", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String preTransTime,
            @WebParam(name = "PreTraceNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            int preTraceNum,
            @WebParam(name = "PreRefNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String preRefNum,
            @WebParam(name = "PreAuthID", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String preAuthID);

    /**
     * 
     * @param amount
     * @param cardNo
     * @param token
     * @param expiryDate
     * @param traceNum
     * @param batchNum
     * @return
     *     returns com.chinadrtv.erp.sales.core.Merchants.model.Response
     */
    @WebMethod
    @WebResult(targetNamespace = "http://oaas.creditcard.cmbchina.com")
    //@RequestWrapper(localName = "purchase", targetNamespace = "http://oaas.creditcard.cmbchina.com", className = "com.cmbchina.creditcard.oaas.Purchase")
    //@ResponseWrapper(localName = "purchaseResponse", targetNamespace = "http://oaas.creditcard.cmbchina.com", className = "com.cmbchina.creditcard.oaas.PurchaseResponse")
    public Response purchase(
            @WebParam(name = "Token", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String token,
            @WebParam(name = "BatchNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String batchNum,
            @WebParam(name = "CardNo", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String cardNo,
            @WebParam(name = "ExpiryDate", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String expiryDate,
            @WebParam(name = "TraceNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            int traceNum,
            @WebParam(name = "Amount", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String amount);

    /**
     * 
     * @param cardNo
     * @param preAmount
     * @param preTraceNum
     * @param token
     * @param expiryDate
     * @param preBatchNum
     * @param traceNum
     * @param batchNum
     * @param preTransTime
     * @return
     *     returns com.chinadrtv.erp.sales.core.Merchants.model.Response
     */
    @WebMethod
    @WebResult(targetNamespace = "http://oaas.creditcard.cmbchina.com")
    //@RequestWrapper(localName = "purchaseRev", targetNamespace = "http://oaas.creditcard.cmbchina.com", className = "com.cmbchina.creditcard.oaas.PurchaseRev")
    //@ResponseWrapper(localName = "purchaseRevResponse", targetNamespace = "http://oaas.creditcard.cmbchina.com", className = "com.cmbchina.creditcard.oaas.PurchaseRevResponse")
    public Response purchaseRev(
            @WebParam(name = "Token", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String token,
            @WebParam(name = "BatchNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String batchNum,
            @WebParam(name = "CardNo", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String cardNo,
            @WebParam(name = "ExpiryDate", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String expiryDate,
            @WebParam(name = "TraceNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            int traceNum,
            @WebParam(name = "PreBatchNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String preBatchNum,
            @WebParam(name = "PreTransTime", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String preTransTime,
            @WebParam(name = "PreTraceNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            int preTraceNum,
            @WebParam(name = "PreAmount", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String preAmount);

    /**
     * 
     * @param amount
     * @param cardNo
     * @param preTraceNum
     * @param token
     * @param expiryDate
     * @param preBatchNum
     * @param preRefNum
     * @param traceNum
     * @param batchNum
     * @param preAuthID
     * @param preTransTime
     * @return
     *     returns com.chinadrtv.erp.sales.core.Merchants.model.Response
     */
    @WebMethod
    @WebResult(targetNamespace = "http://oaas.creditcard.cmbchina.com")
    //@RequestWrapper(localName = "purchaseCancel", targetNamespace = "http://oaas.creditcard.cmbchina.com", className = "com.cmbchina.creditcard.oaas.PurchaseCancel")
    //@ResponseWrapper(localName = "purchaseCancelResponse", targetNamespace = "http://oaas.creditcard.cmbchina.com", className = "com.cmbchina.creditcard.oaas.PurchaseCancelResponse")
    public Response purchaseCancel(
            @WebParam(name = "Token", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String token,
            @WebParam(name = "BatchNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String batchNum,
            @WebParam(name = "CardNo", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String cardNo,
            @WebParam(name = "ExpiryDate", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String expiryDate,
            @WebParam(name = "TraceNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            int traceNum,
            @WebParam(name = "Amount", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String amount,
            @WebParam(name = "PreBatchNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String preBatchNum,
            @WebParam(name = "PreTransTime", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String preTransTime,
            @WebParam(name = "PreTraceNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            int preTraceNum,
            @WebParam(name = "PreRefNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String preRefNum,
            @WebParam(name = "PreAuthID", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String preAuthID);

    /**
     * 
     * @param cardNo
     * @param preAmount
     * @param preTraceNum
     * @param token
     * @param expiryDate
     * @param preBatchNum
     * @param traceNum
     * @param batchNum
     * @param preAuthID
     * @param preTransTime
     * @return
     *     returns com.chinadrtv.erp.sales.core.Merchants.model.Response
     */
    @WebMethod
    @WebResult(targetNamespace = "http://oaas.creditcard.cmbchina.com")
    //@RequestWrapper(localName = "purchaseCancelRev", targetNamespace = "http://oaas.creditcard.cmbchina.com", className = "com.cmbchina.creditcard.oaas.PurchaseCancelRev")
    //@ResponseWrapper(localName = "purchaseCancelRevResponse", targetNamespace = "http://oaas.creditcard.cmbchina.com", className = "com.cmbchina.creditcard.oaas.PurchaseCancelRevResponse")
    public Response purchaseCancelRev(
            @WebParam(name = "Token", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String token,
            @WebParam(name = "BatchNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String batchNum,
            @WebParam(name = "CardNo", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String cardNo,
            @WebParam(name = "ExpiryDate", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String expiryDate,
            @WebParam(name = "TraceNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            int traceNum,
            @WebParam(name = "PreBatchNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String preBatchNum,
            @WebParam(name = "PreTransTime", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String preTransTime,
            @WebParam(name = "PreTraceNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            int preTraceNum,
            @WebParam(name = "PreAmount", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String preAmount,
            @WebParam(name = "PreAuthID", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String preAuthID);

    /**
     * 
     * @param amount
     * @param cardNo
     * @param token
     * @param expiryDate
     * @param traceNum
     * @param batchNum
     * @return
     *     returns com.chinadrtv.erp.sales.core.Merchants.model.Response
     */
    @WebMethod
    @WebResult(name = "purchaseReturnQueryReturn", targetNamespace = "http://oaas.creditcard.cmbchina.com")
    //@RequestWrapper(localName = "purchaseReturnQuery", targetNamespace = "http://oaas.creditcard.cmbchina.com", className = "com.cmbchina.creditcard.oaas.PurchaseReturnQuery")
    //@ResponseWrapper(localName = "purchaseReturnQueryResponse", targetNamespace = "http://oaas.creditcard.cmbchina.com", className = "com.cmbchina.creditcard.oaas.PurchaseReturnQueryResponse")
    public Response purchaseReturnQuery(
            @WebParam(name = "Token", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String token,
            @WebParam(name = "BatchNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String batchNum,
            @WebParam(name = "CardNo", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String cardNo,
            @WebParam(name = "ExpiryDate", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String expiryDate,
            @WebParam(name = "TraceNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            int traceNum,
            @WebParam(name = "Amount", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String amount);

    /**
     * 
     * @param preTraceNum
     * @param preAmount
     * @param expiryDate
     * @param batchNum
     * @param traceNum
     * @param orderNum
     * @param bonusAmount
     * @param preTransTime
     * @param stageNum
     * @param cardNo
     * @param token
     * @param inputType
     * @param preBatchNum
     * @return
     *     returns com.chinadrtv.erp.sales.core.Merchants.model.Response
     */
    @WebMethod
    @WebResult(name = "hPBTOperRevReturn", targetNamespace = "http://oaas.creditcard.cmbchina.com")
    //@RequestWrapper(localName = "hPBTOperRev", targetNamespace = "http://oaas.creditcard.cmbchina.com", className = "com.cmbchina.creditcard.oaas.HPBTOperRev")
    //@ResponseWrapper(localName = "hPBTOperRevResponse", targetNamespace = "http://oaas.creditcard.cmbchina.com", className = "com.cmbchina.creditcard.oaas.HPBTOperRevResponse")
    public Response hPBTOperRev(
            @WebParam(name = "Token", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String token,
            @WebParam(name = "BatchNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String batchNum,
            @WebParam(name = "CardNo", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String cardNo,
            @WebParam(name = "ExpiryDate", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String expiryDate,
            @WebParam(name = "TraceNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            int traceNum,
            @WebParam(name = "PreBatchNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String preBatchNum,
            @WebParam(name = "PreTransTime", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String preTransTime,
            @WebParam(name = "PreTraceNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            int preTraceNum,
            @WebParam(name = "PreAmount", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String preAmount,
            @WebParam(name = "StageNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            int stageNum,
            @WebParam(name = "OrderNum", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String orderNum,
            @WebParam(name = "InputType", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            String inputType,
            @WebParam(name = "BonusAmount", targetNamespace = "http://oaas.creditcard.cmbchina.com")
            int bonusAmount);

}
