package com.chinadrtv.model.oms;

public class AreaMapping {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.AREA_MAPPING.AREAID
     *
     * @mbggenerated Wed Oct 30 13:34:08 CST 2013
     */
    private Integer areaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.AREA_MAPPING.AREANAME
     *
     * @mbggenerated Wed Oct 30 13:34:08 CST 2013
     */
    private String areaname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.AREA_MAPPING.MAPPING_AREAID
     *
     * @mbggenerated Wed Oct 30 13:34:08 CST 2013
     */
    private Integer mappingAreaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.AREA_MAPPING.REMARK
     *
     * @mbggenerated Wed Oct 30 13:34:08 CST 2013
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.AREA_MAPPING.AREAID
     *
     * @return the value of ACOAPP_OMS.AREA_MAPPING.AREAID
     *
     * @mbggenerated Wed Oct 30 13:34:08 CST 2013
     */
    public Integer getAreaid() {
        return areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.AREA_MAPPING.AREAID
     *
     * @param areaid the value for ACOAPP_OMS.AREA_MAPPING.AREAID
     *
     * @mbggenerated Wed Oct 30 13:34:08 CST 2013
     */
    public void setAreaid(Integer areaid) {
        this.areaid = areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.AREA_MAPPING.AREANAME
     *
     * @return the value of ACOAPP_OMS.AREA_MAPPING.AREANAME
     *
     * @mbggenerated Wed Oct 30 13:34:08 CST 2013
     */
    public String getAreaname() {
        return areaname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.AREA_MAPPING.AREANAME
     *
     * @param areaname the value for ACOAPP_OMS.AREA_MAPPING.AREANAME
     *
     * @mbggenerated Wed Oct 30 13:34:08 CST 2013
     */
    public void setAreaname(String areaname) {
        this.areaname = areaname == null ? null : areaname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.AREA_MAPPING.MAPPING_AREAID
     *
     * @return the value of ACOAPP_OMS.AREA_MAPPING.MAPPING_AREAID
     *
     * @mbggenerated Wed Oct 30 13:34:08 CST 2013
     */
    public Integer getMappingAreaid() {
        return mappingAreaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.AREA_MAPPING.MAPPING_AREAID
     *
     * @param mappingAreaid the value for ACOAPP_OMS.AREA_MAPPING.MAPPING_AREAID
     *
     * @mbggenerated Wed Oct 30 13:34:08 CST 2013
     */
    public void setMappingAreaid(Integer mappingAreaid) {
        this.mappingAreaid = mappingAreaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.AREA_MAPPING.REMARK
     *
     * @return the value of ACOAPP_OMS.AREA_MAPPING.REMARK
     *
     * @mbggenerated Wed Oct 30 13:34:08 CST 2013
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.AREA_MAPPING.REMARK
     *
     * @param remark the value for ACOAPP_OMS.AREA_MAPPING.REMARK
     *
     * @mbggenerated Wed Oct 30 13:34:08 CST 2013
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}