package com.chinadrtv.model.oms;

public class CityMapping {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.CITY_MAPPING.CITYID
     *
     * @mbggenerated Wed Oct 30 13:34:08 CST 2013
     */
    private Integer cityid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.CITY_MAPPING.CITYNAME
     *
     * @mbggenerated Wed Oct 30 13:34:08 CST 2013
     */
    private String cityname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.CITY_MAPPING.MAPPING_CITYID
     *
     * @mbggenerated Wed Oct 30 13:34:08 CST 2013
     */
    private Integer mappingCityid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.CITY_MAPPING.REMARK
     *
     * @mbggenerated Wed Oct 30 13:34:08 CST 2013
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.CITY_MAPPING.CITYID
     *
     * @return the value of ACOAPP_OMS.CITY_MAPPING.CITYID
     *
     * @mbggenerated Wed Oct 30 13:34:08 CST 2013
     */
    public Integer getCityid() {
        return cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.CITY_MAPPING.CITYID
     *
     * @param cityid the value for ACOAPP_OMS.CITY_MAPPING.CITYID
     *
     * @mbggenerated Wed Oct 30 13:34:08 CST 2013
     */
    public void setCityid(Integer cityid) {
        this.cityid = cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.CITY_MAPPING.CITYNAME
     *
     * @return the value of ACOAPP_OMS.CITY_MAPPING.CITYNAME
     *
     * @mbggenerated Wed Oct 30 13:34:08 CST 2013
     */
    public String getCityname() {
        return cityname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.CITY_MAPPING.CITYNAME
     *
     * @param cityname the value for ACOAPP_OMS.CITY_MAPPING.CITYNAME
     *
     * @mbggenerated Wed Oct 30 13:34:08 CST 2013
     */
    public void setCityname(String cityname) {
        this.cityname = cityname == null ? null : cityname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.CITY_MAPPING.MAPPING_CITYID
     *
     * @return the value of ACOAPP_OMS.CITY_MAPPING.MAPPING_CITYID
     *
     * @mbggenerated Wed Oct 30 13:34:08 CST 2013
     */
    public Integer getMappingCityid() {
        return mappingCityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.CITY_MAPPING.MAPPING_CITYID
     *
     * @param mappingCityid the value for ACOAPP_OMS.CITY_MAPPING.MAPPING_CITYID
     *
     * @mbggenerated Wed Oct 30 13:34:08 CST 2013
     */
    public void setMappingCityid(Integer mappingCityid) {
        this.mappingCityid = mappingCityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.CITY_MAPPING.REMARK
     *
     * @return the value of ACOAPP_OMS.CITY_MAPPING.REMARK
     *
     * @mbggenerated Wed Oct 30 13:34:08 CST 2013
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.CITY_MAPPING.REMARK
     *
     * @param remark the value for ACOAPP_OMS.CITY_MAPPING.REMARK
     *
     * @mbggenerated Wed Oct 30 13:34:08 CST 2013
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}