package com.chinadrtv.model.oms;

import java.util.Date;

public class PreTradeCard {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PRE_TRADE_CARD.ID
     *
     * @mbggenerated Wed Oct 30 10:57:27 CST 2013
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PRE_TRADE_CARD.TRADE_ID
     *
     * @mbggenerated Wed Oct 30 10:57:27 CST 2013
     */
    private String tradeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PRE_TRADE_CARD.PRE_TRADE_ID
     *
     * @mbggenerated Wed Oct 30 10:57:27 CST 2013
     */
    private Long preTradeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PRE_TRADE_CARD.BANK_CODE
     *
     * @mbggenerated Wed Oct 30 10:57:27 CST 2013
     */
    private String bankCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PRE_TRADE_CARD.AUTH_CODE
     *
     * @mbggenerated Wed Oct 30 10:57:27 CST 2013
     */
    private String authCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PRE_TRADE_CARD.ID_CARD_NUMBER
     *
     * @mbggenerated Wed Oct 30 10:57:27 CST 2013
     */
    private String idCardNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PRE_TRADE_CARD.CREDIT_CARD_NUMBER
     *
     * @mbggenerated Wed Oct 30 10:57:27 CST 2013
     */
    private String creditCardNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PRE_TRADE_CARD.CREDIT_CARD_EXPIRE
     *
     * @mbggenerated Wed Oct 30 10:57:27 CST 2013
     */
    private String creditCardExpire;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PRE_TRADE_CARD.CREDIT_CARD_CYCLES
     *
     * @mbggenerated Wed Oct 30 10:57:27 CST 2013
     */
    private Long creditCardCycles;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PRE_TRADE_CARD.CREATE_USER
     *
     * @mbggenerated Wed Oct 30 10:57:27 CST 2013
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PRE_TRADE_CARD.CREATE_DATE
     *
     * @mbggenerated Wed Oct 30 10:57:27 CST 2013
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PRE_TRADE_CARD.UPDATE_USER
     *
     * @mbggenerated Wed Oct 30 10:57:27 CST 2013
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PRE_TRADE_CARD.UPDATE_DATE
     *
     * @mbggenerated Wed Oct 30 10:57:27 CST 2013
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PRE_TRADE_CARD.ID
     *
     * @return the value of ACOAPP_OMS.PRE_TRADE_CARD.ID
     *
     * @mbggenerated Wed Oct 30 10:57:27 CST 2013
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PRE_TRADE_CARD.ID
     *
     * @param id the value for ACOAPP_OMS.PRE_TRADE_CARD.ID
     *
     * @mbggenerated Wed Oct 30 10:57:27 CST 2013
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PRE_TRADE_CARD.TRADE_ID
     *
     * @return the value of ACOAPP_OMS.PRE_TRADE_CARD.TRADE_ID
     *
     * @mbggenerated Wed Oct 30 10:57:27 CST 2013
     */
    public String getTradeId() {
        return tradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PRE_TRADE_CARD.TRADE_ID
     *
     * @param tradeId the value for ACOAPP_OMS.PRE_TRADE_CARD.TRADE_ID
     *
     * @mbggenerated Wed Oct 30 10:57:27 CST 2013
     */
    public void setTradeId(String tradeId) {
        this.tradeId = tradeId == null ? null : tradeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PRE_TRADE_CARD.PRE_TRADE_ID
     *
     * @return the value of ACOAPP_OMS.PRE_TRADE_CARD.PRE_TRADE_ID
     *
     * @mbggenerated Wed Oct 30 10:57:27 CST 2013
     */
    public Long getPreTradeId() {
        return preTradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PRE_TRADE_CARD.PRE_TRADE_ID
     *
     * @param preTradeId the value for ACOAPP_OMS.PRE_TRADE_CARD.PRE_TRADE_ID
     *
     * @mbggenerated Wed Oct 30 10:57:27 CST 2013
     */
    public void setPreTradeId(Long preTradeId) {
        this.preTradeId = preTradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PRE_TRADE_CARD.BANK_CODE
     *
     * @return the value of ACOAPP_OMS.PRE_TRADE_CARD.BANK_CODE
     *
     * @mbggenerated Wed Oct 30 10:57:27 CST 2013
     */
    public String getBankCode() {
        return bankCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PRE_TRADE_CARD.BANK_CODE
     *
     * @param bankCode the value for ACOAPP_OMS.PRE_TRADE_CARD.BANK_CODE
     *
     * @mbggenerated Wed Oct 30 10:57:27 CST 2013
     */
    public void setBankCode(String bankCode) {
        this.bankCode = bankCode == null ? null : bankCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PRE_TRADE_CARD.AUTH_CODE
     *
     * @return the value of ACOAPP_OMS.PRE_TRADE_CARD.AUTH_CODE
     *
     * @mbggenerated Wed Oct 30 10:57:27 CST 2013
     */
    public String getAuthCode() {
        return authCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PRE_TRADE_CARD.AUTH_CODE
     *
     * @param authCode the value for ACOAPP_OMS.PRE_TRADE_CARD.AUTH_CODE
     *
     * @mbggenerated Wed Oct 30 10:57:27 CST 2013
     */
    public void setAuthCode(String authCode) {
        this.authCode = authCode == null ? null : authCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PRE_TRADE_CARD.ID_CARD_NUMBER
     *
     * @return the value of ACOAPP_OMS.PRE_TRADE_CARD.ID_CARD_NUMBER
     *
     * @mbggenerated Wed Oct 30 10:57:27 CST 2013
     */
    public String getIdCardNumber() {
        return idCardNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PRE_TRADE_CARD.ID_CARD_NUMBER
     *
     * @param idCardNumber the value for ACOAPP_OMS.PRE_TRADE_CARD.ID_CARD_NUMBER
     *
     * @mbggenerated Wed Oct 30 10:57:27 CST 2013
     */
    public void setIdCardNumber(String idCardNumber) {
        this.idCardNumber = idCardNumber == null ? null : idCardNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PRE_TRADE_CARD.CREDIT_CARD_NUMBER
     *
     * @return the value of ACOAPP_OMS.PRE_TRADE_CARD.CREDIT_CARD_NUMBER
     *
     * @mbggenerated Wed Oct 30 10:57:27 CST 2013
     */
    public String getCreditCardNumber() {
        return creditCardNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PRE_TRADE_CARD.CREDIT_CARD_NUMBER
     *
     * @param creditCardNumber the value for ACOAPP_OMS.PRE_TRADE_CARD.CREDIT_CARD_NUMBER
     *
     * @mbggenerated Wed Oct 30 10:57:27 CST 2013
     */
    public void setCreditCardNumber(String creditCardNumber) {
        this.creditCardNumber = creditCardNumber == null ? null : creditCardNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PRE_TRADE_CARD.CREDIT_CARD_EXPIRE
     *
     * @return the value of ACOAPP_OMS.PRE_TRADE_CARD.CREDIT_CARD_EXPIRE
     *
     * @mbggenerated Wed Oct 30 10:57:27 CST 2013
     */
    public String getCreditCardExpire() {
        return creditCardExpire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PRE_TRADE_CARD.CREDIT_CARD_EXPIRE
     *
     * @param creditCardExpire the value for ACOAPP_OMS.PRE_TRADE_CARD.CREDIT_CARD_EXPIRE
     *
     * @mbggenerated Wed Oct 30 10:57:27 CST 2013
     */
    public void setCreditCardExpire(String creditCardExpire) {
        this.creditCardExpire = creditCardExpire == null ? null : creditCardExpire.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PRE_TRADE_CARD.CREDIT_CARD_CYCLES
     *
     * @return the value of ACOAPP_OMS.PRE_TRADE_CARD.CREDIT_CARD_CYCLES
     *
     * @mbggenerated Wed Oct 30 10:57:27 CST 2013
     */
    public Long getCreditCardCycles() {
        return creditCardCycles;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PRE_TRADE_CARD.CREDIT_CARD_CYCLES
     *
     * @param creditCardCycles the value for ACOAPP_OMS.PRE_TRADE_CARD.CREDIT_CARD_CYCLES
     *
     * @mbggenerated Wed Oct 30 10:57:27 CST 2013
     */
    public void setCreditCardCycles(Long creditCardCycles) {
        this.creditCardCycles = creditCardCycles;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PRE_TRADE_CARD.CREATE_USER
     *
     * @return the value of ACOAPP_OMS.PRE_TRADE_CARD.CREATE_USER
     *
     * @mbggenerated Wed Oct 30 10:57:27 CST 2013
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PRE_TRADE_CARD.CREATE_USER
     *
     * @param createUser the value for ACOAPP_OMS.PRE_TRADE_CARD.CREATE_USER
     *
     * @mbggenerated Wed Oct 30 10:57:27 CST 2013
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PRE_TRADE_CARD.CREATE_DATE
     *
     * @return the value of ACOAPP_OMS.PRE_TRADE_CARD.CREATE_DATE
     *
     * @mbggenerated Wed Oct 30 10:57:27 CST 2013
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PRE_TRADE_CARD.CREATE_DATE
     *
     * @param createDate the value for ACOAPP_OMS.PRE_TRADE_CARD.CREATE_DATE
     *
     * @mbggenerated Wed Oct 30 10:57:27 CST 2013
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PRE_TRADE_CARD.UPDATE_USER
     *
     * @return the value of ACOAPP_OMS.PRE_TRADE_CARD.UPDATE_USER
     *
     * @mbggenerated Wed Oct 30 10:57:27 CST 2013
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PRE_TRADE_CARD.UPDATE_USER
     *
     * @param updateUser the value for ACOAPP_OMS.PRE_TRADE_CARD.UPDATE_USER
     *
     * @mbggenerated Wed Oct 30 10:57:27 CST 2013
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PRE_TRADE_CARD.UPDATE_DATE
     *
     * @return the value of ACOAPP_OMS.PRE_TRADE_CARD.UPDATE_DATE
     *
     * @mbggenerated Wed Oct 30 10:57:27 CST 2013
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PRE_TRADE_CARD.UPDATE_DATE
     *
     * @param updateDate the value for ACOAPP_OMS.PRE_TRADE_CARD.UPDATE_DATE
     *
     * @mbggenerated Wed Oct 30 10:57:27 CST 2013
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}