package com.chinadrtv.model.oms;

import java.util.Date;

public class PreTradeInsurance {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PRE_TRADE_INSURANCE.ID
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PRE_TRADE_INSURANCE.OUT_SKU_ID
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    private String outSkuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PRE_TRADE_INSURANCE.ISACTIVE
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    private String isactive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PRE_TRADE_INSURANCE.CREATE_USER
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PRE_TRADE_INSURANCE.CREATE_DATE
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PRE_TRADE_INSURANCE.UPDATE_USER
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PRE_TRADE_INSURANCE.UPDATE_DATE
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PRE_TRADE_INSURANCE.ID
     *
     * @return the value of ACOAPP_OMS.PRE_TRADE_INSURANCE.ID
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PRE_TRADE_INSURANCE.ID
     *
     * @param id the value for ACOAPP_OMS.PRE_TRADE_INSURANCE.ID
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PRE_TRADE_INSURANCE.OUT_SKU_ID
     *
     * @return the value of ACOAPP_OMS.PRE_TRADE_INSURANCE.OUT_SKU_ID
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public String getOutSkuId() {
        return outSkuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PRE_TRADE_INSURANCE.OUT_SKU_ID
     *
     * @param outSkuId the value for ACOAPP_OMS.PRE_TRADE_INSURANCE.OUT_SKU_ID
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public void setOutSkuId(String outSkuId) {
        this.outSkuId = outSkuId == null ? null : outSkuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PRE_TRADE_INSURANCE.ISACTIVE
     *
     * @return the value of ACOAPP_OMS.PRE_TRADE_INSURANCE.ISACTIVE
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public String getIsactive() {
        return isactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PRE_TRADE_INSURANCE.ISACTIVE
     *
     * @param isactive the value for ACOAPP_OMS.PRE_TRADE_INSURANCE.ISACTIVE
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public void setIsactive(String isactive) {
        this.isactive = isactive == null ? null : isactive.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PRE_TRADE_INSURANCE.CREATE_USER
     *
     * @return the value of ACOAPP_OMS.PRE_TRADE_INSURANCE.CREATE_USER
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PRE_TRADE_INSURANCE.CREATE_USER
     *
     * @param createUser the value for ACOAPP_OMS.PRE_TRADE_INSURANCE.CREATE_USER
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PRE_TRADE_INSURANCE.CREATE_DATE
     *
     * @return the value of ACOAPP_OMS.PRE_TRADE_INSURANCE.CREATE_DATE
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PRE_TRADE_INSURANCE.CREATE_DATE
     *
     * @param createDate the value for ACOAPP_OMS.PRE_TRADE_INSURANCE.CREATE_DATE
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PRE_TRADE_INSURANCE.UPDATE_USER
     *
     * @return the value of ACOAPP_OMS.PRE_TRADE_INSURANCE.UPDATE_USER
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PRE_TRADE_INSURANCE.UPDATE_USER
     *
     * @param updateUser the value for ACOAPP_OMS.PRE_TRADE_INSURANCE.UPDATE_USER
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PRE_TRADE_INSURANCE.UPDATE_DATE
     *
     * @return the value of ACOAPP_OMS.PRE_TRADE_INSURANCE.UPDATE_DATE
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PRE_TRADE_INSURANCE.UPDATE_DATE
     *
     * @param updateDate the value for ACOAPP_OMS.PRE_TRADE_INSURANCE.UPDATE_DATE
     *
     * @mbggenerated Wed Oct 30 13:54:38 CST 2013
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}