package com.chinadrtv.model.oms;

import java.util.Date;

public class PreTradeLot {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PRE_TRADE_LOT.ID
     *
     * @mbggenerated Wed Oct 30 10:57:27 CST 2013
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PRE_TRADE_LOT.STATUS
     *
     * @mbggenerated Wed Oct 30 10:57:27 CST 2013
     */
    private Long status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PRE_TRADE_LOT.LOT_DSC
     *
     * @mbggenerated Wed Oct 30 10:57:27 CST 2013
     */
    private String lotDsc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PRE_TRADE_LOT.CRUSR
     *
     * @mbggenerated Wed Oct 30 10:57:27 CST 2013
     */
    private String crusr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PRE_TRADE_LOT.CRDT
     *
     * @mbggenerated Wed Oct 30 10:57:27 CST 2013
     */
    private Date crdt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PRE_TRADE_LOT.DLUSR
     *
     * @mbggenerated Wed Oct 30 10:57:27 CST 2013
     */
    private String dlusr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PRE_TRADE_LOT.DLDT
     *
     * @mbggenerated Wed Oct 30 10:57:27 CST 2013
     */
    private Date dldt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PRE_TRADE_LOT.UPLOADER
     *
     * @mbggenerated Wed Oct 30 10:57:27 CST 2013
     */
    private String uploader;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PRE_TRADE_LOT.VALID_COUNT
     *
     * @mbggenerated Wed Oct 30 10:57:27 CST 2013
     */
    private Long validCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PRE_TRADE_LOT.ERR_COUNT
     *
     * @mbggenerated Wed Oct 30 10:57:27 CST 2013
     */
    private Long errCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PRE_TRADE_LOT.TOTAL_COUNT
     *
     * @mbggenerated Wed Oct 30 10:57:27 CST 2013
     */
    private Long totalCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PRE_TRADE_LOT.SOURCE_ID
     *
     * @mbggenerated Wed Oct 30 10:57:27 CST 2013
     */
    private Long sourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PRE_TRADE_LOT.ERR_MSG
     *
     * @mbggenerated Wed Oct 30 10:57:27 CST 2013
     */
    private String errMsg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PRE_TRADE_LOT.ID
     *
     * @return the value of ACOAPP_OMS.PRE_TRADE_LOT.ID
     *
     * @mbggenerated Wed Oct 30 10:57:27 CST 2013
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PRE_TRADE_LOT.ID
     *
     * @param id the value for ACOAPP_OMS.PRE_TRADE_LOT.ID
     *
     * @mbggenerated Wed Oct 30 10:57:27 CST 2013
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PRE_TRADE_LOT.STATUS
     *
     * @return the value of ACOAPP_OMS.PRE_TRADE_LOT.STATUS
     *
     * @mbggenerated Wed Oct 30 10:57:27 CST 2013
     */
    public Long getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PRE_TRADE_LOT.STATUS
     *
     * @param status the value for ACOAPP_OMS.PRE_TRADE_LOT.STATUS
     *
     * @mbggenerated Wed Oct 30 10:57:27 CST 2013
     */
    public void setStatus(Long status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PRE_TRADE_LOT.LOT_DSC
     *
     * @return the value of ACOAPP_OMS.PRE_TRADE_LOT.LOT_DSC
     *
     * @mbggenerated Wed Oct 30 10:57:27 CST 2013
     */
    public String getLotDsc() {
        return lotDsc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PRE_TRADE_LOT.LOT_DSC
     *
     * @param lotDsc the value for ACOAPP_OMS.PRE_TRADE_LOT.LOT_DSC
     *
     * @mbggenerated Wed Oct 30 10:57:27 CST 2013
     */
    public void setLotDsc(String lotDsc) {
        this.lotDsc = lotDsc == null ? null : lotDsc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PRE_TRADE_LOT.CRUSR
     *
     * @return the value of ACOAPP_OMS.PRE_TRADE_LOT.CRUSR
     *
     * @mbggenerated Wed Oct 30 10:57:27 CST 2013
     */
    public String getCrusr() {
        return crusr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PRE_TRADE_LOT.CRUSR
     *
     * @param crusr the value for ACOAPP_OMS.PRE_TRADE_LOT.CRUSR
     *
     * @mbggenerated Wed Oct 30 10:57:27 CST 2013
     */
    public void setCrusr(String crusr) {
        this.crusr = crusr == null ? null : crusr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PRE_TRADE_LOT.CRDT
     *
     * @return the value of ACOAPP_OMS.PRE_TRADE_LOT.CRDT
     *
     * @mbggenerated Wed Oct 30 10:57:27 CST 2013
     */
    public Date getCrdt() {
        return crdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PRE_TRADE_LOT.CRDT
     *
     * @param crdt the value for ACOAPP_OMS.PRE_TRADE_LOT.CRDT
     *
     * @mbggenerated Wed Oct 30 10:57:27 CST 2013
     */
    public void setCrdt(Date crdt) {
        this.crdt = crdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PRE_TRADE_LOT.DLUSR
     *
     * @return the value of ACOAPP_OMS.PRE_TRADE_LOT.DLUSR
     *
     * @mbggenerated Wed Oct 30 10:57:27 CST 2013
     */
    public String getDlusr() {
        return dlusr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PRE_TRADE_LOT.DLUSR
     *
     * @param dlusr the value for ACOAPP_OMS.PRE_TRADE_LOT.DLUSR
     *
     * @mbggenerated Wed Oct 30 10:57:27 CST 2013
     */
    public void setDlusr(String dlusr) {
        this.dlusr = dlusr == null ? null : dlusr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PRE_TRADE_LOT.DLDT
     *
     * @return the value of ACOAPP_OMS.PRE_TRADE_LOT.DLDT
     *
     * @mbggenerated Wed Oct 30 10:57:27 CST 2013
     */
    public Date getDldt() {
        return dldt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PRE_TRADE_LOT.DLDT
     *
     * @param dldt the value for ACOAPP_OMS.PRE_TRADE_LOT.DLDT
     *
     * @mbggenerated Wed Oct 30 10:57:27 CST 2013
     */
    public void setDldt(Date dldt) {
        this.dldt = dldt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PRE_TRADE_LOT.UPLOADER
     *
     * @return the value of ACOAPP_OMS.PRE_TRADE_LOT.UPLOADER
     *
     * @mbggenerated Wed Oct 30 10:57:27 CST 2013
     */
    public String getUploader() {
        return uploader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PRE_TRADE_LOT.UPLOADER
     *
     * @param uploader the value for ACOAPP_OMS.PRE_TRADE_LOT.UPLOADER
     *
     * @mbggenerated Wed Oct 30 10:57:27 CST 2013
     */
    public void setUploader(String uploader) {
        this.uploader = uploader == null ? null : uploader.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PRE_TRADE_LOT.VALID_COUNT
     *
     * @return the value of ACOAPP_OMS.PRE_TRADE_LOT.VALID_COUNT
     *
     * @mbggenerated Wed Oct 30 10:57:27 CST 2013
     */
    public Long getValidCount() {
        return validCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PRE_TRADE_LOT.VALID_COUNT
     *
     * @param validCount the value for ACOAPP_OMS.PRE_TRADE_LOT.VALID_COUNT
     *
     * @mbggenerated Wed Oct 30 10:57:27 CST 2013
     */
    public void setValidCount(Long validCount) {
        this.validCount = validCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PRE_TRADE_LOT.ERR_COUNT
     *
     * @return the value of ACOAPP_OMS.PRE_TRADE_LOT.ERR_COUNT
     *
     * @mbggenerated Wed Oct 30 10:57:27 CST 2013
     */
    public Long getErrCount() {
        return errCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PRE_TRADE_LOT.ERR_COUNT
     *
     * @param errCount the value for ACOAPP_OMS.PRE_TRADE_LOT.ERR_COUNT
     *
     * @mbggenerated Wed Oct 30 10:57:27 CST 2013
     */
    public void setErrCount(Long errCount) {
        this.errCount = errCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PRE_TRADE_LOT.TOTAL_COUNT
     *
     * @return the value of ACOAPP_OMS.PRE_TRADE_LOT.TOTAL_COUNT
     *
     * @mbggenerated Wed Oct 30 10:57:27 CST 2013
     */
    public Long getTotalCount() {
        return totalCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PRE_TRADE_LOT.TOTAL_COUNT
     *
     * @param totalCount the value for ACOAPP_OMS.PRE_TRADE_LOT.TOTAL_COUNT
     *
     * @mbggenerated Wed Oct 30 10:57:27 CST 2013
     */
    public void setTotalCount(Long totalCount) {
        this.totalCount = totalCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PRE_TRADE_LOT.SOURCE_ID
     *
     * @return the value of ACOAPP_OMS.PRE_TRADE_LOT.SOURCE_ID
     *
     * @mbggenerated Wed Oct 30 10:57:27 CST 2013
     */
    public Long getSourceId() {
        return sourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PRE_TRADE_LOT.SOURCE_ID
     *
     * @param sourceId the value for ACOAPP_OMS.PRE_TRADE_LOT.SOURCE_ID
     *
     * @mbggenerated Wed Oct 30 10:57:27 CST 2013
     */
    public void setSourceId(Long sourceId) {
        this.sourceId = sourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PRE_TRADE_LOT.ERR_MSG
     *
     * @return the value of ACOAPP_OMS.PRE_TRADE_LOT.ERR_MSG
     *
     * @mbggenerated Wed Oct 30 10:57:27 CST 2013
     */
    public String getErrMsg() {
        return errMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PRE_TRADE_LOT.ERR_MSG
     *
     * @param errMsg the value for ACOAPP_OMS.PRE_TRADE_LOT.ERR_MSG
     *
     * @mbggenerated Wed Oct 30 10:57:27 CST 2013
     */
    public void setErrMsg(String errMsg) {
        this.errMsg = errMsg == null ? null : errMsg.trim();
    }
}