package com.chinadrtv.model.oms;

import java.math.BigDecimal;
import java.util.Date;

public class PromotionRuleOption {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PROMOTION_RULE_OPTION.RULE_OPTION_ID
     *
     * @mbggenerated Fri Nov 01 13:52:58 CST 2013
     */
    private BigDecimal ruleOptionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PROMOTION_RULE_OPTION.CREATED_BY
     *
     * @mbggenerated Fri Nov 01 13:52:58 CST 2013
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PROMOTION_RULE_OPTION.DATE_ADDED
     *
     * @mbggenerated Fri Nov 01 13:52:58 CST 2013
     */
    private Date dateAdded;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PROMOTION_RULE_OPTION.RULE_OPTION_DEFAULT
     *
     * @mbggenerated Fri Nov 01 13:52:58 CST 2013
     */
    private String ruleOptionDefault;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PROMOTION_RULE_OPTION.RULE_OPTION_DESCRIPTION
     *
     * @mbggenerated Fri Nov 01 13:52:58 CST 2013
     */
    private String ruleOptionDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PROMOTION_RULE_OPTION.I18N_KEY
     *
     * @mbggenerated Fri Nov 01 13:52:58 CST 2013
     */
    private String i18nKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PROMOTION_RULE_OPTION.RULE_OPTION_KEY
     *
     * @mbggenerated Fri Nov 01 13:52:58 CST 2013
     */
    private String ruleOptionKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PROMOTION_RULE_OPTION.LAST_MODIFIED
     *
     * @mbggenerated Fri Nov 01 13:52:58 CST 2013
     */
    private Date lastModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PROMOTION_RULE_OPTION.MAX_VALUE
     *
     * @mbggenerated Fri Nov 01 13:52:58 CST 2013
     */
    private Double maxValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PROMOTION_RULE_OPTION.MIN_VALUE
     *
     * @mbggenerated Fri Nov 01 13:52:58 CST 2013
     */
    private Double minValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PROMOTION_RULE_OPTION.RULE_OPTION_NAME
     *
     * @mbggenerated Fri Nov 01 13:52:58 CST 2013
     */
    private String ruleOptionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PROMOTION_RULE_OPTION.RULE_OPTION_OPTIONS
     *
     * @mbggenerated Fri Nov 01 13:52:58 CST 2013
     */
    private String ruleOptionOptions;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PROMOTION_RULE_OPTION.IS_REQUIRED
     *
     * @mbggenerated Fri Nov 01 13:52:58 CST 2013
     */
    private Short isRequired;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PROMOTION_RULE_OPTION.SORT_ID
     *
     * @mbggenerated Fri Nov 01 13:52:58 CST 2013
     */
    private BigDecimal sortId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PROMOTION_RULE_OPTION.RULE_OPTION_TYPE
     *
     * @mbggenerated Fri Nov 01 13:52:58 CST 2013
     */
    private String ruleOptionType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PROMOTION_RULE_OPTION.UPDATE_BY
     *
     * @mbggenerated Fri Nov 01 13:52:58 CST 2013
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PROMOTION_RULE_OPTION.RULE_ID
     *
     * @mbggenerated Fri Nov 01 13:52:58 CST 2013
     */
    private BigDecimal ruleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PROMOTION_RULE_OPTION.RULE_OPTION_TYPE_SIZE
     *
     * @mbggenerated Fri Nov 01 13:52:58 CST 2013
     */
    private Long ruleOptionTypeSize;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PROMOTION_RULE_OPTION.RULE_OPTION_ID
     *
     * @return the value of ACOAPP_OMS.PROMOTION_RULE_OPTION.RULE_OPTION_ID
     *
     * @mbggenerated Fri Nov 01 13:52:58 CST 2013
     */
    public BigDecimal getRuleOptionId() {
        return ruleOptionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PROMOTION_RULE_OPTION.RULE_OPTION_ID
     *
     * @param ruleOptionId the value for ACOAPP_OMS.PROMOTION_RULE_OPTION.RULE_OPTION_ID
     *
     * @mbggenerated Fri Nov 01 13:52:58 CST 2013
     */
    public void setRuleOptionId(BigDecimal ruleOptionId) {
        this.ruleOptionId = ruleOptionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PROMOTION_RULE_OPTION.CREATED_BY
     *
     * @return the value of ACOAPP_OMS.PROMOTION_RULE_OPTION.CREATED_BY
     *
     * @mbggenerated Fri Nov 01 13:52:58 CST 2013
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PROMOTION_RULE_OPTION.CREATED_BY
     *
     * @param createdBy the value for ACOAPP_OMS.PROMOTION_RULE_OPTION.CREATED_BY
     *
     * @mbggenerated Fri Nov 01 13:52:58 CST 2013
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PROMOTION_RULE_OPTION.DATE_ADDED
     *
     * @return the value of ACOAPP_OMS.PROMOTION_RULE_OPTION.DATE_ADDED
     *
     * @mbggenerated Fri Nov 01 13:52:58 CST 2013
     */
    public Date getDateAdded() {
        return dateAdded;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PROMOTION_RULE_OPTION.DATE_ADDED
     *
     * @param dateAdded the value for ACOAPP_OMS.PROMOTION_RULE_OPTION.DATE_ADDED
     *
     * @mbggenerated Fri Nov 01 13:52:58 CST 2013
     */
    public void setDateAdded(Date dateAdded) {
        this.dateAdded = dateAdded;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PROMOTION_RULE_OPTION.RULE_OPTION_DEFAULT
     *
     * @return the value of ACOAPP_OMS.PROMOTION_RULE_OPTION.RULE_OPTION_DEFAULT
     *
     * @mbggenerated Fri Nov 01 13:52:58 CST 2013
     */
    public String getRuleOptionDefault() {
        return ruleOptionDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PROMOTION_RULE_OPTION.RULE_OPTION_DEFAULT
     *
     * @param ruleOptionDefault the value for ACOAPP_OMS.PROMOTION_RULE_OPTION.RULE_OPTION_DEFAULT
     *
     * @mbggenerated Fri Nov 01 13:52:58 CST 2013
     */
    public void setRuleOptionDefault(String ruleOptionDefault) {
        this.ruleOptionDefault = ruleOptionDefault == null ? null : ruleOptionDefault.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PROMOTION_RULE_OPTION.RULE_OPTION_DESCRIPTION
     *
     * @return the value of ACOAPP_OMS.PROMOTION_RULE_OPTION.RULE_OPTION_DESCRIPTION
     *
     * @mbggenerated Fri Nov 01 13:52:58 CST 2013
     */
    public String getRuleOptionDescription() {
        return ruleOptionDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PROMOTION_RULE_OPTION.RULE_OPTION_DESCRIPTION
     *
     * @param ruleOptionDescription the value for ACOAPP_OMS.PROMOTION_RULE_OPTION.RULE_OPTION_DESCRIPTION
     *
     * @mbggenerated Fri Nov 01 13:52:58 CST 2013
     */
    public void setRuleOptionDescription(String ruleOptionDescription) {
        this.ruleOptionDescription = ruleOptionDescription == null ? null : ruleOptionDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PROMOTION_RULE_OPTION.I18N_KEY
     *
     * @return the value of ACOAPP_OMS.PROMOTION_RULE_OPTION.I18N_KEY
     *
     * @mbggenerated Fri Nov 01 13:52:58 CST 2013
     */
    public String getI18nKey() {
        return i18nKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PROMOTION_RULE_OPTION.I18N_KEY
     *
     * @param i18nKey the value for ACOAPP_OMS.PROMOTION_RULE_OPTION.I18N_KEY
     *
     * @mbggenerated Fri Nov 01 13:52:58 CST 2013
     */
    public void setI18nKey(String i18nKey) {
        this.i18nKey = i18nKey == null ? null : i18nKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PROMOTION_RULE_OPTION.RULE_OPTION_KEY
     *
     * @return the value of ACOAPP_OMS.PROMOTION_RULE_OPTION.RULE_OPTION_KEY
     *
     * @mbggenerated Fri Nov 01 13:52:58 CST 2013
     */
    public String getRuleOptionKey() {
        return ruleOptionKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PROMOTION_RULE_OPTION.RULE_OPTION_KEY
     *
     * @param ruleOptionKey the value for ACOAPP_OMS.PROMOTION_RULE_OPTION.RULE_OPTION_KEY
     *
     * @mbggenerated Fri Nov 01 13:52:58 CST 2013
     */
    public void setRuleOptionKey(String ruleOptionKey) {
        this.ruleOptionKey = ruleOptionKey == null ? null : ruleOptionKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PROMOTION_RULE_OPTION.LAST_MODIFIED
     *
     * @return the value of ACOAPP_OMS.PROMOTION_RULE_OPTION.LAST_MODIFIED
     *
     * @mbggenerated Fri Nov 01 13:52:58 CST 2013
     */
    public Date getLastModified() {
        return lastModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PROMOTION_RULE_OPTION.LAST_MODIFIED
     *
     * @param lastModified the value for ACOAPP_OMS.PROMOTION_RULE_OPTION.LAST_MODIFIED
     *
     * @mbggenerated Fri Nov 01 13:52:58 CST 2013
     */
    public void setLastModified(Date lastModified) {
        this.lastModified = lastModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PROMOTION_RULE_OPTION.MAX_VALUE
     *
     * @return the value of ACOAPP_OMS.PROMOTION_RULE_OPTION.MAX_VALUE
     *
     * @mbggenerated Fri Nov 01 13:52:58 CST 2013
     */
    public Double getMaxValue() {
        return maxValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PROMOTION_RULE_OPTION.MAX_VALUE
     *
     * @param maxValue the value for ACOAPP_OMS.PROMOTION_RULE_OPTION.MAX_VALUE
     *
     * @mbggenerated Fri Nov 01 13:52:58 CST 2013
     */
    public void setMaxValue(Double maxValue) {
        this.maxValue = maxValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PROMOTION_RULE_OPTION.MIN_VALUE
     *
     * @return the value of ACOAPP_OMS.PROMOTION_RULE_OPTION.MIN_VALUE
     *
     * @mbggenerated Fri Nov 01 13:52:58 CST 2013
     */
    public Double getMinValue() {
        return minValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PROMOTION_RULE_OPTION.MIN_VALUE
     *
     * @param minValue the value for ACOAPP_OMS.PROMOTION_RULE_OPTION.MIN_VALUE
     *
     * @mbggenerated Fri Nov 01 13:52:58 CST 2013
     */
    public void setMinValue(Double minValue) {
        this.minValue = minValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PROMOTION_RULE_OPTION.RULE_OPTION_NAME
     *
     * @return the value of ACOAPP_OMS.PROMOTION_RULE_OPTION.RULE_OPTION_NAME
     *
     * @mbggenerated Fri Nov 01 13:52:58 CST 2013
     */
    public String getRuleOptionName() {
        return ruleOptionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PROMOTION_RULE_OPTION.RULE_OPTION_NAME
     *
     * @param ruleOptionName the value for ACOAPP_OMS.PROMOTION_RULE_OPTION.RULE_OPTION_NAME
     *
     * @mbggenerated Fri Nov 01 13:52:58 CST 2013
     */
    public void setRuleOptionName(String ruleOptionName) {
        this.ruleOptionName = ruleOptionName == null ? null : ruleOptionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PROMOTION_RULE_OPTION.RULE_OPTION_OPTIONS
     *
     * @return the value of ACOAPP_OMS.PROMOTION_RULE_OPTION.RULE_OPTION_OPTIONS
     *
     * @mbggenerated Fri Nov 01 13:52:58 CST 2013
     */
    public String getRuleOptionOptions() {
        return ruleOptionOptions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PROMOTION_RULE_OPTION.RULE_OPTION_OPTIONS
     *
     * @param ruleOptionOptions the value for ACOAPP_OMS.PROMOTION_RULE_OPTION.RULE_OPTION_OPTIONS
     *
     * @mbggenerated Fri Nov 01 13:52:58 CST 2013
     */
    public void setRuleOptionOptions(String ruleOptionOptions) {
        this.ruleOptionOptions = ruleOptionOptions == null ? null : ruleOptionOptions.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PROMOTION_RULE_OPTION.IS_REQUIRED
     *
     * @return the value of ACOAPP_OMS.PROMOTION_RULE_OPTION.IS_REQUIRED
     *
     * @mbggenerated Fri Nov 01 13:52:58 CST 2013
     */
    public Short getIsRequired() {
        return isRequired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PROMOTION_RULE_OPTION.IS_REQUIRED
     *
     * @param isRequired the value for ACOAPP_OMS.PROMOTION_RULE_OPTION.IS_REQUIRED
     *
     * @mbggenerated Fri Nov 01 13:52:58 CST 2013
     */
    public void setIsRequired(Short isRequired) {
        this.isRequired = isRequired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PROMOTION_RULE_OPTION.SORT_ID
     *
     * @return the value of ACOAPP_OMS.PROMOTION_RULE_OPTION.SORT_ID
     *
     * @mbggenerated Fri Nov 01 13:52:58 CST 2013
     */
    public BigDecimal getSortId() {
        return sortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PROMOTION_RULE_OPTION.SORT_ID
     *
     * @param sortId the value for ACOAPP_OMS.PROMOTION_RULE_OPTION.SORT_ID
     *
     * @mbggenerated Fri Nov 01 13:52:58 CST 2013
     */
    public void setSortId(BigDecimal sortId) {
        this.sortId = sortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PROMOTION_RULE_OPTION.RULE_OPTION_TYPE
     *
     * @return the value of ACOAPP_OMS.PROMOTION_RULE_OPTION.RULE_OPTION_TYPE
     *
     * @mbggenerated Fri Nov 01 13:52:58 CST 2013
     */
    public String getRuleOptionType() {
        return ruleOptionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PROMOTION_RULE_OPTION.RULE_OPTION_TYPE
     *
     * @param ruleOptionType the value for ACOAPP_OMS.PROMOTION_RULE_OPTION.RULE_OPTION_TYPE
     *
     * @mbggenerated Fri Nov 01 13:52:58 CST 2013
     */
    public void setRuleOptionType(String ruleOptionType) {
        this.ruleOptionType = ruleOptionType == null ? null : ruleOptionType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PROMOTION_RULE_OPTION.UPDATE_BY
     *
     * @return the value of ACOAPP_OMS.PROMOTION_RULE_OPTION.UPDATE_BY
     *
     * @mbggenerated Fri Nov 01 13:52:58 CST 2013
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PROMOTION_RULE_OPTION.UPDATE_BY
     *
     * @param updateBy the value for ACOAPP_OMS.PROMOTION_RULE_OPTION.UPDATE_BY
     *
     * @mbggenerated Fri Nov 01 13:52:58 CST 2013
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PROMOTION_RULE_OPTION.RULE_ID
     *
     * @return the value of ACOAPP_OMS.PROMOTION_RULE_OPTION.RULE_ID
     *
     * @mbggenerated Fri Nov 01 13:52:58 CST 2013
     */
    public BigDecimal getRuleId() {
        return ruleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PROMOTION_RULE_OPTION.RULE_ID
     *
     * @param ruleId the value for ACOAPP_OMS.PROMOTION_RULE_OPTION.RULE_ID
     *
     * @mbggenerated Fri Nov 01 13:52:58 CST 2013
     */
    public void setRuleId(BigDecimal ruleId) {
        this.ruleId = ruleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PROMOTION_RULE_OPTION.RULE_OPTION_TYPE_SIZE
     *
     * @return the value of ACOAPP_OMS.PROMOTION_RULE_OPTION.RULE_OPTION_TYPE_SIZE
     *
     * @mbggenerated Fri Nov 01 13:52:58 CST 2013
     */
    public Long getRuleOptionTypeSize() {
        return ruleOptionTypeSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PROMOTION_RULE_OPTION.RULE_OPTION_TYPE_SIZE
     *
     * @param ruleOptionTypeSize the value for ACOAPP_OMS.PROMOTION_RULE_OPTION.RULE_OPTION_TYPE_SIZE
     *
     * @mbggenerated Fri Nov 01 13:52:58 CST 2013
     */
    public void setRuleOptionTypeSize(Long ruleOptionTypeSize) {
        this.ruleOptionTypeSize = ruleOptionTypeSize;
    }
}