package com.chinadrtv.model.oms;

import java.math.BigDecimal;
import java.util.Date;

public class PromotionRuleResult {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PROMOTION_RULE_RESULT.PROMOTION_RESULT_ID
     *
     * @mbggenerated Fri Nov 01 13:40:31 CST 2013
     */
    private BigDecimal promotionResultId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PROMOTION_RULE_RESULT.DISCRIMINATOR
     *
     * @mbggenerated Fri Nov 01 13:40:31 CST 2013
     */
    private String discriminator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PROMOTION_RULE_RESULT.CREATED_BY
     *
     * @mbggenerated Fri Nov 01 13:40:31 CST 2013
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PROMOTION_RULE_RESULT.DATE_ADDED
     *
     * @mbggenerated Fri Nov 01 13:40:31 CST 2013
     */
    private Date dateAdded;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PROMOTION_RULE_RESULT.ORDER_ID
     *
     * @mbggenerated Fri Nov 01 13:40:31 CST 2013
     */
    private BigDecimal orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PROMOTION_RULE_RESULT.PRE_TRADE_ID
     *
     * @mbggenerated Fri Nov 01 13:40:31 CST 2013
     */
    private BigDecimal preTradeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PROMOTION_RULE_RESULT.RESULT_DESCRIPTION
     *
     * @mbggenerated Fri Nov 01 13:40:31 CST 2013
     */
    private String resultDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PROMOTION_RULE_RESULT.PROMOTION_ID
     *
     * @mbggenerated Fri Nov 01 13:40:31 CST 2013
     */
    private BigDecimal promotionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PROMOTION_RULE_RESULT.OPTION_PRODUCTS
     *
     * @mbggenerated Fri Nov 01 13:40:31 CST 2013
     */
    private String optionProducts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PROMOTION_RULE_RESULT.PRODUCT_ID
     *
     * @mbggenerated Fri Nov 01 13:40:31 CST 2013
     */
    private String productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PROMOTION_RULE_RESULT.PRODUCT_NAME
     *
     * @mbggenerated Fri Nov 01 13:40:31 CST 2013
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PROMOTION_RULE_RESULT.SKU_CODE
     *
     * @mbggenerated Fri Nov 01 13:40:31 CST 2013
     */
    private String skuCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PROMOTION_RULE_RESULT.UNIT_NUMBER
     *
     * @mbggenerated Fri Nov 01 13:40:31 CST 2013
     */
    private Long unitNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PROMOTION_RULE_RESULT.PID
     *
     * @mbggenerated Fri Nov 01 13:40:31 CST 2013
     */
    private BigDecimal pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PROMOTION_RULE_RESULT.PRODUCT_GROUP
     *
     * @mbggenerated Fri Nov 01 13:40:31 CST 2013
     */
    private Long productGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PROMOTION_RULE_RESULT.DISCOUNT
     *
     * @mbggenerated Fri Nov 01 13:40:31 CST 2013
     */
    private Double discount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PROMOTION_RULE_RESULT.ISPER
     *
     * @mbggenerated Fri Nov 01 13:40:31 CST 2013
     */
    private Short isper;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PROMOTION_RULE_RESULT.PROMOTION_RESULT_ID
     *
     * @return the value of ACOAPP_OMS.PROMOTION_RULE_RESULT.PROMOTION_RESULT_ID
     *
     * @mbggenerated Fri Nov 01 13:40:31 CST 2013
     */
    public BigDecimal getPromotionResultId() {
        return promotionResultId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PROMOTION_RULE_RESULT.PROMOTION_RESULT_ID
     *
     * @param promotionResultId the value for ACOAPP_OMS.PROMOTION_RULE_RESULT.PROMOTION_RESULT_ID
     *
     * @mbggenerated Fri Nov 01 13:40:31 CST 2013
     */
    public void setPromotionResultId(BigDecimal promotionResultId) {
        this.promotionResultId = promotionResultId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PROMOTION_RULE_RESULT.DISCRIMINATOR
     *
     * @return the value of ACOAPP_OMS.PROMOTION_RULE_RESULT.DISCRIMINATOR
     *
     * @mbggenerated Fri Nov 01 13:40:31 CST 2013
     */
    public String getDiscriminator() {
        return discriminator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PROMOTION_RULE_RESULT.DISCRIMINATOR
     *
     * @param discriminator the value for ACOAPP_OMS.PROMOTION_RULE_RESULT.DISCRIMINATOR
     *
     * @mbggenerated Fri Nov 01 13:40:31 CST 2013
     */
    public void setDiscriminator(String discriminator) {
        this.discriminator = discriminator == null ? null : discriminator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PROMOTION_RULE_RESULT.CREATED_BY
     *
     * @return the value of ACOAPP_OMS.PROMOTION_RULE_RESULT.CREATED_BY
     *
     * @mbggenerated Fri Nov 01 13:40:31 CST 2013
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PROMOTION_RULE_RESULT.CREATED_BY
     *
     * @param createdBy the value for ACOAPP_OMS.PROMOTION_RULE_RESULT.CREATED_BY
     *
     * @mbggenerated Fri Nov 01 13:40:31 CST 2013
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PROMOTION_RULE_RESULT.DATE_ADDED
     *
     * @return the value of ACOAPP_OMS.PROMOTION_RULE_RESULT.DATE_ADDED
     *
     * @mbggenerated Fri Nov 01 13:40:31 CST 2013
     */
    public Date getDateAdded() {
        return dateAdded;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PROMOTION_RULE_RESULT.DATE_ADDED
     *
     * @param dateAdded the value for ACOAPP_OMS.PROMOTION_RULE_RESULT.DATE_ADDED
     *
     * @mbggenerated Fri Nov 01 13:40:31 CST 2013
     */
    public void setDateAdded(Date dateAdded) {
        this.dateAdded = dateAdded;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PROMOTION_RULE_RESULT.ORDER_ID
     *
     * @return the value of ACOAPP_OMS.PROMOTION_RULE_RESULT.ORDER_ID
     *
     * @mbggenerated Fri Nov 01 13:40:31 CST 2013
     */
    public BigDecimal getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PROMOTION_RULE_RESULT.ORDER_ID
     *
     * @param orderId the value for ACOAPP_OMS.PROMOTION_RULE_RESULT.ORDER_ID
     *
     * @mbggenerated Fri Nov 01 13:40:31 CST 2013
     */
    public void setOrderId(BigDecimal orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PROMOTION_RULE_RESULT.PRE_TRADE_ID
     *
     * @return the value of ACOAPP_OMS.PROMOTION_RULE_RESULT.PRE_TRADE_ID
     *
     * @mbggenerated Fri Nov 01 13:40:31 CST 2013
     */
    public BigDecimal getPreTradeId() {
        return preTradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PROMOTION_RULE_RESULT.PRE_TRADE_ID
     *
     * @param preTradeId the value for ACOAPP_OMS.PROMOTION_RULE_RESULT.PRE_TRADE_ID
     *
     * @mbggenerated Fri Nov 01 13:40:31 CST 2013
     */
    public void setPreTradeId(BigDecimal preTradeId) {
        this.preTradeId = preTradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PROMOTION_RULE_RESULT.RESULT_DESCRIPTION
     *
     * @return the value of ACOAPP_OMS.PROMOTION_RULE_RESULT.RESULT_DESCRIPTION
     *
     * @mbggenerated Fri Nov 01 13:40:31 CST 2013
     */
    public String getResultDescription() {
        return resultDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PROMOTION_RULE_RESULT.RESULT_DESCRIPTION
     *
     * @param resultDescription the value for ACOAPP_OMS.PROMOTION_RULE_RESULT.RESULT_DESCRIPTION
     *
     * @mbggenerated Fri Nov 01 13:40:31 CST 2013
     */
    public void setResultDescription(String resultDescription) {
        this.resultDescription = resultDescription == null ? null : resultDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PROMOTION_RULE_RESULT.PROMOTION_ID
     *
     * @return the value of ACOAPP_OMS.PROMOTION_RULE_RESULT.PROMOTION_ID
     *
     * @mbggenerated Fri Nov 01 13:40:31 CST 2013
     */
    public BigDecimal getPromotionId() {
        return promotionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PROMOTION_RULE_RESULT.PROMOTION_ID
     *
     * @param promotionId the value for ACOAPP_OMS.PROMOTION_RULE_RESULT.PROMOTION_ID
     *
     * @mbggenerated Fri Nov 01 13:40:31 CST 2013
     */
    public void setPromotionId(BigDecimal promotionId) {
        this.promotionId = promotionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PROMOTION_RULE_RESULT.OPTION_PRODUCTS
     *
     * @return the value of ACOAPP_OMS.PROMOTION_RULE_RESULT.OPTION_PRODUCTS
     *
     * @mbggenerated Fri Nov 01 13:40:31 CST 2013
     */
    public String getOptionProducts() {
        return optionProducts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PROMOTION_RULE_RESULT.OPTION_PRODUCTS
     *
     * @param optionProducts the value for ACOAPP_OMS.PROMOTION_RULE_RESULT.OPTION_PRODUCTS
     *
     * @mbggenerated Fri Nov 01 13:40:31 CST 2013
     */
    public void setOptionProducts(String optionProducts) {
        this.optionProducts = optionProducts == null ? null : optionProducts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PROMOTION_RULE_RESULT.PRODUCT_ID
     *
     * @return the value of ACOAPP_OMS.PROMOTION_RULE_RESULT.PRODUCT_ID
     *
     * @mbggenerated Fri Nov 01 13:40:31 CST 2013
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PROMOTION_RULE_RESULT.PRODUCT_ID
     *
     * @param productId the value for ACOAPP_OMS.PROMOTION_RULE_RESULT.PRODUCT_ID
     *
     * @mbggenerated Fri Nov 01 13:40:31 CST 2013
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PROMOTION_RULE_RESULT.PRODUCT_NAME
     *
     * @return the value of ACOAPP_OMS.PROMOTION_RULE_RESULT.PRODUCT_NAME
     *
     * @mbggenerated Fri Nov 01 13:40:31 CST 2013
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PROMOTION_RULE_RESULT.PRODUCT_NAME
     *
     * @param productName the value for ACOAPP_OMS.PROMOTION_RULE_RESULT.PRODUCT_NAME
     *
     * @mbggenerated Fri Nov 01 13:40:31 CST 2013
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PROMOTION_RULE_RESULT.SKU_CODE
     *
     * @return the value of ACOAPP_OMS.PROMOTION_RULE_RESULT.SKU_CODE
     *
     * @mbggenerated Fri Nov 01 13:40:31 CST 2013
     */
    public String getSkuCode() {
        return skuCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PROMOTION_RULE_RESULT.SKU_CODE
     *
     * @param skuCode the value for ACOAPP_OMS.PROMOTION_RULE_RESULT.SKU_CODE
     *
     * @mbggenerated Fri Nov 01 13:40:31 CST 2013
     */
    public void setSkuCode(String skuCode) {
        this.skuCode = skuCode == null ? null : skuCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PROMOTION_RULE_RESULT.UNIT_NUMBER
     *
     * @return the value of ACOAPP_OMS.PROMOTION_RULE_RESULT.UNIT_NUMBER
     *
     * @mbggenerated Fri Nov 01 13:40:31 CST 2013
     */
    public Long getUnitNumber() {
        return unitNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PROMOTION_RULE_RESULT.UNIT_NUMBER
     *
     * @param unitNumber the value for ACOAPP_OMS.PROMOTION_RULE_RESULT.UNIT_NUMBER
     *
     * @mbggenerated Fri Nov 01 13:40:31 CST 2013
     */
    public void setUnitNumber(Long unitNumber) {
        this.unitNumber = unitNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PROMOTION_RULE_RESULT.PID
     *
     * @return the value of ACOAPP_OMS.PROMOTION_RULE_RESULT.PID
     *
     * @mbggenerated Fri Nov 01 13:40:31 CST 2013
     */
    public BigDecimal getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PROMOTION_RULE_RESULT.PID
     *
     * @param pid the value for ACOAPP_OMS.PROMOTION_RULE_RESULT.PID
     *
     * @mbggenerated Fri Nov 01 13:40:31 CST 2013
     */
    public void setPid(BigDecimal pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PROMOTION_RULE_RESULT.PRODUCT_GROUP
     *
     * @return the value of ACOAPP_OMS.PROMOTION_RULE_RESULT.PRODUCT_GROUP
     *
     * @mbggenerated Fri Nov 01 13:40:31 CST 2013
     */
    public Long getProductGroup() {
        return productGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PROMOTION_RULE_RESULT.PRODUCT_GROUP
     *
     * @param productGroup the value for ACOAPP_OMS.PROMOTION_RULE_RESULT.PRODUCT_GROUP
     *
     * @mbggenerated Fri Nov 01 13:40:31 CST 2013
     */
    public void setProductGroup(Long productGroup) {
        this.productGroup = productGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PROMOTION_RULE_RESULT.DISCOUNT
     *
     * @return the value of ACOAPP_OMS.PROMOTION_RULE_RESULT.DISCOUNT
     *
     * @mbggenerated Fri Nov 01 13:40:31 CST 2013
     */
    public Double getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PROMOTION_RULE_RESULT.DISCOUNT
     *
     * @param discount the value for ACOAPP_OMS.PROMOTION_RULE_RESULT.DISCOUNT
     *
     * @mbggenerated Fri Nov 01 13:40:31 CST 2013
     */
    public void setDiscount(Double discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PROMOTION_RULE_RESULT.ISPER
     *
     * @return the value of ACOAPP_OMS.PROMOTION_RULE_RESULT.ISPER
     *
     * @mbggenerated Fri Nov 01 13:40:31 CST 2013
     */
    public Short getIsper() {
        return isper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PROMOTION_RULE_RESULT.ISPER
     *
     * @param isper the value for ACOAPP_OMS.PROMOTION_RULE_RESULT.ISPER
     *
     * @mbggenerated Fri Nov 01 13:40:31 CST 2013
     */
    public void setIsper(Short isper) {
        this.isper = isper;
    }
}