package com.chinadrtv.model.oms;

import java.math.BigDecimal;
import java.util.Date;

public class Promotion {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PROMOTION.PROMOTIONID
     *
     * @mbggenerated Fri Nov 01 13:38:07 CST 2013
     */
    private String promotionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PROMOTION.PRODID
     *
     * @mbggenerated Fri Nov 01 13:38:07 CST 2013
     */
    private String prodid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PROMOTION.DSC
     *
     * @mbggenerated Fri Nov 01 13:38:07 CST 2013
     */
    private String dsc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PROMOTION.DNIS
     *
     * @mbggenerated Fri Nov 01 13:38:07 CST 2013
     */
    private String dnis;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PROMOTION.STATUS
     *
     * @mbggenerated Fri Nov 01 13:38:07 CST 2013
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PROMOTION.MEDIAPRODUCTID
     *
     * @mbggenerated Fri Nov 01 13:38:07 CST 2013
     */
    private String mediaproductid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PROMOTION.STATDATA
     *
     * @mbggenerated Fri Nov 01 13:38:07 CST 2013
     */
    private Date statdata;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PROMOTION.PRICE
     *
     * @mbggenerated Fri Nov 01 13:38:07 CST 2013
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PROMOTION.FDURATION
     *
     * @mbggenerated Fri Nov 01 13:38:07 CST 2013
     */
    private BigDecimal fduration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PROMOTION.MONITOR
     *
     * @mbggenerated Fri Nov 01 13:38:07 CST 2013
     */
    private String monitor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PROMOTION.SALESPROMOTION
     *
     * @mbggenerated Fri Nov 01 13:38:07 CST 2013
     */
    private String salespromotion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PROMOTION.MPVERSIONID
     *
     * @mbggenerated Fri Nov 01 13:38:07 CST 2013
     */
    private String mpversionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PROMOTION.CODE
     *
     * @mbggenerated Fri Nov 01 13:38:07 CST 2013
     */
    private String code;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PROMOTION.PROMOTIONID
     *
     * @return the value of ACOAPP_OMS.PROMOTION.PROMOTIONID
     *
     * @mbggenerated Fri Nov 01 13:38:07 CST 2013
     */
    public String getPromotionid() {
        return promotionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PROMOTION.PROMOTIONID
     *
     * @param promotionid the value for ACOAPP_OMS.PROMOTION.PROMOTIONID
     *
     * @mbggenerated Fri Nov 01 13:38:07 CST 2013
     */
    public void setPromotionid(String promotionid) {
        this.promotionid = promotionid == null ? null : promotionid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PROMOTION.PRODID
     *
     * @return the value of ACOAPP_OMS.PROMOTION.PRODID
     *
     * @mbggenerated Fri Nov 01 13:38:07 CST 2013
     */
    public String getProdid() {
        return prodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PROMOTION.PRODID
     *
     * @param prodid the value for ACOAPP_OMS.PROMOTION.PRODID
     *
     * @mbggenerated Fri Nov 01 13:38:07 CST 2013
     */
    public void setProdid(String prodid) {
        this.prodid = prodid == null ? null : prodid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PROMOTION.DSC
     *
     * @return the value of ACOAPP_OMS.PROMOTION.DSC
     *
     * @mbggenerated Fri Nov 01 13:38:07 CST 2013
     */
    public String getDsc() {
        return dsc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PROMOTION.DSC
     *
     * @param dsc the value for ACOAPP_OMS.PROMOTION.DSC
     *
     * @mbggenerated Fri Nov 01 13:38:07 CST 2013
     */
    public void setDsc(String dsc) {
        this.dsc = dsc == null ? null : dsc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PROMOTION.DNIS
     *
     * @return the value of ACOAPP_OMS.PROMOTION.DNIS
     *
     * @mbggenerated Fri Nov 01 13:38:07 CST 2013
     */
    public String getDnis() {
        return dnis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PROMOTION.DNIS
     *
     * @param dnis the value for ACOAPP_OMS.PROMOTION.DNIS
     *
     * @mbggenerated Fri Nov 01 13:38:07 CST 2013
     */
    public void setDnis(String dnis) {
        this.dnis = dnis == null ? null : dnis.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PROMOTION.STATUS
     *
     * @return the value of ACOAPP_OMS.PROMOTION.STATUS
     *
     * @mbggenerated Fri Nov 01 13:38:07 CST 2013
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PROMOTION.STATUS
     *
     * @param status the value for ACOAPP_OMS.PROMOTION.STATUS
     *
     * @mbggenerated Fri Nov 01 13:38:07 CST 2013
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PROMOTION.MEDIAPRODUCTID
     *
     * @return the value of ACOAPP_OMS.PROMOTION.MEDIAPRODUCTID
     *
     * @mbggenerated Fri Nov 01 13:38:07 CST 2013
     */
    public String getMediaproductid() {
        return mediaproductid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PROMOTION.MEDIAPRODUCTID
     *
     * @param mediaproductid the value for ACOAPP_OMS.PROMOTION.MEDIAPRODUCTID
     *
     * @mbggenerated Fri Nov 01 13:38:07 CST 2013
     */
    public void setMediaproductid(String mediaproductid) {
        this.mediaproductid = mediaproductid == null ? null : mediaproductid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PROMOTION.STATDATA
     *
     * @return the value of ACOAPP_OMS.PROMOTION.STATDATA
     *
     * @mbggenerated Fri Nov 01 13:38:07 CST 2013
     */
    public Date getStatdata() {
        return statdata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PROMOTION.STATDATA
     *
     * @param statdata the value for ACOAPP_OMS.PROMOTION.STATDATA
     *
     * @mbggenerated Fri Nov 01 13:38:07 CST 2013
     */
    public void setStatdata(Date statdata) {
        this.statdata = statdata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PROMOTION.PRICE
     *
     * @return the value of ACOAPP_OMS.PROMOTION.PRICE
     *
     * @mbggenerated Fri Nov 01 13:38:07 CST 2013
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PROMOTION.PRICE
     *
     * @param price the value for ACOAPP_OMS.PROMOTION.PRICE
     *
     * @mbggenerated Fri Nov 01 13:38:07 CST 2013
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PROMOTION.FDURATION
     *
     * @return the value of ACOAPP_OMS.PROMOTION.FDURATION
     *
     * @mbggenerated Fri Nov 01 13:38:07 CST 2013
     */
    public BigDecimal getFduration() {
        return fduration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PROMOTION.FDURATION
     *
     * @param fduration the value for ACOAPP_OMS.PROMOTION.FDURATION
     *
     * @mbggenerated Fri Nov 01 13:38:07 CST 2013
     */
    public void setFduration(BigDecimal fduration) {
        this.fduration = fduration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PROMOTION.MONITOR
     *
     * @return the value of ACOAPP_OMS.PROMOTION.MONITOR
     *
     * @mbggenerated Fri Nov 01 13:38:07 CST 2013
     */
    public String getMonitor() {
        return monitor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PROMOTION.MONITOR
     *
     * @param monitor the value for ACOAPP_OMS.PROMOTION.MONITOR
     *
     * @mbggenerated Fri Nov 01 13:38:07 CST 2013
     */
    public void setMonitor(String monitor) {
        this.monitor = monitor == null ? null : monitor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PROMOTION.SALESPROMOTION
     *
     * @return the value of ACOAPP_OMS.PROMOTION.SALESPROMOTION
     *
     * @mbggenerated Fri Nov 01 13:38:07 CST 2013
     */
    public String getSalespromotion() {
        return salespromotion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PROMOTION.SALESPROMOTION
     *
     * @param salespromotion the value for ACOAPP_OMS.PROMOTION.SALESPROMOTION
     *
     * @mbggenerated Fri Nov 01 13:38:07 CST 2013
     */
    public void setSalespromotion(String salespromotion) {
        this.salespromotion = salespromotion == null ? null : salespromotion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PROMOTION.MPVERSIONID
     *
     * @return the value of ACOAPP_OMS.PROMOTION.MPVERSIONID
     *
     * @mbggenerated Fri Nov 01 13:38:07 CST 2013
     */
    public String getMpversionid() {
        return mpversionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PROMOTION.MPVERSIONID
     *
     * @param mpversionid the value for ACOAPP_OMS.PROMOTION.MPVERSIONID
     *
     * @mbggenerated Fri Nov 01 13:38:07 CST 2013
     */
    public void setMpversionid(String mpversionid) {
        this.mpversionid = mpversionid == null ? null : mpversionid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PROMOTION.CODE
     *
     * @return the value of ACOAPP_OMS.PROMOTION.CODE
     *
     * @mbggenerated Fri Nov 01 13:38:07 CST 2013
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PROMOTION.CODE
     *
     * @param code the value for ACOAPP_OMS.PROMOTION.CODE
     *
     * @mbggenerated Fri Nov 01 13:38:07 CST 2013
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }
}