package com.chinadrtv.model.oms;

public class ProvinceMapping {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PROVINCE_MAPPING.PROVINCEID
     *
     * @mbggenerated Wed Oct 30 13:34:08 CST 2013
     */
    private Integer provinceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PROVINCE_MAPPING.PROVINCENAME
     *
     * @mbggenerated Wed Oct 30 13:34:08 CST 2013
     */
    private String provincename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PROVINCE_MAPPING.MAPPING_PROVINCEID
     *
     * @mbggenerated Wed Oct 30 13:34:08 CST 2013
     */
    private String mappingProvinceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.PROVINCE_MAPPING.REMARK
     *
     * @mbggenerated Wed Oct 30 13:34:08 CST 2013
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PROVINCE_MAPPING.PROVINCEID
     *
     * @return the value of ACOAPP_OMS.PROVINCE_MAPPING.PROVINCEID
     *
     * @mbggenerated Wed Oct 30 13:34:08 CST 2013
     */
    public Integer getProvinceid() {
        return provinceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PROVINCE_MAPPING.PROVINCEID
     *
     * @param provinceid the value for ACOAPP_OMS.PROVINCE_MAPPING.PROVINCEID
     *
     * @mbggenerated Wed Oct 30 13:34:08 CST 2013
     */
    public void setProvinceid(Integer provinceid) {
        this.provinceid = provinceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PROVINCE_MAPPING.PROVINCENAME
     *
     * @return the value of ACOAPP_OMS.PROVINCE_MAPPING.PROVINCENAME
     *
     * @mbggenerated Wed Oct 30 13:34:08 CST 2013
     */
    public String getProvincename() {
        return provincename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PROVINCE_MAPPING.PROVINCENAME
     *
     * @param provincename the value for ACOAPP_OMS.PROVINCE_MAPPING.PROVINCENAME
     *
     * @mbggenerated Wed Oct 30 13:34:08 CST 2013
     */
    public void setProvincename(String provincename) {
        this.provincename = provincename == null ? null : provincename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PROVINCE_MAPPING.MAPPING_PROVINCEID
     *
     * @return the value of ACOAPP_OMS.PROVINCE_MAPPING.MAPPING_PROVINCEID
     *
     * @mbggenerated Wed Oct 30 13:34:08 CST 2013
     */
    public String getMappingProvinceid() {
        return mappingProvinceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PROVINCE_MAPPING.MAPPING_PROVINCEID
     *
     * @param mappingProvinceid the value for ACOAPP_OMS.PROVINCE_MAPPING.MAPPING_PROVINCEID
     *
     * @mbggenerated Wed Oct 30 13:34:08 CST 2013
     */
    public void setMappingProvinceid(String mappingProvinceid) {
        this.mappingProvinceid = mappingProvinceid == null ? null : mappingProvinceid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.PROVINCE_MAPPING.REMARK
     *
     * @return the value of ACOAPP_OMS.PROVINCE_MAPPING.REMARK
     *
     * @mbggenerated Wed Oct 30 13:34:08 CST 2013
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.PROVINCE_MAPPING.REMARK
     *
     * @param remark the value for ACOAPP_OMS.PROVINCE_MAPPING.REMARK
     *
     * @mbggenerated Wed Oct 30 13:34:08 CST 2013
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}