package com.chinadrtv.model.oms;

import java.math.BigDecimal;
import java.util.Date;

public class ShipmentHeader {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.SHIPMENT_HEADER.ID
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.SHIPMENT_HEADER.SHIPMENT_ID
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    private String shipmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.SHIPMENT_HEADER.ACCOUNT_TYPE
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    private String accountType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.SHIPMENT_HEADER.ORDER_REF_HIS_ID
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    private Long orderRefHisId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.SHIPMENT_HEADER.ORDER_ID
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.SHIPMENT_HEADER.REVISION
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    private Long revision;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.SHIPMENT_HEADER.MAIL_ID
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    private String mailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.SHIPMENT_HEADER.ENTITY_ID
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    private String entityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.SHIPMENT_HEADER.CRUSR
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    private String crusr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.SHIPMENT_HEADER.MDUSR
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    private String mdusr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.SHIPMENT_HEADER.MDDT
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    private Date mddt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.SHIPMENT_HEADER.ACCOUNT_STATUS_ID
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    private String accountStatusId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.SHIPMENT_HEADER.ACCOUNT_STATUS_REMARK
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    private String accountStatusRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.SHIPMENT_HEADER.CRDT
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    private Date crdt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.SHIPMENT_HEADER.SENDDT
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    private Date senddt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.SHIPMENT_HEADER.FBDT
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    private Date fbdt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.SHIPMENT_HEADER.OUTDT
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    private Date outdt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.SHIPMENT_HEADER.ACCDT
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    private Date accdt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.SHIPMENT_HEADER.LOGISTICS_STATUS_ID
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    private String logisticsStatusId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.SHIPMENT_HEADER.LOGISTICS_STATUS_REMARK
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    private String logisticsStatusRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.SHIPMENT_HEADER.RFOUTDAT
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    private Date rfoutdat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.SHIPMENT_HEADER.ITEM_FLAG
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    private String itemFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.SHIPMENT_HEADER.OWNER
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    private String owner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.SHIPMENT_HEADER.VOLUME
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    private String volume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.SHIPMENT_HEADER.WEIGHT
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    private String weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.SHIPMENT_HEADER.WAREHOUSE_ID
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    private String warehouseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.SHIPMENT_HEADER.ORDER_REF_REVISION
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    private Long orderRefRevision;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.SHIPMENT_HEADER.ASSOCIATED_ID
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    private Long associatedId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.SHIPMENT_HEADER.PROD_PRICE
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    private BigDecimal prodPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.SHIPMENT_HEADER.MAIL_PRICE
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    private BigDecimal mailPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.SHIPMENT_HEADER.POST_FEE1
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    private BigDecimal postFee1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.SHIPMENT_HEADER.POST_FEE2
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    private BigDecimal postFee2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.SHIPMENT_HEADER.CLEAR_FEE
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    private BigDecimal clearFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.SHIPMENT_HEADER.RECONCIL_FLAG
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    private Short reconcilFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.SHIPMENT_HEADER.RECONCIL_USER
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    private String reconcilUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.SHIPMENT_HEADER.RECONCIL_DATE
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    private Date reconcilDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.SHIPMENT_HEADER.CLEAR_POST_FEE
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    private BigDecimal clearPostFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.SHIPMENT_HEADER.ACCOUNT
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACOAPP_OMS.SHIPMENT_HEADER.POST_FEE3
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    private BigDecimal postFee3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.SHIPMENT_HEADER.ID
     *
     * @return the value of ACOAPP_OMS.SHIPMENT_HEADER.ID
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.SHIPMENT_HEADER.ID
     *
     * @param id the value for ACOAPP_OMS.SHIPMENT_HEADER.ID
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.SHIPMENT_HEADER.SHIPMENT_ID
     *
     * @return the value of ACOAPP_OMS.SHIPMENT_HEADER.SHIPMENT_ID
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    public String getShipmentId() {
        return shipmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.SHIPMENT_HEADER.SHIPMENT_ID
     *
     * @param shipmentId the value for ACOAPP_OMS.SHIPMENT_HEADER.SHIPMENT_ID
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    public void setShipmentId(String shipmentId) {
        this.shipmentId = shipmentId == null ? null : shipmentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.SHIPMENT_HEADER.ACCOUNT_TYPE
     *
     * @return the value of ACOAPP_OMS.SHIPMENT_HEADER.ACCOUNT_TYPE
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    public String getAccountType() {
        return accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.SHIPMENT_HEADER.ACCOUNT_TYPE
     *
     * @param accountType the value for ACOAPP_OMS.SHIPMENT_HEADER.ACCOUNT_TYPE
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    public void setAccountType(String accountType) {
        this.accountType = accountType == null ? null : accountType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.SHIPMENT_HEADER.ORDER_REF_HIS_ID
     *
     * @return the value of ACOAPP_OMS.SHIPMENT_HEADER.ORDER_REF_HIS_ID
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    public Long getOrderRefHisId() {
        return orderRefHisId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.SHIPMENT_HEADER.ORDER_REF_HIS_ID
     *
     * @param orderRefHisId the value for ACOAPP_OMS.SHIPMENT_HEADER.ORDER_REF_HIS_ID
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    public void setOrderRefHisId(Long orderRefHisId) {
        this.orderRefHisId = orderRefHisId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.SHIPMENT_HEADER.ORDER_ID
     *
     * @return the value of ACOAPP_OMS.SHIPMENT_HEADER.ORDER_ID
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.SHIPMENT_HEADER.ORDER_ID
     *
     * @param orderId the value for ACOAPP_OMS.SHIPMENT_HEADER.ORDER_ID
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.SHIPMENT_HEADER.REVISION
     *
     * @return the value of ACOAPP_OMS.SHIPMENT_HEADER.REVISION
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    public Long getRevision() {
        return revision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.SHIPMENT_HEADER.REVISION
     *
     * @param revision the value for ACOAPP_OMS.SHIPMENT_HEADER.REVISION
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    public void setRevision(Long revision) {
        this.revision = revision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.SHIPMENT_HEADER.MAIL_ID
     *
     * @return the value of ACOAPP_OMS.SHIPMENT_HEADER.MAIL_ID
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    public String getMailId() {
        return mailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.SHIPMENT_HEADER.MAIL_ID
     *
     * @param mailId the value for ACOAPP_OMS.SHIPMENT_HEADER.MAIL_ID
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    public void setMailId(String mailId) {
        this.mailId = mailId == null ? null : mailId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.SHIPMENT_HEADER.ENTITY_ID
     *
     * @return the value of ACOAPP_OMS.SHIPMENT_HEADER.ENTITY_ID
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    public String getEntityId() {
        return entityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.SHIPMENT_HEADER.ENTITY_ID
     *
     * @param entityId the value for ACOAPP_OMS.SHIPMENT_HEADER.ENTITY_ID
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    public void setEntityId(String entityId) {
        this.entityId = entityId == null ? null : entityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.SHIPMENT_HEADER.CRUSR
     *
     * @return the value of ACOAPP_OMS.SHIPMENT_HEADER.CRUSR
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    public String getCrusr() {
        return crusr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.SHIPMENT_HEADER.CRUSR
     *
     * @param crusr the value for ACOAPP_OMS.SHIPMENT_HEADER.CRUSR
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    public void setCrusr(String crusr) {
        this.crusr = crusr == null ? null : crusr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.SHIPMENT_HEADER.MDUSR
     *
     * @return the value of ACOAPP_OMS.SHIPMENT_HEADER.MDUSR
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    public String getMdusr() {
        return mdusr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.SHIPMENT_HEADER.MDUSR
     *
     * @param mdusr the value for ACOAPP_OMS.SHIPMENT_HEADER.MDUSR
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    public void setMdusr(String mdusr) {
        this.mdusr = mdusr == null ? null : mdusr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.SHIPMENT_HEADER.MDDT
     *
     * @return the value of ACOAPP_OMS.SHIPMENT_HEADER.MDDT
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    public Date getMddt() {
        return mddt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.SHIPMENT_HEADER.MDDT
     *
     * @param mddt the value for ACOAPP_OMS.SHIPMENT_HEADER.MDDT
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    public void setMddt(Date mddt) {
        this.mddt = mddt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.SHIPMENT_HEADER.ACCOUNT_STATUS_ID
     *
     * @return the value of ACOAPP_OMS.SHIPMENT_HEADER.ACCOUNT_STATUS_ID
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    public String getAccountStatusId() {
        return accountStatusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.SHIPMENT_HEADER.ACCOUNT_STATUS_ID
     *
     * @param accountStatusId the value for ACOAPP_OMS.SHIPMENT_HEADER.ACCOUNT_STATUS_ID
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    public void setAccountStatusId(String accountStatusId) {
        this.accountStatusId = accountStatusId == null ? null : accountStatusId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.SHIPMENT_HEADER.ACCOUNT_STATUS_REMARK
     *
     * @return the value of ACOAPP_OMS.SHIPMENT_HEADER.ACCOUNT_STATUS_REMARK
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    public String getAccountStatusRemark() {
        return accountStatusRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.SHIPMENT_HEADER.ACCOUNT_STATUS_REMARK
     *
     * @param accountStatusRemark the value for ACOAPP_OMS.SHIPMENT_HEADER.ACCOUNT_STATUS_REMARK
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    public void setAccountStatusRemark(String accountStatusRemark) {
        this.accountStatusRemark = accountStatusRemark == null ? null : accountStatusRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.SHIPMENT_HEADER.CRDT
     *
     * @return the value of ACOAPP_OMS.SHIPMENT_HEADER.CRDT
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    public Date getCrdt() {
        return crdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.SHIPMENT_HEADER.CRDT
     *
     * @param crdt the value for ACOAPP_OMS.SHIPMENT_HEADER.CRDT
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    public void setCrdt(Date crdt) {
        this.crdt = crdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.SHIPMENT_HEADER.SENDDT
     *
     * @return the value of ACOAPP_OMS.SHIPMENT_HEADER.SENDDT
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    public Date getSenddt() {
        return senddt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.SHIPMENT_HEADER.SENDDT
     *
     * @param senddt the value for ACOAPP_OMS.SHIPMENT_HEADER.SENDDT
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    public void setSenddt(Date senddt) {
        this.senddt = senddt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.SHIPMENT_HEADER.FBDT
     *
     * @return the value of ACOAPP_OMS.SHIPMENT_HEADER.FBDT
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    public Date getFbdt() {
        return fbdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.SHIPMENT_HEADER.FBDT
     *
     * @param fbdt the value for ACOAPP_OMS.SHIPMENT_HEADER.FBDT
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    public void setFbdt(Date fbdt) {
        this.fbdt = fbdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.SHIPMENT_HEADER.OUTDT
     *
     * @return the value of ACOAPP_OMS.SHIPMENT_HEADER.OUTDT
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    public Date getOutdt() {
        return outdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.SHIPMENT_HEADER.OUTDT
     *
     * @param outdt the value for ACOAPP_OMS.SHIPMENT_HEADER.OUTDT
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    public void setOutdt(Date outdt) {
        this.outdt = outdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.SHIPMENT_HEADER.ACCDT
     *
     * @return the value of ACOAPP_OMS.SHIPMENT_HEADER.ACCDT
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    public Date getAccdt() {
        return accdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.SHIPMENT_HEADER.ACCDT
     *
     * @param accdt the value for ACOAPP_OMS.SHIPMENT_HEADER.ACCDT
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    public void setAccdt(Date accdt) {
        this.accdt = accdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.SHIPMENT_HEADER.LOGISTICS_STATUS_ID
     *
     * @return the value of ACOAPP_OMS.SHIPMENT_HEADER.LOGISTICS_STATUS_ID
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    public String getLogisticsStatusId() {
        return logisticsStatusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.SHIPMENT_HEADER.LOGISTICS_STATUS_ID
     *
     * @param logisticsStatusId the value for ACOAPP_OMS.SHIPMENT_HEADER.LOGISTICS_STATUS_ID
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    public void setLogisticsStatusId(String logisticsStatusId) {
        this.logisticsStatusId = logisticsStatusId == null ? null : logisticsStatusId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.SHIPMENT_HEADER.LOGISTICS_STATUS_REMARK
     *
     * @return the value of ACOAPP_OMS.SHIPMENT_HEADER.LOGISTICS_STATUS_REMARK
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    public String getLogisticsStatusRemark() {
        return logisticsStatusRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.SHIPMENT_HEADER.LOGISTICS_STATUS_REMARK
     *
     * @param logisticsStatusRemark the value for ACOAPP_OMS.SHIPMENT_HEADER.LOGISTICS_STATUS_REMARK
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    public void setLogisticsStatusRemark(String logisticsStatusRemark) {
        this.logisticsStatusRemark = logisticsStatusRemark == null ? null : logisticsStatusRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.SHIPMENT_HEADER.RFOUTDAT
     *
     * @return the value of ACOAPP_OMS.SHIPMENT_HEADER.RFOUTDAT
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    public Date getRfoutdat() {
        return rfoutdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.SHIPMENT_HEADER.RFOUTDAT
     *
     * @param rfoutdat the value for ACOAPP_OMS.SHIPMENT_HEADER.RFOUTDAT
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    public void setRfoutdat(Date rfoutdat) {
        this.rfoutdat = rfoutdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.SHIPMENT_HEADER.ITEM_FLAG
     *
     * @return the value of ACOAPP_OMS.SHIPMENT_HEADER.ITEM_FLAG
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    public String getItemFlag() {
        return itemFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.SHIPMENT_HEADER.ITEM_FLAG
     *
     * @param itemFlag the value for ACOAPP_OMS.SHIPMENT_HEADER.ITEM_FLAG
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    public void setItemFlag(String itemFlag) {
        this.itemFlag = itemFlag == null ? null : itemFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.SHIPMENT_HEADER.OWNER
     *
     * @return the value of ACOAPP_OMS.SHIPMENT_HEADER.OWNER
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    public String getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.SHIPMENT_HEADER.OWNER
     *
     * @param owner the value for ACOAPP_OMS.SHIPMENT_HEADER.OWNER
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    public void setOwner(String owner) {
        this.owner = owner == null ? null : owner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.SHIPMENT_HEADER.VOLUME
     *
     * @return the value of ACOAPP_OMS.SHIPMENT_HEADER.VOLUME
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    public String getVolume() {
        return volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.SHIPMENT_HEADER.VOLUME
     *
     * @param volume the value for ACOAPP_OMS.SHIPMENT_HEADER.VOLUME
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    public void setVolume(String volume) {
        this.volume = volume == null ? null : volume.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.SHIPMENT_HEADER.WEIGHT
     *
     * @return the value of ACOAPP_OMS.SHIPMENT_HEADER.WEIGHT
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    public String getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.SHIPMENT_HEADER.WEIGHT
     *
     * @param weight the value for ACOAPP_OMS.SHIPMENT_HEADER.WEIGHT
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    public void setWeight(String weight) {
        this.weight = weight == null ? null : weight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.SHIPMENT_HEADER.WAREHOUSE_ID
     *
     * @return the value of ACOAPP_OMS.SHIPMENT_HEADER.WAREHOUSE_ID
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    public String getWarehouseId() {
        return warehouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.SHIPMENT_HEADER.WAREHOUSE_ID
     *
     * @param warehouseId the value for ACOAPP_OMS.SHIPMENT_HEADER.WAREHOUSE_ID
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    public void setWarehouseId(String warehouseId) {
        this.warehouseId = warehouseId == null ? null : warehouseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.SHIPMENT_HEADER.ORDER_REF_REVISION
     *
     * @return the value of ACOAPP_OMS.SHIPMENT_HEADER.ORDER_REF_REVISION
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    public Long getOrderRefRevision() {
        return orderRefRevision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.SHIPMENT_HEADER.ORDER_REF_REVISION
     *
     * @param orderRefRevision the value for ACOAPP_OMS.SHIPMENT_HEADER.ORDER_REF_REVISION
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    public void setOrderRefRevision(Long orderRefRevision) {
        this.orderRefRevision = orderRefRevision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.SHIPMENT_HEADER.ASSOCIATED_ID
     *
     * @return the value of ACOAPP_OMS.SHIPMENT_HEADER.ASSOCIATED_ID
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    public Long getAssociatedId() {
        return associatedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.SHIPMENT_HEADER.ASSOCIATED_ID
     *
     * @param associatedId the value for ACOAPP_OMS.SHIPMENT_HEADER.ASSOCIATED_ID
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    public void setAssociatedId(Long associatedId) {
        this.associatedId = associatedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.SHIPMENT_HEADER.PROD_PRICE
     *
     * @return the value of ACOAPP_OMS.SHIPMENT_HEADER.PROD_PRICE
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    public BigDecimal getProdPrice() {
        return prodPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.SHIPMENT_HEADER.PROD_PRICE
     *
     * @param prodPrice the value for ACOAPP_OMS.SHIPMENT_HEADER.PROD_PRICE
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    public void setProdPrice(BigDecimal prodPrice) {
        this.prodPrice = prodPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.SHIPMENT_HEADER.MAIL_PRICE
     *
     * @return the value of ACOAPP_OMS.SHIPMENT_HEADER.MAIL_PRICE
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    public BigDecimal getMailPrice() {
        return mailPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.SHIPMENT_HEADER.MAIL_PRICE
     *
     * @param mailPrice the value for ACOAPP_OMS.SHIPMENT_HEADER.MAIL_PRICE
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    public void setMailPrice(BigDecimal mailPrice) {
        this.mailPrice = mailPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.SHIPMENT_HEADER.POST_FEE1
     *
     * @return the value of ACOAPP_OMS.SHIPMENT_HEADER.POST_FEE1
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    public BigDecimal getPostFee1() {
        return postFee1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.SHIPMENT_HEADER.POST_FEE1
     *
     * @param postFee1 the value for ACOAPP_OMS.SHIPMENT_HEADER.POST_FEE1
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    public void setPostFee1(BigDecimal postFee1) {
        this.postFee1 = postFee1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.SHIPMENT_HEADER.POST_FEE2
     *
     * @return the value of ACOAPP_OMS.SHIPMENT_HEADER.POST_FEE2
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    public BigDecimal getPostFee2() {
        return postFee2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.SHIPMENT_HEADER.POST_FEE2
     *
     * @param postFee2 the value for ACOAPP_OMS.SHIPMENT_HEADER.POST_FEE2
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    public void setPostFee2(BigDecimal postFee2) {
        this.postFee2 = postFee2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.SHIPMENT_HEADER.CLEAR_FEE
     *
     * @return the value of ACOAPP_OMS.SHIPMENT_HEADER.CLEAR_FEE
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    public BigDecimal getClearFee() {
        return clearFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.SHIPMENT_HEADER.CLEAR_FEE
     *
     * @param clearFee the value for ACOAPP_OMS.SHIPMENT_HEADER.CLEAR_FEE
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    public void setClearFee(BigDecimal clearFee) {
        this.clearFee = clearFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.SHIPMENT_HEADER.RECONCIL_FLAG
     *
     * @return the value of ACOAPP_OMS.SHIPMENT_HEADER.RECONCIL_FLAG
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    public Short getReconcilFlag() {
        return reconcilFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.SHIPMENT_HEADER.RECONCIL_FLAG
     *
     * @param reconcilFlag the value for ACOAPP_OMS.SHIPMENT_HEADER.RECONCIL_FLAG
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    public void setReconcilFlag(Short reconcilFlag) {
        this.reconcilFlag = reconcilFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.SHIPMENT_HEADER.RECONCIL_USER
     *
     * @return the value of ACOAPP_OMS.SHIPMENT_HEADER.RECONCIL_USER
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    public String getReconcilUser() {
        return reconcilUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.SHIPMENT_HEADER.RECONCIL_USER
     *
     * @param reconcilUser the value for ACOAPP_OMS.SHIPMENT_HEADER.RECONCIL_USER
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    public void setReconcilUser(String reconcilUser) {
        this.reconcilUser = reconcilUser == null ? null : reconcilUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.SHIPMENT_HEADER.RECONCIL_DATE
     *
     * @return the value of ACOAPP_OMS.SHIPMENT_HEADER.RECONCIL_DATE
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    public Date getReconcilDate() {
        return reconcilDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.SHIPMENT_HEADER.RECONCIL_DATE
     *
     * @param reconcilDate the value for ACOAPP_OMS.SHIPMENT_HEADER.RECONCIL_DATE
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    public void setReconcilDate(Date reconcilDate) {
        this.reconcilDate = reconcilDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.SHIPMENT_HEADER.CLEAR_POST_FEE
     *
     * @return the value of ACOAPP_OMS.SHIPMENT_HEADER.CLEAR_POST_FEE
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    public BigDecimal getClearPostFee() {
        return clearPostFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.SHIPMENT_HEADER.CLEAR_POST_FEE
     *
     * @param clearPostFee the value for ACOAPP_OMS.SHIPMENT_HEADER.CLEAR_POST_FEE
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    public void setClearPostFee(BigDecimal clearPostFee) {
        this.clearPostFee = clearPostFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.SHIPMENT_HEADER.ACCOUNT
     *
     * @return the value of ACOAPP_OMS.SHIPMENT_HEADER.ACCOUNT
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.SHIPMENT_HEADER.ACCOUNT
     *
     * @param account the value for ACOAPP_OMS.SHIPMENT_HEADER.ACCOUNT
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACOAPP_OMS.SHIPMENT_HEADER.POST_FEE3
     *
     * @return the value of ACOAPP_OMS.SHIPMENT_HEADER.POST_FEE3
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    public BigDecimal getPostFee3() {
        return postFee3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACOAPP_OMS.SHIPMENT_HEADER.POST_FEE3
     *
     * @param postFee3 the value for ACOAPP_OMS.SHIPMENT_HEADER.POST_FEE3
     *
     * @mbggenerated Thu Oct 31 18:26:51 CST 2013
     */
    public void setPostFee3(BigDecimal postFee3) {
        this.postFee3 = postFee3;
    }
}